.github/workflows/nodejs.yml, data-serving/data-service/package.json, verification/curator-service/package.json
This is the default nodejs.yml config, with some small tweaks/customization for our monorepo. Should run on sending a PR and on pushing to `master`.
Can always tweak this in the future, but should prevent most breakages for now.
=> Setting up a base GitHub action for our Node apps.

data-serving/data-service/jest.config.js, data-serving/data-service/nodemon.json, data-serving/data-service/package-lock.json, data-serving/data-service/package.json, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/controllers/home.ts, data-serving/data-service/src/index.ts, data-serving/data-service/src/server.ts, data-serving/data-service/test/case.test.ts, data-serving/data-service/test/home.test.ts, data-serving/data-service/test/index.test.ts
Handful of set up items, and kicking off the case data API.
- Separate the app and server -- mostly for testability.
- Add controllers dir where route handling logic is kept.
- Add a /cases route and initial (skeletal) read handlers.
- Set up testing framework, add tests, and add an npm script for testing.
- Add nodemon (hot refresh) and a dev convenience script.
(Don't mind the delta -- it's reasonable aside from auto-gen'd changes to `package-lock.json`).
=> Create serving structure and add skeletal read case data methods to the data service.

data-serving/data-service/.eslintignore, data-serving/data-service/.eslintrc.js, data-serving/data-service/.prettierrc.js, data-serving/data-service/package-lock.json, data-serving/data-service/package.json
Getting the linter/formatter ready to rock. Not applying in this PR; don't want to confuse the issue; I'll apply fixes separately.
Mostly just using the baseline recommended config for TS. Made a couple judgement calls on some common rules. Feel free to turn this thread into a holy war on quotes/tabs/etc.
=> Configure linting (eslint) and integrate prettier for auto-formatting.

.github/workflows/nodejs.yml
Just the data-service app for now (until there's testing in curator-service).
Works well -- see `Checks` tab.
=> Run npm test as part of our Node js GH action.

data-serving/data-service/package.json
Think we're all set on project config miscellany for now. Thanks for the review(s)!
=> Adding description and repository data to data-service package.json.

verification/curator-service/src/controllers/sources.ts, verification/curator-service/src/index.ts, verification/curator-service/test/sources.test.ts
=> Add config api routes and chose a different default port for curation service

data-serving/data-service/package-lock.json, data-serving/data-service/package.json, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/controllers/home.ts, data-serving/data-service/src/index.ts, data-serving/data-service/test/case.test.ts
Sets up body parsing and express validation, so separating this into an initial PR from the remainder of the mutation methods.
=> Base create method for case data

verification/curator-service/jest-mongodb-config.js, verification/curator-service/jest.config.js, verification/curator-service/package-lock.json, verification/curator-service/package.json, verification/curator-service/src/controllers/sources.ts, verification/curator-service/src/index.ts, verification/curator-service/src/model/source.ts, verification/curator-service/test/sources.test.ts
Small changes from ab's original PR https://github.com/open-covid-data/healthmap-gdo-temp/pull/24:
- using one env variable, not sure why the need for conenction url + db name was there, a single string seems sufficient
- this is not using the environment validator that the data service is using (to be reconciled in a subsequent PR)
- using promises instead of callbacks when using mongoose find()
=> Connect curator service to mongodb using mongoose

.github/workflows/docker.yml, .github/workflows/nodejs.yml, data-serving/data-service/.dockerignore, data-serving/data-service/Dockerfile, dev/README.md, dev/docker-compose.dev.yml, dev/docker-compose.yml, dev/run_stack.sh, verification/curator-service/Dockerfile
In which github, running as docker containers, starts action workflows as docker containers which download docker containers and run stuff in them. We need to go deeper. And I need to regain my sanity.
=> added docker compose stack and github action

data-serving/samples/line-list.json
Sorry for the large diff here. Starting with this PR, I'm going to format this json with `python -m json.tool line-list.json` for consistency, unless anyone has another preference.
=> Update sample line list data per schema changes

.github/workflows/nodejs.yml, data-serving/data-service/.dockerignore, dev/docker-compose.dev.yml, dev/docker-compose.yml, verification/curator-service/api/.dockerignore, verification/curator-service/api/package-lock.json, verification/curator-service/api/package.json, verification/curator-service/api/src/index.ts, verification/curator-service/ui/.dockerignore, verification/curator-service/ui/Dockerfile, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/LinelistCaseRow.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
- Got rid of {Case} imports from parent directory as it's forbidden by docker for good reasons.
- stopped using proxy config and instead used environment variables to pass the api endpoint to the react app (https://create-react-app.dev/docs/adding-custom-environment-variables/). Using cors in express server to support UI calling the api server.
=> added UI to the dev stack

data-serving/data-service/package.json, data-serving/data-service/src/util/validate-env.ts, dev/docker-compose.yml, dev/test_all.sh, verification/curator-service/api/package.json, verification/curator-service/api/src/util/validate-env.ts, verification/curator-service/ui/package.json
Also added a dev script to run all tests instead of having to change directory and run npm test in all of them.
=> changed db to covid19 and added global test script

verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/App.test.tsx, verification/curator-service/ui/src/components/App.tsx
=> Add react-router to map /new to a WIP page

verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/NewCaseForm.test.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx
No client-side validation yet, I can add that later once we "finalize" the schema.
Submitting just prints the form content as json to the console.
Uses formik to make react forms less painful and some material components when available (all except date picker).
=> add basic form to submit new case

data-serving/scripts/constants.py, data-serving/scripts/convert_data.py, data-serving/scripts/converters.py
Running on 10% of the data set, only getting a single parsing error (incorrect data format)
Here's an example output for a fairly robust row:
```
{
"demographics": {
"age": {
"range": {
"min": 70.0,
"max": 79.0
}
},
"sex": "Male"
},
"events": [
{
"name": "onsetSymptoms",
"date": {
"range": {
"min": {
"$date": "2020-02-23T00:00:00Z"
},
"max": {
"$date": "2020-02-23T00:00:00Z"
}
}
}
},
{
"name": "confirmed",
"date": {
"range": {
"min": {
"$date": "2020-03-06T00:00:00Z"
},
"max": {
"$date": "2020-03-06T00:00:00Z"
}
}
}
}
]
},
```
=> [data converter] Convert events and demographics fields

data-serving/scripts/constants.py, data-serving/scripts/convert_data.py, data-serving/scripts/converters.py
Example output:
```
{
"demographics": {
"age": {
"range": {
"min": 53.0,
"max": 53.0
}
},
"sex": "Male"
},
"events": [
{
"name": "onsetSymptoms",
"date": {
"range": {
"min": {
"$date": "2020-03-19T00:00:00Z"
},
"max": {
"$date": "2020-03-19T00:00:00Z"
}
}
}
},
{
"name": "confirmed",
"date": {
"range": {
"min": {
"$date": "2020-03-25T00:00:00Z"
},
"max": {
"$date": "2020-03-25T00:00:00Z"
}
}
}
}
],
"location": {
"id": 951.0,
"country": "Mexico",
"geometry": {
"latitude": 20.833333,
"longitude": -89.0
}
},
"importedCase": {
"ID": "004-11146",
"admin_id": 951.0,
"age": "53",
"chronic_disease_binary": false,
"country": "Mexico",
"date_confirmation": "25.03.2020",
"date_onset_symptoms": "19.03.2020",
"geo_resolution": "admin1",
"latitude": 20.833333,
"longitude": -89.0,
"province": "Yucatan", …
```
=> Add conversions for location and importedCase fields

data-serving/data-service/src/index.ts, verification/curator-service/ui/src/components/NewCaseForm.test.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx
This contains just a bit more than the minimum  set of fields currently required, I could submit new cases successfully this way even though it's not super pretty.
=> Submit form to create new cases

data-serving/data-service/schemas/cases.schema.json, data-serving/samples/line-list.json, dev/.vscode/settings.json
Based on evolutions of the schema:
- Rename fields
- Restructure fields
- Fix typos
- Add validation to ensure no additional fields are added to objects
TESTED=Applied schema to my collection and successfully imported the example
Next I'll adjust the node schema
=> Update the line-list schema and sample document to the latest model

data-serving/data-service/src/model/case.ts, verification/curator-service/ui/src/components/NewCaseForm.test.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx
Note: events' dates ranges are not returned by the service, not sure why.
=> fix frontend to be able to submit cases as per new schema

data-serving/data-service/schemas/cases.schema.json, data-serving/samples/line-list.json, verification/curator-service/ui/src/components/LinelistCaseRow.test.tsx, verification/curator-service/ui/src/components/LinelistCaseRow.tsx, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/NewCaseForm.test.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx
Also updates the UI to parse these fields
I have a dream to create an API so I don't have to change schema + UI in the same PR... maybe later this week!
=> Update mongodb schema & example json to use range format in mongoose

data-serving/scripts/README.md, data-serving/scripts/convert_data.py, data-serving/scripts/converters.py
- 99.7% of rows from the CSV file convert successfully to JSON
+ Of the 0.3% of rows with errors:
- 99.6% have age values outside the valid range
- 0.4% have invalid date formats
- 100% of rows from `cases.json` import successfully into mongodb using `cases.schema.json` as a validator
These two fixes resolved all import errors:
- Bug where single symptom/chronicDisease values weren't put in array format
- ageRange was double-nested (uuugh range field my nemesis)
And for funsies, to reduce the lossiness of the conversion, I supported additional age formats.
=> Fix all mongodb import errors and some conversion errors

verification/curator-service/ui/src/components/App.tsx
=> remove padding around table, let's use the space we have

verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
=> Modify how the table actions are created and implement deleting a row

dev/docker-compose.yml, verification/curator-service/api/env, verification/curator-service/api/package-lock.json, verification/curator-service/api/package.json, verification/curator-service/api/src/controllers/auth.ts, verification/curator-service/api/src/index.ts, verification/curator-service/api/src/model/user.ts, verification/curator-service/api/src/util/validate-env.ts, verification/curator-service/api/test/auth.test.ts
Tested locally with a project of mine waiting for Gaurav to create a project for us.
Still a no-op because no /api routes are being forced to be authenticated yet.
=> Support authentication via google oauth 2.0

data-serving/scripts/converters.py, data-serving/scripts/utils.py
Accidentally tested ingestion with an old dataset -- this change was needed. My b!
=> I was wrong: mongodb needs the Z(ulu) at the end of time strings

dev/docker-compose.yml, verification/curator-service/api/package-lock.json, verification/curator-service/api/package.json, verification/curator-service/api/src/index.ts, verification/curator-service/api/src/util/validate-env.ts, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx
=> proxy api cases requests from cutator service to data service

.github/workflows/ingestion-aws-sam-deploy.yml
The action I'm using is a little goofy -- doesn't always return the right error code, it seems.
But it works for now. GitHub is adding native SAM-CLI support soon:
https://github.com/actions/virtual-environments/issues/94
=> Basic GitHub action deploying SAM stack.

verification/curator-service/ui/src/components/LinelistTable.tsx
=> make ID column not editable

verification/curator-service/ui/src/components/LinelistTable.tsx
- Makes sex a dropdown between Male / Female.
- Makes age be a number
- Makes source URL required.
=> Add field validators when editting or adding rows

verification/curator-service/api/src/index.ts
=> simpler init of mongo session

data-serving/data-service/src/model/case.ts, data-serving/data-service/src/model/source.ts, data-serving/data-service/test/model/source.test.ts
This is how I'm proposing to refactor the case model, moving sub-schemas into their own files -- LMK what you think.
=> Pull the source schema + interface into its own file

data-serving/scripts/setup-db/tsconfig.json, dev/README.md, dev/setup_db.sh
(Also a small fix to tsconfig in the scripts dir that I noticed when testing the new script)
TESTED=Dropped my covid19 database, ran the script, and confirmed that:
- covid19 db exists
- it has a cases collection
- the collection has a validator
- the collection has 100 documents in it
=> Add a dev script to set up the local cases db and populate it with sample data

data-serving/scripts/setup-db/package-lock.json, data-serving/scripts/setup-db/package.json
Ran:
`npm ci`
`npm run setup-cases`
great success
=> Prefix setup-db commands with npm install; update package-lock.json with npm ci

verification/curator-service/ui/src/components/LinelistTable.tsx
second PR ever for you -- what a day!
=> Fix format of events sent over the wire

verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
=> Display API errors in the UI

verification/curator-service/ui/src/components/SourceTable.test.tsx, verification/curator-service/ui/src/components/SourceTable.tsx
And adding required fields.
For reference, #148.
=>  Update SourceTable to align with ~current data model.

verification/curator-service/ui/cypress.json, verification/curator-service/ui/cypress/fixtures/example.json, verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.js, verification/curator-service/ui/cypress/plugins/index.js, verification/curator-service/ui/cypress/support/commands.js, verification/curator-service/ui/cypress/support/index.js, verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json
This definitely needs a lot of refinement, but achieves putting the cypress infrastructure in place.
Right now you must run the stack locally first, and then run the tests against the local server. In a future PR I will look to add this to our CI tests where it starts its own server before running. But for local development it's much easier to run your own local stack than to have the test start one up.
I left some example code + comments in while everyone is getting acquainted with Cypress.
=> Add a cypress integration test for the linelist table

verification/curator-service/ui/src/components/SourceTable.test.tsx, verification/curator-service/ui/src/components/SourceTable.tsx
Implementation is analogous to the Linelist table component. Update (and display of error codes) in subsequent PR(s).
=> Enable creating rows in the SourceTable component.

data-serving/data-service/api/openapi.yaml, data-serving/data-service/package-lock.json, data-serving/data-service/package.json, data-serving/data-service/src/index.ts
Not sure if this is the lib we want to go with but a proof of concept -- LMK what you think!
Video of error when incorrect id format supplied: https://screencast.googleplex.com/cast/NTkyMzk5OTI0NDYxNTY4MHwyMzhhMzU2NS0xOQ
=> Use Express OpenAPI Validator to validate /api/cases/:id GET requests

.github/workflows/integration-tests.yml, data-serving/data-service/jest.config.js, data-serving/data-service/nodemon.json, data-serving/data-service/package.json, data-serving/data-service/tsconfig.build.json, data-serving/data-service/tsconfig.json, verification/curator-service/api/jest.config.js, verification/curator-service/api/nodemon.json, verification/curator-service/api/package.json, verification/curator-service/api/tsconfig.build.json, verification/curator-service/api/tsconfig.json
I also let autoformat do its json thing, not liking it but at least it's consistent.
=> include tests in tsconfig

verification/curator-service/api/src/controllers/auth.ts, verification/curator-service/api/test/auth.test.ts
Didn't plug it in any index.ts routing yet so it's a no-op for now.
=> add roles checking middleware

verification/scripts/README.md, verification/scripts/roles.js
I didn't go the full typescript/npm package way as Kelly did for the other scripts as this is really a one-liner doable in mongo shell only.
=> add script to set initial roles

verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/Users.test.tsx, verification/curator-service/ui/src/components/Users.tsx
=> Add ability to change users' roles in the manage users page

data-serving/data-service/api/openapi.yaml
https://screencast.googleplex.com/cast/NDU5MzQwMDE3MzAzNTUyMHxhN2IyZWUxYy1kMg
=> Add list cases API definition

verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/cypress/integration/components/SourceTableTest.spec.ts, verification/curator-service/ui/cypress/plugins/index.ts, verification/curator-service/ui/cypress/support/commands.ts, verification/curator-service/ui/cypress/support/index.ts, verification/curator-service/ui/src/components/SourceTable.tsx
=> Add a cypress test for SourceTable. 

data-serving/data-service/api/openapi.yaml
=> Add updateCase endpoint to API definition

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/cypress/integration/components/UsersTest.spec.ts, verification/curator-service/ui/src/components/App.tsx
Removes Terms of Service and Privacy Policy links since they didn't go anywhere.
=> Restrict pages access based on role

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/CumulativeCharts.tsx
I will add the Dataset freshness metrics and Dataset completeness metrics in the next PR.
=> Add a page for cumulative charts

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/CompletenessCharts.tsx, verification/curator-service/ui/src/components/FreshnessCharts.tsx
=> Add freshness and completeness chart pages

verification/curator-service/api/src/clients/aws-events-client.ts, verification/curator-service/api/src/controllers/sources.ts, verification/curator-service/api/src/model/source.ts, verification/curator-service/api/test/clients/aws-events-client.test.ts, verification/curator-service/api/test/model/source.test.ts, verification/curator-service/api/test/sources.test.ts
Small QoL change as I'm getting down to brass tacks and configuring rules.
=> Populate rule description in our AWS CW events client library

dev/README.md
To honor Spencer's sacrifice of being our guinea pig and getting the stack up and running, a few updates to our documentation to help future brave souls.
@SpencerMarks-IDHA: These are just my notes from our convo last week but definitely feel free to add in more!
=> Consolidate getting started instructions into dev/README.md

.github/workflows/case-data-update.yml
=> Fix cron schedule to be at 5am precisely, not... every minute during the 5am hour

aws/README.md, aws/curator.yaml, aws/data.yaml, data-serving/data-service/api/openapi.yaml, ingestion/functions/README.md, ingestion/functions/retrieval/retrieval.py, ingestion/functions/template.yaml, verification/curator-service/api/openapi/openapi.yaml, verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/cypress/integration/components/EpidNavbarTest.spec.ts, verification/curator-service/ui/public/index.html, verification/curator-service/ui/public/manifest.json, verification/curator-service/ui/src/components/App.test.tsx, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/Navbar.test.tsx, verification/curator-service/ui/src/components/Navbar.tsx, verification/scripts/README.md
I didn't change the lambdas in the ingestion folders because the "epid" is embedded in the ARNs of the functions and so that's going to break things, I'll let @axmb decide what he wants to do with those.
=> rename epid to global health

verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/NewCaseForm.test.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx
Shruti has begun a spec on a form for inputing a single case manually. This will be the beginning of that.
=> Resurrect NewCaseForm

.github/workflows/curator-api-node.yml, .github/workflows/curator-ui-node.yml, .github/workflows/data-service-node.yml, verification/curator-service/ui/package.json
That's free for public repo and provides nice viz on PRs
=> Upload coverage to codecov

ingestion/functions/parsing/india/india.py, ingestion/functions/parsing/india/india_test.py, ingestion/functions/parsing/india/input_event.json, ingestion/functions/parsing/india/requirements.txt, ingestion/functions/parsing/india/sample_data.json
Some notes:
- Sorry for the large diff!
- As stated, this isn't parsing every field. It's parsing most fields, and everything we show in the UI --  this is probably a decent stopping point until we finalize the case schema/API.
- Not adding the function to the SAM template; will do that subsequently. Doing separately since I'll have to tweak a couple things in the retrieval function when I do this, and there's already enough going on in this PR.
=> Initial parser for COVID19-India API data

verification/curator-service/api/src/index.ts
Re: https://www.npmjs.com/package/express-session#cookiesecure
=> Set trust proxy to allow the use of secure session cookies behind nginx.

verification/curator-service/ui/src/components/App.tsx
https://material-ui.com/components/css-baseline/
Before:
After:
(seeing it in real life makes more difference than on a screenshot I promise ;) )
=> use css baseline to have a consistent CSS experience

verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
Also remove column sorting ability as it is not supported by the backend yet.
=> Add geo admin areas to linelist table

verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/NewCaseForm.tsx
In a future PR I will change it to a red ! icon on error.
=> Show checkbox in table of contents when field is complete

verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/NewCaseForm.tsx
=> Scroll field into view when clicking on table of contents row

data-serving/data-service/schemas/cases.schema.json, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/NewCaseForm.test.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx
- Adds Yup for form validation.
- Can enter age range or age, but not both
- Changes schema to accept either double or int
=> Add fields for age in new case form

data-serving/data-service/schemas/cases.schema.json, data-serving/data-service/src/model/travel.ts, data-serving/samples/cases.json
Still TBD whether we're putting enums in the schema so will put it for now but happy to pare down the schema later
=> Update enum values for travelHistory.purpose per spec

data-serving/data-service/schemas/cases.schema.json, data-serving/data-service/src/model/case.ts, data-serving/data-service/src/model/pathogen.ts, data-serving/data-service/test/model/data/case.full.json, data-serving/data-service/test/model/data/pathogen.full.json, data-serving/data-service/test/model/data/pathogen.minimal.json, data-serving/data-service/test/model/pathogen.test.ts, data-serving/samples/cases.json, data-serving/scripts/convert-data/README.md, data-serving/scripts/convert-data/convert_data.py, data-serving/scripts/convert-data/converters.py
Remove fields:
- sequenceSources
- additionalInformation
Add required field 'id'
=> Bring pathogens field up to spec

verification/curator-service/api/src/geocoding/suggest.ts, verification/curator-service/api/src/index.ts, verification/curator-service/api/test/geocoding/fake.test.ts, verification/curator-service/api/test/geocoding/suggest.test.ts, verification/curator-service/api/test/index.test.ts
To be used by autocompletion input once we figure it out.
=> Implement /api/geocode/suggest endpoint to suggest geocodes

verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
Also adds admin3 and proper geo resolution fields.
=> proper display of lat lng in the linelist table and remove add functionality

verification/curator-service/ui/src/components/NewCaseForm.test.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Location.tsx, verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx
In preparation to adding autosuggest there.
=> Move Location form to its own component

verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx, verification/curator-service/ui/src/components/new-case-form-fields/FormikAutocomplete.tsx
Pulled the autocomplete component into it's own file so it can be used in multiple places.
=> Add profession to NewCaseForm and LinelistTable

data-serving/data-service/schemas/cases.schema.json, data-serving/data-service/src/model/date.ts, data-serving/data-service/src/model/location.ts, verification/curator-service/api/src/controllers/cases.ts, verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/cypress/support/commands.ts, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Location.test.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Location.tsx, verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx
Had to change the schema for lat lng to be numbers to accept "2" as a lat for example otherwise an error would be thrown.
Also only send non empty even fields because the mongo schema validator doesn't like null dates.
=> Suggest geocodes and send them with the new form request

verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
=> Add link in linelist table to add a new case for curators

verification/curator-service/ui/src/components/Users.test.tsx, verification/curator-service/ui/src/components/Users.tsx
Stop-gap until we implement UI paging in the manage users page
=> Raise page limit of users

data-serving/data-service/schemas/cases.schema.json, data-serving/samples/cases.json
- Fix a bug in the example case from a schema change last week
- While I was in there, did a quick cleanup (removing geo_resolution from importedCase)
=> Fix example case.json

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/src/components/App.test.tsx, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/Home.tsx
Add all links that were previously in the home page and divide them appropriately.
The choice is icons is my fault, blame me :)
Logged in full powers:
Logged out:
=> Finish drawer

aws/curator.yaml, aws/data.yaml
They are being built by docker hub, will merge once ready.
=> bump curator and data to 0.0.6

ingestion/functions/parsing/india/india.py, ingestion/functions/parsing/india/india_test.py, ingestion/functions/parsing/india/input_event.json, ingestion/functions/retrieval/retrieval.py, ingestion/functions/retrieval/retrieval_test.py, ingestion/functions/template.yaml
Couple parsing updates based on the data spec, and on what we're now showing in the linelist UI. Not extracting every possible field to fit the schema, since I imagine a couple things might still change, and this isn't in the first wave of data we're focused on productionizing.
=> Update retrieval/India parsing functions: (1) based on case schema changes; (2) to use the upsert API

verification/curator-service/api/src/controllers/cases.ts, verification/curator-service/ui/src/components/NewCaseForm.tsx
And just send the error message not the whole error as the http error, now it shows up properly, it didn't before.
=> Catch geocode errors

suggest/route_of_transmission.txt
This is blocking reading this file async for multiselect
=> Add routes of transmission values to github

verification/curator-service/ui/src/components/NewCaseForm.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Location.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Notes.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Source.tsx, verification/curator-service/ui/src/index.css
Somehow with a small screen the demographics for was fine but all the other fieldsets were using 60% of the demographics size, removing the 60% width fixed that and the form is of a reasonable size by default.
Also make notes multiline because it is really.
=> new form UI nit fixes to make it look better and more mobile friendly

dev/README.md
=> Fix incorrect path in README

data-serving/data-service/Dockerfile, verification/curator-service/Dockerfile, verification/curator-service/api/Dockerfile, verification/curator-service/ui/Dockerfile
https://nodejs.org/en/about/releases/
=> upgrade node to version 14

data-serving/scripts/convert-data/constants.py, data-serving/scripts/convert-data/converters.py
And 2 other small changes:
- Add 2 new sheet names
- Fix an error in the error logging - delightfully ironic
=> Add a few more location abbreviations to the conversion script

verification/curator-service/ui/cypress/integration/components/EditCase.spec.ts, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/Case.tsx, verification/curator-service/ui/src/components/EditCase.test.tsx, verification/curator-service/ui/src/components/EditCase.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Location.tsx
Moved the case definition that we get from the /api/cases calls to somewhere common to share it.
This caught a lot of undefined checks that needed to be done as well.
=> Add edit case component

verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/Case.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx, verification/curator-service/ui/src/components/new-case-form-fields/GenomeSequences.tsx, verification/curator-service/ui/src/components/new-case-form-fields/NewCaseFormValues.tsx, verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx
=> Add genome sequencing to NewCaseForm

verification/curator-service/ui/src/components/App.tsx
This doesn't break the other parts of the website as it did when I changed the primary color of the theme.
=> Make appbar background white

aws/curator.yaml, aws/data.yaml
this is building now on docker hub
=> bump prod version to 0.0.8

verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx, verification/curator-service/ui/src/components/new-case-form-fields/FormikFields.tsx
=> Add 'Unknown' display to undefined select fields

verification/curator-service/ui/cypress/integration/components/EditCase.spec.ts, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/NewCaseForm.test.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx, verification/curator-service/ui/src/components/Utils.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Events.tsx, verification/curator-service/ui/src/components/new-case-form-fields/FormikFields.tsx, verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Notes.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Source.tsx
I removed two unit tests that checked that requests were sent because those requests are no longer sent until all the required fields are filled out. That unit test didn't provide any added coverage compared to the integration tests, so I don't think they are worth keeping around. Let me know if you disagree.
In future PRs we can look into using <FastField>s to speed up the I/O on the form: https://github.com/formik/formik/issues/671
=> Add required fields to NewCaseForm

verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts, verification/curator-service/ui/src/components/BulkCaseForm.test.tsx, verification/curator-service/ui/src/components/BulkCaseForm.tsx, verification/curator-service/ui/src/components/BulkCaseFormValues.tsx
=> Set up form for bulk upload interface; separate file upload from submission

verification/curator-service/ui/src/components/common-form-fields/FormikFields.tsx, verification/curator-service/ui/src/components/common-form-fields/Source.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx, verification/curator-service/ui/src/components/new-case-form-fields/GenomeSequences.tsx, verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Notes.tsx
https://jaredpalmer.com/formik/docs/api/fastfield
=> Use FastField where possible to speed up the form

verification/curator-service/ui/src/components/App.tsx
=> Make table scroll rather than entire page scroll

verification/curator-service/ui/cypress/integration/components/ViewCase.spec.ts, verification/curator-service/ui/src/components/ViewCase.test.tsx, verification/curator-service/ui/src/components/ViewCase.tsx, verification/curator-service/ui/src/components/fixtures/fullCase.json
Doing small incremental changes to display components and associated unit tests, will finish the integration tests after the component is complete.
=> case data and demographics rendering of case

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/Charts.tsx
I remember Shru saying she preferred keeping the sidebar low-weight, I like that too.
99% taken from https://material-ui.com/components/tabs/#simple-tabs
=> Move charts to one page with tabs

verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/Case.tsx, verification/curator-service/ui/src/components/NewCaseForm.test.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx, verification/curator-service/ui/src/components/new-case-form-fields/GenomeSequences.tsx, verification/curator-service/ui/src/components/new-case-form-fields/NewCaseFormValues.tsx, verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx
=> Update travel history and genome sequencing to spec

.github/workflows/curator-api-node.yml, .github/workflows/curator-ui-node.yml, .github/workflows/data-service-node.yml, verification/curator-service/ui/cypress/fixtures/fullCase.json, verification/curator-service/ui/cypress/integration/components/EditCase.spec.ts, verification/curator-service/ui/cypress/integration/components/ViewCase.spec.ts, verification/curator-service/ui/cypress/support/commands.ts, verification/curator-service/ui/src/components/NewCaseForm.tsx, verification/curator-service/ui/src/components/ViewCase.test.tsx, verification/curator-service/ui/src/components/fixtures/fullCase.json, verification/curator-service/ui/src/components/new-case-form-fields/Transmission.tsx
- show "edit case" instead of "submit case" when editing a case
- pass initial value to chip input
- make fixture for full case pass yup validation
=> More tests for edit case form and minor fixes identified from these tests

verification/curator-service/ui/cypress/integration/components/ViewCase.spec.ts, verification/curator-service/ui/src/components/ViewCase.test.tsx, verification/curator-service/ui/src/components/ViewCase.tsx
They are not in the mocks, I left a question but for now this seems reasonable.
=> Add notes to details page

verification/curator-service/ui/src/components/Case.tsx, verification/curator-service/ui/src/components/ViewCase.test.tsx, verification/curator-service/ui/src/components/ViewCase.tsx
Okay not really, there's the scroll-to-section panel left to do, will do it next ;)
=> Finish details page

verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/NewCaseForm.tsx
Otherwise hospital and outcome events would be set with empty date ranges.
Before:
After:
=> Filter dates on null AND undefined when submitting case

dev/docker-compose.dev.yml, verification/curator-service/Dockerfile, verification/curator-service/ui/src/components/StaticMap.tsx, verification/curator-service/ui/src/components/ViewCase.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Location.tsx
In new case form:
In details page:
=> add map to location components

verification/curator-service/ui/cypress/integration/components/EditCase.spec.ts, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/CaseForm.tsx
=> Add a success message for CaseForm

verification/curator-service/ui/cypress/fixtures/bulk_data.csv, verification/curator-service/ui/cypress/fixtures/bulk_data_with_case_count.csv, verification/curator-service/ui/cypress/fixtures/updated_bulk_data.csv, verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts, verification/curator-service/ui/src/components/BulkCaseForm.tsx
Includes one minor bugfix to the hospitalization event. Relatedly, we should standardize constructing data like this across our UI components.
=> Adding a caseCount field to bulk upload

verification/curator-service/ui/cypress/integration/components/EditCase.spec.ts, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/Case.tsx, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/ViewCase.test.tsx, verification/curator-service/ui/src/components/ViewCase.tsx, verification/curator-service/ui/src/components/new-case-form-fields/CaseFormValues.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx
Last field to be added to the form!! 🎉
=> Add symptoms status to the case form

verification/curator-service/ui/src/components/Profile.tsx, verification/curator-service/ui/src/components/common-form-fields/Source.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Location.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Notes.tsx
To simplify them when they don't require something done on component mount for example.
=> functionalize components

verification/curator-service/ui/src/components/common-form-fields/FormikFields.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Events.tsx, verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx
- Dialog closes when you select a date
- Date pickers open up to show the confirmed date, hopefully saving them from having to scroll through the months multiple times.
=> Some date picker enhancements

data-serving/data-service/schemas/cases.schema.json, data-serving/data-service/src/model/transmission.ts, data-serving/data-service/test/controllers/case.test.ts, data-serving/data-service/test/model/transmission.test.ts, suggest/route_of_transmission.txt, verification/curator-service/ui/cypress/integration/components/Curator.spec.ts, verification/curator-service/ui/src/components/common-form-fields/FormikFields.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Transmission.tsx
Fixes #328
also fixes a flaky pagination test (my bad) that was running fine or not depending on the hour of the day /sigh.
=> freesolo the transmission suggest box

suggest/place_of_transmission.txt, suggest/professions.txt
As per Slack discussion, for #440 and #437
=> Add new suggestion options

verification/curator-service/ui/cypress/integration/components/Curator.spec.ts, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/cypress/integration/utils/enterSource.ts, verification/curator-service/ui/src/components/BulkCaseForm.test.tsx, verification/curator-service/ui/src/components/BulkCaseForm.tsx, verification/curator-service/ui/src/components/CaseForm.test.tsx, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/EditCase.test.tsx, verification/curator-service/ui/src/components/common-form-fields/Source.tsx, verification/curator-service/ui/src/components/new-case-form-fields/CaseFormValues.tsx
Pretty beefy change, though the bulk of the interesting diff is in `Source.tsx`.
More or less finalizes source/caseReference handling pre-UX'ification.
=> Update the Source component to operate on CaseReference; add creation dialog

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/src/components/App.tsx
- Shows menu open by default
- Doesn't close menu when selecting a menu option
- Keeps app bar in static location and allows opening/closing menu from hamburger icon
=> Menu improvements

verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
=> Add selection to table and allow deleting selected rows

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/cypress/integration/components/Curator.spec.ts, verification/curator-service/ui/cypress/integration/components/EditCase.spec.ts, verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/EditCase.tsx, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/setupTests.ts
Also adds the create new menu.
Screenshots because the gif file size is too big :(
=> Have CaseForm show up as a modal

verification/curator-service/ui/cypress/integration/components/Curator.spec.ts, verification/curator-service/ui/cypress/integration/components/EditCase.spec.ts, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/cypress/integration/components/ViewCase.spec.ts, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/AppModal.tsx, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/ViewCase.tsx
Pulls the modal logic out into a separate component to be shared.
=> Put ViewCase into a modal

verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts
=> Collapse a Cypress test chain.

verification/curator-service/ui/src/components/CaseForm.test.tsx, verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx, verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx
Fixes https://docs.google.com/presentation/d/1Fg-UYsIB8oq03-VIHR0CP8G6ym02HxjCpyDcroheFzc/edit#slide=id.g8b4f04bb4d_0_52
=> Hide location values until a location has been selected

verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/common-form-fields/FormikFields.tsx, verification/curator-service/ui/src/components/common-form-fields/Source.tsx, verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx
- Use "Required" instead of "Required field"
- Have "Required" always be present, and change text color to red when error is triggered
- Remove asterisks
=> Fix required fields UI

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/CaseForm.tsx
Addresses remainder of https://docs.google.com/presentation/d/1Fg-UYsIB8oq03-VIHR0CP8G6ym02HxjCpyDcroheFzc/edit#slide=id.g8b4f04bb4d_0_9
#475
=> Change title and add cancel button to CaseForm

verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/bulk-case-form-fields/FileUpload.tsx, verification/curator-service/ui/src/components/common-form-fields/FieldTitle.tsx, verification/curator-service/ui/src/components/common-form-fields/Source.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Events.tsx, verification/curator-service/ui/src/components/new-case-form-fields/GenomeSequences.tsx, verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Notes.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Pathogens.tsx, verification/curator-service/ui/src/components/new-case-form-fields/PreexistingConditions.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Transmission.tsx, verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx
https://docs.google.com/presentation/d/1Fg-UYsIB8oq03-VIHR0CP8G6ym02HxjCpyDcroheFzc/edit#slide=id.g8bdf5ed96c_0_0
#475
=> Update styling of section titles and add option for tooltips

verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/SourceTable.tsx
Makes the page size dropdown functional. Fixes https://docs.google.com/presentation/d/1Fg-UYsIB8oq03-VIHR0CP8G6ym02HxjCpyDcroheFzc/edit#slide=id.g8b4f04bb4d_0_16
#475
=> Fix paging in tables

verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/BulkCaseForm.tsx
=> Put bulk case form in a modal

verification/curator-service/ui/cypress/integration/components/Curator.spec.ts, verification/curator-service/ui/cypress/integration/components/EditCase.spec.ts, verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/cypress/integration/components/ViewCase.spec.ts, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/SourceTable.tsx
=> Add vertical scroll to table as opposed to window

data-serving/data-service/src/model/demographics.ts, data-serving/data-service/src/model/location.ts, data-serving/data-service/src/model/travel.ts, data-serving/data-service/test/model/demographics.test.ts, data-serving/data-service/test/model/travel.test.ts, verification/curator-service/api/globalConfig.json, verification/curator-service/ui/cypress/fixtures/bad_bulk_data.csv, verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts
Per decision [here](https://docs.google.com/document/d/1u0FUPZ6vG00irfPaw7CLwekWxpeE7n70WlRRnMQAi-g/edit#heading=h.rijffgfpldij)
=> Remove enums from mongoose schema

verification/curator-service/ui/cypress/integration/components/Curator.spec.ts, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/ViewCase.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx
=> s/ethnicity/race \/ ethnicity and make it free-form text field

verification/curator-service/ui/src/components/BulkCaseForm.test.tsx, verification/curator-service/ui/src/components/BulkCaseForm.tsx, verification/curator-service/ui/src/components/Case.tsx
Can't write a meaningful test for this, but here's a gif:
=> Apply geocoding limits in bulk case form.

data-serving/data-service/api/openapi.yaml, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/index.ts, data-serving/data-service/test/controllers/case.test.ts
There was a bug in `index.ts` on dataserver leading to validation not actually taking place -- this fixes it
=> Enable request & response validation in data server and fix resulting issues

verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts, verification/curator-service/ui/src/components/BulkCaseForm.tsx
=> Add basic stats for successful uploads.

verification/curator-service/ui/cypress/integration/components/Curator.spec.ts, verification/curator-service/ui/cypress/integration/components/EditCase.spec.ts, verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/CaseForm.test.tsx, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/EditCase.test.tsx, verification/curator-service/ui/src/components/EditCase.tsx, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/Profile.test.tsx, verification/curator-service/ui/src/components/ViewCase.test.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx
- After hitting submit the CaseForm is closed and the LinelistTable data is refreshed
- Removes the add button on the LinelistTable
- Shows the added/edited case row as highlighted in the LinelistTable
- Shows success message above LinelistTable
Before adding a row:
After adding a row:
=> Navigate to /cases after submitting the CaseForm

verification/curator-service/ui/src/components/CaseForm.tsx
=> Update error message on age range fields

verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/LinelistTable.tsx
Should address the flaky test (and functionality)
=> Wait for delete calls to finish before refreshing table

verification/curator-service/ui/cypress/integration/components/Curator.spec.ts, verification/curator-service/ui/src/components/common-form-fields/FormikFields.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Transmission.tsx, verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx
Adds the free-form text as an option to select so that it's clear free-form text is allowed. Decided on that UX with Shroo.
=> Allow free-form text for several fields

verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts, verification/curator-service/ui/src/components/BulkCaseForm.test.tsx, verification/curator-service/ui/src/components/BulkCaseForm.tsx, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
Highlights all added and updated row. Shows success message on /cases.
Updated message style after taking that screen recording:
=> Navigate to /cases after successful bulk upload

verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx
As per feedback, now:
Fixes #469
=> fix unclear places autocomplete

verification/curator-service/ui/src/components/common-form-fields/FormikFields.tsx
=> add format to invalid date error message

verification/curator-service/api/openapi/openapi.yaml
The right one is /geocode/suggest
=> remove unused openapi spec

verification/curator-service/ui/src/components/AppModal.tsx
Related to #617 and curator testing report
=> Make the grey area of the modal responsive to the screensize

verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/ViewCase.test.tsx, verification/curator-service/ui/src/components/ViewCase.tsx
=> add edit button to case details component

verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/CaseForm.test.tsx, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/EditCase.test.tsx
Add
We don't have a link to the data entry guide yet so didn't add that.
=> add title to edit page as per mocks

README.md, aws/README.md, data-serving/data-service/package.json, data-serving/scripts/setup-db/package.json, ingestion/functions/README.md, ingestion/functions/parsing/common/python/parsing_lib.py, verification/curator-service/api/package.json, verification/curator-service/ui/src/components/bulk-case-form-fields/FileUpload.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Pathogens.tsx, verification/curator-service/ui/src/components/new-case-form-fields/PreexistingConditions.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Transmission.tsx
DO NOT SUBMIT until the rename happens.
Created this PR with VSCode search and replace on all files in repo, hopefully it didn't miss anything.
For #607
=> rename repo and org

suggest/route_of_transmission.txt, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/common-form-fields/FormikFields.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Events.tsx, verification/curator-service/ui/src/components/new-case-form-fields/PreexistingConditions.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx, verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx
=> Fix UX of selecting Unknown fields

verification/curator-service/ui/src/components/ViewCase.tsx
Feedback from UX session was that the grey titles didn't appear like links, so I made those tentatively just look like links.
Also using plain old html inner links instead of the third party library used in the case for to link to internal parts of the page, I am not sure why was that needed? Happy to move to that one and/or change the form one to be similar once we agree on the way to do this.
Fixes #429
=> add left side links to navigate in case details

verification/curator-service/ui/cypress/integration/components/Curator.spec.ts, verification/curator-service/ui/src/components/LinelistTable.tsx
=> link to newly created or edited case

verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/EditCase.test.tsx
=> Change in Wording from 'Edit case' to 'Submit case edit'

verification/curator-service/ui/src/components/ViewCase.tsx
Trying to get back some of my screen estate 💻 
Related to #617
=> Do not show the details page nav menu on small screens

data-serving/data-service/api/openapi.yaml, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/index.ts, data-serving/data-service/test/controllers/case.test.ts
=> Add an endpoint for listing the most frequently used symptoms

verification/curator-service/ui/src/components/App.test.tsx, verification/curator-service/ui/src/components/App.tsx
Had to rewrite the App component into a functional component because there is no class component access to media queries.
Related to #617
=> Automatically hide/show the app menu on small/medium+ screens

verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/cypress/support/commands.ts, verification/curator-service/ui/src/components/CaseForm.test.tsx, verification/curator-service/ui/src/components/EditCase.test.tsx, verification/curator-service/ui/src/components/common-form-fields/FormikFields.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx
Fixes #439
(lag is only from gif creation, not on actual site)
=> Add frequently used symptoms as clickable chips

verification/curator-service/ui/cypress/integration/components/Curator.spec.ts, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
- Do not store results when conditions are not met
- Do not show green checkmark when conditions are not met
Fixes #618
=> Handle conditional fields better

verification/curator-service/ui/src/components/CaseForm.tsx
Other sections with required fields are already implemented as such. 
Fixes #329
=> Show table of contents checkmark once required fields are complete

verification/curator-service/ui/src/components/BulkCaseForm.tsx, verification/curator-service/ui/src/components/CaseForm.test.tsx, verification/curator-service/ui/src/components/bulk-case-form-fields/FileUpload.tsx, verification/curator-service/ui/src/components/common-form-fields/Source.tsx
=> Arrange bulk upload form inputs per spec

data-serving/data-service/api/openapi.yaml, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/test/controllers/case.test.ts
=> Add num_cases param to create endpoint

verification/curator-service/api/openapi/openapi.yaml, verification/curator-service/api/test/cases.test.ts, verification/curator-service/ui/cypress/integration/components/Curator.spec.ts, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/CaseForm.tsx
=> Use batch create endpoint in UI

verification/curator-service/ui/src/components/BulkCaseForm.test.tsx, verification/curator-service/ui/src/components/BulkCaseForm.tsx, verification/curator-service/ui/src/index.css
=> Add reference links to bulk upload page.

verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/LinelistTable.tsx
Better matches the mocks and search upon {enter} instead of on every characters.
=> replace linelist searchbar with our own input field

verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/common-form-fields/Source.tsx
=> Allow typing in a source without selecting a dropdown option

data-serving/data-service/api/openapi.yaml, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/util/search.ts, data-serving/data-service/test/controllers/case.test.ts, data-serving/data-service/test/util/search.test.ts
Future improvements:
- add tooltip to searchbar to explain the search syntax
- add more keywords based on UX feedback
=> Support keywords in search

verification/curator-service/ui/src/components/LinelistTable.tsx
=> add tooltip for search syntax

verification/curator-service/ui/src/components/EditCase.tsx, verification/curator-service/ui/src/components/ViewCase.test.tsx, verification/curator-service/ui/src/components/ViewCase.tsx
I like them better as you don't have to do all that WithStyle() export and properties extension madness.
=> Rewrite edit and and view case into function components

data-serving/data-service/src/index.ts, data-serving/data-service/src/model/demographics.ts, data-serving/data-service/src/model/location.ts, data-serving/data-service/src/model/pathogen.ts, data-serving/data-service/src/model/revision-metadata.ts
=> index keyword fields

verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/BulkCaseForm.tsx, verification/curator-service/ui/src/components/bulk-case-form-fields/BulkCaseFormValues.tsx, verification/curator-service/ui/src/components/common-form-fields/FormikFields.tsx, verification/curator-service/ui/src/components/common-form-fields/Source.tsx
=> Maintain the sourceName when changing the sourceURL

verification/curator-service/ui/src/components/common-form-fields/FormikFields.tsx
=> Add helperText to date fields indicating format

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/index.tsx
=> Show previous page when closing modal if it exists

verification/curator-service/ui/src/components/CaseForm.test.tsx, verification/curator-service/ui/src/components/CaseForm.tsx
Changes CaseForm to a functional component while here.
Addresses some of #617
=> Don't show table of contents when screen is small

verification/curator-service/ui/cypress/fixtures/bulk_data_with_all_fields.csv, verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts, verification/curator-service/ui/src/components/BulkCaseForm.tsx
I'm also adding a separate Cypress E2E test; while it's slightly overkill for this PR, I'll be using it for #646.
=> Support hyphenated ageRange field in bulk upload.

verification/curator-service/ui/src/components/App.tsx
=> Have button text ellipsis on small screens

verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts, verification/curator-service/ui/cypress/integration/components/Curator.spec.ts, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/ViewCase.test.tsx, verification/curator-service/ui/src/components/ViewCase.tsx, verification/curator-service/ui/src/components/util/date.tsx
Without leading 0s in MM or DD
Fixes #532
=> Render dates as YYYY-MM-DD throughout console

verification/curator-service/ui/src/components/CaseForm.tsx
Warning example: ` You have provided an out-of-range value 'undefined' for the select (name="traveledPrior30Days") component`
=> Remove some warnings from UI

verification/curator-service/ui/src/components/util/date.tsx
=> Use UTC dates

verification/curator-service/api/src/geocoding/adminsFetcher.ts, verification/curator-service/api/test/geocoding/adminsFetcher.test.ts
=> do not throw when no admin name is found

verification/curator-service/ui/README.md, verification/curator-service/ui/cypress/fixtures/bulk_data_with_all_fields.csv, verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts, verification/curator-service/ui/src/components/BulkCaseForm.tsx
=>  Add additional fields to bulk upload format.

verification/curator-service/ui/src/components/App.tsx
=> Add some styles to app menu

verification/curator-service/ui/src/components/LinelistTable.tsx
Includes putting the alerts above the search bar
=> Tidy up styling on linelist

verification/curator-service/ui/src/components/App.tsx
This way the selectedMenuIndex is also set on page load
=> Update how the selectedMenuIndex is set

verification/curator-service/ui/cypress/integration/components/SourceTableTest.spec.ts, verification/curator-service/ui/src/components/SourceTable.tsx
=> make json csv dropdown for format edit field

data-serving/data-service/jest.config.js, data-serving/data-service/package-lock.json, data-serving/data-service/package.json, data-serving/data-service/src/index.ts, data-serving/data-service/src/types/appmetrics-dash.d.ts, verification/curator-service/api/jest.config.js, verification/curator-service/api/package-lock.json, verification/curator-service/api/package.json, verification/curator-service/api/src/index.ts, verification/curator-service/api/src/types/appmetrics-dash.d.ts
I'm not in love with the package, but it's pretty solid (more or less) out of the box.
Seems to be the best solution short of investing in Prometheus/Grafana.
=> Add basic monitoring with appmetrics-dash

ingestion/functions/parsing/ch_zurich/input_event.json, ingestion/functions/parsing/common/python/parsing_lib/input_event.json, ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py, ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py, ingestion/functions/parsing/india/input_event.json, ingestion/functions/retrieval/retrieval.py, ingestion/functions/retrieval/retrieval_test.py
=> extract source id from event instead of s3 path

CONTRIBUTING.md, LICENSE
Pretty standard stuff in there, should raise our community profile status:
https://github.com/globaldothealth/list/community
=> Add contribution guidelines

verification/curator-service/ui/cypress/integration/components/ProfileTest.spec.ts, verification/curator-service/ui/cypress/integration/components/UsersTest.spec.ts, verification/curator-service/ui/src/components/Profile.tsx
=> nicify profile page using chips and tooltips over roles

verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/cypress/support/commands.ts, verification/curator-service/ui/src/components/CaseForm.test.tsx, verification/curator-service/ui/src/components/EditCase.test.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Transmission.tsx
Essentially copied #664
Fixes #638
=> Add frequently used places of transmission as clickable chips

verification/curator-service/ui/cypress/integration/components/Curator.spec.ts, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx
=> Don't allow adding symptoms when status is presymptomatic

data-serving/data-service/api/openapi.yaml, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/index.ts, data-serving/data-service/test/controllers/case.test.ts
Essentially copied #658
Needed for #634
=> Add an endpoint for listing the most frequently used occupations

data-serving/data-service/src/index.ts, verification/curator-service/api/openapi/openapi.yaml, verification/curator-service/api/package-lock.json, verification/curator-service/api/src/controllers/cases.ts, verification/curator-service/api/src/index.ts, verification/curator-service/api/test/cases.test.ts
Essentially copied #661
Needed for #634
=> Add endpoint in curator-service API for listing most frequently used occupations

ingestion/functions/README.md
Covers retrieval, parsing and UI actions that need to be taken to test locally.
=> More comprehensive docs for e2e function tests

verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/cypress/support/commands.ts, verification/curator-service/ui/src/components/CaseForm.test.tsx, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/EditCase.test.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx
=> Add frequently used occupations as clickable chips

ingestion/functions/README.md, verification/curator-service/ui/cypress/integration/components/SourceTableTest.spec.ts, verification/curator-service/ui/src/components/SourceTable.test.tsx, verification/curator-service/ui/src/components/SourceTable.tsx
I think this is the first time we have a column handle more than one field so that's nice.
(video even includes a live bug fix, what a gif(t))
=> nicer formatting of date filtering column

verification/curator-service/ui/src/components/App.tsx
=> Add some styling

verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
=> Add some more styling

verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts, verification/curator-service/ui/cypress/integration/components/Curator.spec.ts, verification/curator-service/ui/cypress/integration/components/EditCase.spec.ts, verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
=> Only show a subset of fields in linelist table

verification/curator-service/api/openapi/openapi.yaml, verification/curator-service/api/src/controllers/uploads.ts, verification/curator-service/api/src/index.ts, verification/curator-service/api/test/model/data/source.full.json, verification/curator-service/api/test/uploads.test.ts
We can add filtering/paging in the future as needed.
=> Add an endpoint for listing all uploads

ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py, ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py, verification/curator-service/api/openapi/openapi.yaml, verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts, verification/curator-service/ui/src/components/BulkCaseForm.tsx, verification/curator-service/ui/src/components/Case.tsx, verification/curator-service/ui/src/components/ViewCase.tsx
=> Create and finalize upload objects for bulk upload (and one ADI addition)

.github/workflows/case-data-export-prod.yml, data-serving/scripts/export-data/export_data.sh
Also changes the workflow to run when the export script is updated
=> Add flag to data export script to export valid json

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/cypress/support/commands.ts, verification/curator-service/ui/src/components/Alerts.test.tsx, verification/curator-service/ui/src/components/Alerts.tsx, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/SourceTable.tsx, verification/curator-service/ui/src/components/Users.tsx
Just shows static content for now (and not content appropriate for all cases). Will continue to update in future PRs.
=> Add beginnings of alerts panel

verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/cypress/support/commands.ts, verification/curator-service/ui/src/components/LinelistTable.tsx
There are outstanding questions on the spec for this. Adding a couple simple actions to manipulate verification status for now.
=> Add a toggle to verify cases from the linelist

verification/curator-service/ui/cypress/integration/components/Alerts.spec.ts, verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/cypress/support/commands.ts, verification/curator-service/ui/src/components/Alerts.test.tsx, verification/curator-service/ui/src/components/Alerts.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/ViewCase.tsx, verification/curator-service/ui/src/components/util/links.tsx
=> After clicking on alert, navigate to linelist filtered for upload id

ingestion/functions/README.md
One of the joys of new systems, you figure out what is missing from docs :)
=> add links to sam cli install procedure

ingestion/functions/retrieval/retrieval.py
This made the retrieval of japan data timeout even after 10minutes, with this change the retrieval works on 25s 🤷
=> do not parse-and-dump to json when retrieving content

.github/workflows/ingestion-aws-sam-build.yml, .github/workflows/ingestion-functions-python.yml
Apologies for any commit churn. Not feasible to test this locally with `act`.
=> Use the sam CLI, now installed by default in action images, to sam build PRs

verification/curator-service/ui/cypress/tsconfig.json, verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json
https://docs.cypress.io/guides/references/changelog.html#5-0-0
Was gettig the error
```
Error: Webpack Compilation Error
/Users/timothe/healthmap/list/verification/curator-service/ui/cypress/tsconfig.json
[tsl] ERROR
TS5053: Option 'sourceMap' cannot be specified with option 'inlineSourceMap'.
This occurred while Cypress was compiling and bundling your test code. This is usually caused by:
- A missing file or dependency
- A syntax error in the file or one of its dependencies
Fix the error in your code and re-run your tests.
```
when upgrading so I changed the source map generation config, then it passed.
=> upgrade cypress to v5

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/cypress/integration/components/AutomatedSourceForm.spec.ts, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/AutomatedSourceForm.test.tsx, verification/curator-service/ui/src/components/AutomatedSourceForm.tsx, verification/curator-service/ui/src/components/common-form-fields/FormikFields.tsx
We'll replace the "add source" table function once this is completed.
=> Add skeletal new automated source form

ingestion/functions/common/common_lib.py, ingestion/functions/common/common_lib_test.py, ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py, ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py, ingestion/functions/retrieval/retrieval.py
Minimal real delta here. There's a net decrease in LoC, due to axing some duplication. Thereby advancing our quest for 0 LoC.
Tested local invoke for retrieval/parsing, which both appear to work just fine.
=> Move remaining common code into common_lib.py

verification/curator-service/ui/cypress/integration/components/UploadsTableTest.spec.ts, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/UploadsTable.test.tsx, verification/curator-service/ui/src/components/UploadsTable.tsx
=> Add beginnings of uploads table

verification/curator-service/api/src/controllers/sources.ts, verification/curator-service/api/src/model/automation.ts, verification/curator-service/api/test/model/automation.test.ts, verification/curator-service/api/test/sources.test.ts, verification/curator-service/ui/cypress/integration/components/SourceTableTest.spec.ts, verification/curator-service/ui/src/components/SourceTable.tsx
=> Make it possible to update source with a parser arn only without requiring a schedule

README.md, data-serving/data-service/api/openapi.yaml, data-serving/data-service/nodemon.json, dev/docker-compose.dev.yml, verification/curator-service/api/nodemon.json, verification/curator-service/api/openapi/openapi.yaml
Installed a VSCode extension to lint/validate the specs, this PR fixes most of the lint warnings that showed up (missing tags and tags definition mostly).
=> hot reload openapi and add more descriptions and examples

verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/LinelistTable.tsx
Need to update actions and exact styling in future PRs
=> Add a button for selecting all rows across pages

verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
=> Add confirmation dialog before deleting cases

.github/workflows/case-data-export-prod.yml, .github/workflows/case-data-update-dev.yml
Remove all mongodb packages prior to installing the versions we want
(sorry, the issue doesn't repro locally so just... trying stuff)
=> 'last' fix for installing mongodb in workflows

data-serving/data-service/src/index.ts, ingestion/functions/README.md, verification/curator-service/api/openapi/openapi.yaml, verification/curator-service/api/src/index.ts
I think this is final this time :) Can't think of anywhere to add new descriptions or examples...
Also make it look nicer by using themes.
https://github.com/ostranme/swagger-ui-themes#monokai
=> Complete openapi documentation

aws/curator.yaml, aws/data.yaml
I'll wait for the build before I merge and apply.
=> Update prod version to 0.0.12

data-serving/data-service/api/openapi.yaml, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/controllers/preprocessor.ts, data-serving/data-service/src/index.ts, data-serving/data-service/test/controllers/case.test.ts, data-serving/data-service/test/controllers/preprocessor.test.ts, verification/curator-service/api/openapi/openapi.yaml, verification/curator-service/api/src/controllers/cases.ts, verification/curator-service/api/src/index.ts, verification/curator-service/api/test/cases.test.ts
Sorry this got fairly large in the end!
=> Add an endpoint for batch updates

verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/LinelistTable.tsx
Endpoint was added in https://github.com/globaldothealth/list/pull/881
=> Use batch update endpoint in linelist

data-serving/scripts/export-data/case_fields.yaml, data/README.md
=> export verified status in data export

verification/curator-service/api/src/controllers/auth.ts, verification/curator-service/api/src/controllers/cases.ts, verification/curator-service/api/src/controllers/sources.ts, verification/curator-service/api/src/controllers/uploads.ts, verification/curator-service/api/src/controllers/users.ts, verification/curator-service/api/src/geocoding/adminsFetcher.ts, verification/curator-service/api/src/geocoding/fake.ts, verification/curator-service/api/src/geocoding/geocoder.ts, verification/curator-service/api/src/geocoding/mapbox.ts, verification/curator-service/api/src/geocoding/suggest.ts, verification/curator-service/api/src/model/admin.ts, verification/curator-service/api/src/schemas/README.md, verification/curator-service/ui/src/components/new-case-form-fields/CaseFormValues.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Location.test.tsx
- document (all ?) methods in curator service
- fix tslint errors/warnings in frontend as I went along
- try to use [tsdoc](https://github.com/microsoft/tsdoc) as much as I could, I did not convert all existing one-liners though as it was too tedious, perhaps a vscode extension can do that.
=> add moar commentz

data-serving/data-service/src/controllers/preprocessor.ts
Separating this out as not to confound some content changes I'm making.
The @ts-ignore error doesn't seem to be new, looking at the config; though I can't say for sure, as I don't think I've edited this file.
=> Clean up or suppress warnings/errors in preprocessor.ts

.github/workflows/case-data-export-prod.yml
whoever so wishes to approve, shall
=> Fix arg name in prod export script

data-serving/data-service/src/index.ts, verification/curator-service/api/src/index.ts
=> change api docs theme to material

data-serving/data-service/src/controllers/preprocessor.ts, data-serving/data-service/test/controllers/case.test.ts, data-serving/data-service/test/controllers/preprocessor.test.ts
After writing this, I considered instead filtering the value of `request.body.cases` in the revisionMetadata middleware, which seems promising. I'll take a look at that in a different PR.
=> Don't create revisions if a case is unchanged in batchUpsert.

verification/curator-service/ui/src/components/LinelistTable.tsx
Based on https://www.figma.com/file/TqqzDnXF4KTBAGUchpt4mQ/Global.Health-Marketing-Website?node-id=471%3A434
=> Style selected table toolbar

.github/workflows/curator-service-package.yml, .github/workflows/data-service-package.yml
First step of #671 
Will change the aws config and docs after packages are built.
I just built one to check the workflow worked as expected: https://github.com/orgs/globaldothealth/packages/container/list%2Fcuratorservice/28025
=> add workflow to push to github container registry

verification/curator-service/ui/src/components/Charts.tsx
=> Update charts styling

verification/curator-service/api/src/index.ts, verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/cypress/integration/components/SourceTableTest.spec.ts, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/SourceTable.tsx
=> hide source and upload tables from readers

ingestion/functions/parsing/common/python/parsing_lib/input_event.json, ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py, ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
For #754
Next is local storage vs s3 storage.
=> Handle local cookie login in parsing functions as well

data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/util/search.ts, data-serving/data-service/test/controllers/case.test.ts, data-serving/data-service/test/util/search.test.ts, verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/LinelistTable.tsx
=> Throw upon invalid search request and display an error message in the UI

data-serving/data-service/src/controllers/case.ts, verification/curator-service/api/src/controllers/auth.ts, verification/curator-service/api/src/controllers/cases.ts, verification/curator-service/api/src/controllers/sources.ts, verification/curator-service/api/src/controllers/uploads.ts, verification/curator-service/api/src/controllers/users.ts, verification/curator-service/api/src/geocoding/suggest.ts, verification/curator-service/api/src/index.ts, verification/curator-service/api/test/sources.test.ts, verification/curator-service/ui/cypress/integration/components/AutomatedSourceForm.spec.ts, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/AutomatedSourceForm.tsx, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/EditCase.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/SourceRetrievalButton.tsx, verification/curator-service/ui/src/components/SourceTable.tsx, verification/curator-service/ui/src/components/UploadsTable.tsx, verification/curator-service/ui/src/components/Users.tsx, verification/curator-service/ui/src/components/ViewCase.tsx
As I did in #950 previously but even simpler this time using ||.
Example of error before:
(styling is weird btw for large errors)
Example of same error now:
Fixes #954
=> catch axios and express vlaidator errors properly

verification/curator-service/api/src/controllers/auth.ts, verification/curator-service/api/src/model/user.ts, verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/src/components/App.test.tsx, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/User.tsx
Fixes #949 
Logged out:
Logged in:
=> more profile from left menu to top right

data-serving/data-service/api/openapi.yaml, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/test/controllers/case.test.ts, verification/curator-service/api/openapi/openapi.yaml, verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/LinelistTable.tsx
=> If there is a search query only download search results

ingestion/functions/README.md, ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
Also some docs about debugging.
=> More python types annotations to make it clearer what is expected from parsers

data-serving/data-service/schemas/cases.indexes.json
=> add index for sort order

aws/curator.yaml, aws/data.yaml
=> bump prod to 0.0.18

verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
=> Update search bar to new spec

verification/curator-service/ui/src/components/App.tsx
=> Add COVID-19 title to UI

data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/controllers/preprocessor.ts, data-serving/data-service/src/index.ts, data-serving/data-service/test/controllers/case.test.ts, data-serving/data-service/test/controllers/preprocessor.test.ts
=> Create case revisions on deletion

verification/curator-service/ui/src/components/LinelistTable.tsx
By showing an error dialog rather than a confirmation dialog if they try to delete more than 10,000 cases.
Also removes the text that "rows cannot be recovered" because they now can after #982
=> Don't allow curators to delete more than 10,000 from UI

aws/curator.yaml, aws/data.yaml
We need to push so that prod knows about your breaking change upload_id->upload_ids I think from https://github.com/globaldothealth/list/pull/927/files
=> bump prod to 0.0.19

verification/curator-service/ui/public/index.html, verification/curator-service/ui/src/components/LinelistTable.tsx
=> Set font to Inter for table rows and pagination bar

verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/SearchBar.tsx
=> Move search bar and download button to app bar

verification/curator-service/ui/src/components/LinelistTable.tsx
=> Disable the button and show spinner icon when downloading

verification/curator-service/api/openapi/openapi.yaml, verification/curator-service/api/src/controllers/sources.ts, verification/curator-service/api/src/index.ts, verification/curator-service/api/src/model/source.ts, verification/curator-service/api/src/util/validate-env.ts, verification/curator-service/api/test/auth.test.ts, verification/curator-service/api/test/cases.test.ts, verification/curator-service/api/test/geocoding/fake.test.ts, verification/curator-service/api/test/index.test.ts, verification/curator-service/api/test/model/data/source.full.json, verification/curator-service/api/test/sources.test.ts, verification/curator-service/api/test/uploads.test.ts, verification/curator-service/api/test/users.test.ts
Other notification scenarios, and UI, forthcoming.
Re: #978
=> Set up email notifications, and fire for an initial (source creation) case

verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/UploadsTable.tsx
#1006
This way if you open a case details view and close it, the search results remain.
=> Save search in browser history

verification/curator-service/api/test/uploads.test.ts
=> Fix describe nesting in uploads.test.ts

verification/curator-service/api/src/clients/email-client.ts, verification/curator-service/api/src/controllers/uploads.ts, verification/curator-service/api/src/index.ts, verification/curator-service/api/test/uploads.test.ts
=> Send notifications for failed uploads

ingestion/functions/parsing/hongkong/hongkong.py, ingestion/functions/parsing/hongkong/hongkong_test.py, ingestion/functions/parsing/hongkong/sample_data.csv
=> parse imported case as having traveled in the past 30days

verification/curator-service/ui/src/components/Users.test.tsx, verification/curator-service/ui/src/components/Users.tsx
=> show user pics in table

data-serving/scripts/export-data/case_fields.yaml
=> Add some missing fields to the downloads

verification/curator-service/ui/src/components/ViewCase.tsx
=> s/Data source link/Data source URL

ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
=> Only send 250 cases per batch upsert from ingestion functions

aws/README.md, aws/curator.yaml, aws/data.yaml
=> Increase resources available to prod jobs

verification/curator-service/ui/src/components/LinelistTable.tsx
A guess at why the data was corrupted as described in #940 is because a user clicked the verify/unverify buttons a second time before the first request was finished. By adding a loading indicator it will make it more clear to the user that an action is happening, and prevent them from taking the action again before the first one is over.
Fixes #939
=> Add loading indicators to linelist actions

verification/curator-service/ui/cypress/integration/components/UploadsTableTest.spec.ts, verification/curator-service/ui/src/components/UploadsTable.test.tsx, verification/curator-service/ui/src/components/UploadsTable.tsx
=> Add source name to uploads table

aws/curator.yaml, aws/data.yaml
Will drop data and reimport after that's pushed.
=> bump prod version

verification/scripts/gen_boundaries.sh
=> prefer english admin names

verification/curator-service/ui/src/components/UploadsTable.tsx
=> Put source name column before source url column

verification/curator-service/ui/src/components/LinelistTable.tsx
=> Change downloaded filename

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/TermsOfService.tsx, verification/curator-service/ui/src/index.css
The text in the terms of use is still being finalized
For #1092
=> Add terms of use

ingestion/functions/common/common_lib.py, ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py, ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
=> Store current created/updated count for failed uploads as well

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/src/components/App.tsx
=> do not show Home button when user has no roles, redirect to /cases

ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py, ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
For #1124
```
Raw file retrieved at /tmp/tmp0_0ahaur
Sending 250 cases, total so far: 0
Current speed: 90 cases/sec
Max estimate: 80710 in the remaining 894 sec
Sending 250 cases, total so far: 250
Current speed: 100 cases/sec
Max estimate: 89700 in the remaining 892 sec
Sending 250 cases, total so far: 500
Current speed: 105 cases/sec
Max estimate: 94200 in the remaining 890 sec
Sending 250 cases, total so far: 750
Current speed: 108 cases/sec
Max estimate: 96904 in the remaining 888 sec
Sending 250 cases, total so far: 1000
Current speed: 108 cases/sec
Max estimate: 96830 in the remaining 885 sec
Sending 250 cases, total so far: 1250
Current speed: 110 cases/sec
Max estimate: 98630 in the remaining 883 sec
Sending 250 cases, total so far: 1500
Current speed: 112 cases/sec
Max estimate: …
```
=> add estimate cases per second and total to parser output

data-serving/data-service/package-lock.json, data-serving/data-service/src/geocoding/suggest.ts, verification/curator-service/api/package-lock.json, verification/curator-service/api/src/controllers/uploads.ts, verification/curator-service/api/test/uploads.test.ts
=> Sort uploads by most recent first

verification/curator-service/ui/src/components/UploadsTable.tsx
So that they are not hidden behind long sourceURLs
Fixes #1120
=> Move created/updated # columns before source info

verification/curator-service/ui/src/components/App.tsx
=> Add padding to main content when menu is hidden

aws/README.md, aws/curator-ingress-config-map.yaml
=> Compress text/csv responses in nginx

verification/curator-service/ui/src/components/App.tsx
=> Add a link to the data dictionary in the account menu

aws/curator.yaml, aws/data.yaml
Changelog:
https://github.com/globaldothealth/list/compare/0.1.1...0.1.2
=> bump prod to 0.1.2

verification/curator-service/ui/src/components/BulkCaseForm.tsx
=> display error message instead of whole stringified error

data-serving/data-service/src/controllers/case.ts
#1107 #1109
Hopefully this fixes the OOM in the data-service
=> Stream mongo docs in download action

data-serving/data-service/src/util/search.ts, data-serving/data-service/test/controllers/case.test.ts, data-serving/data-service/test/util/search.test.ts
=> fix query at runtime to support mistyped keyword searches

aws/README.md, aws/dashboard.yaml, aws/display_dashboard_token.sh
=> Deploy kubernetes dashboard

ingestion/functions/README.md
=> Document zip support for sources

aws/curator.yaml, aws/data.yaml
Changelog: https://github.com/globaldothealth/list/compare/0.1.3...0.1.4
=> bump prod to 0.1.4

verification/curator-service/ui/src/components/SearchBar.tsx
Fixes #1150 
Only present if there is a current search query
=> Add a button to remove the current search query

verification/curator-service/ui/src/components/App.test.tsx, verification/curator-service/ui/src/components/App.tsx
=> Add data dictionary button to drawer

ingestion/functions/template.yaml
=> disable lambda retries

ingestion/functions/parsing/thai/sample_data.json, ingestion/functions/parsing/thai/thai.py, ingestion/functions/parsing/thai/thai_test.py
=> fix Thai geolocation queries by ignoring unknown english provinces

data-serving/data-service/api/openapi.yaml, data-serving/data-service/schemas/cases.indexes.json, data-serving/data-service/schemas/cases.schema.json, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/model/location.ts, data-serving/data-service/test/model/data/location.full.json, verification/curator-service/ui/src/components/Case.tsx, verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx
=> store geocode query alongside location

data-serving/scripts/convert-data/convert_data.py, data-serving/scripts/convert-data/converters.py, data-serving/scripts/data-pipeline/convert_and_import_latest_data.sh
For #1186
This gets us closer to being able to import docs AND have curators fix them but we're not there yet as since we made source creation mandatory before case creation can be done this will need to be added to the script (otherwise when editing a case we get errors like `ValidationError: case.caseReference.sourceId: Path `sourceId` is required., case.caseReference: Validation failed: sourceId: Path `sourceId` is required`
Still this is much better.
=> Various fixes to import scripts

verification/curator-service/api/src/controllers/sources.ts, verification/curator-service/api/src/schemas/sources.indexes.json, verification/curator-service/api/test/sources.test.ts
=> sort sources by name asc

verification/curator-service/ui/src/components/LandingPage.tsx
=> Change login link to a button

data-serving/data-service/api/openapi.yaml, data-serving/data-service/src/geocoding/suggest.ts, data-serving/data-service/test/geocoding/suggest.test.ts, verification/curator-service/api/openapi/openapi.yaml
Related to #1231
Tested locally:
http://localhost:3002/api/geocode/suggest?q=Adams,%20Ohio,%20United%20State&limitToResolution=Admin2,Admin1,Country
```
[{"geometry":{"longitude":-82.7114488167578,"latitude":40.4174201146},"country":"United States","place":"","name":"Ohio, United States","geoResolution":"Admin1","administrativeAreaLevel1":"Ohio","administrativeAreaLevel2":"Morrow","administrativeAreaLevel3":"Morrow"},{"geometry":{"longitude":-97.9222112121185,"latitude":39.3812661305678},"country":"United States","place":"","name":"United States","geoResolution":"Country","administrativeAreaLevel1":"Kansas","administrativeAreaLevel2":"Cloud","administrativeAreaLevel3":"Cloud"},{"geometry":{"longitude":29.7,"latitude":9},"country":"South Sudan","place":"","name":"Unity, South …
```
=> Support restrictToResolution in /api/geocode/suggest endpoint

data-serving/data-service/api/openapi.yaml, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/test/controllers/case.test.ts, data-serving/data-service/test/model/data/case.mustgeocode.json, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts
So far we were only looking at `case.location`, now we also look at `case.travelHistory.travel.location`.
Fixes #1231
=> Geocode every location entries in new case

verification/curator-service/ui/src/components/App.tsx
=> Add a catch all redirect to /

verification/curator-service/ui/src/components/App.tsx
=> Change UX of drawer links

aws/cluster.yaml, aws/curator.yaml, aws/data.yaml
Changelogs: https://github.com/globaldothealth/list/compare/0.1.6...0.2.0
Fixes #1238
=> bump prod to 0.2.0

verification/curator-service/ui/src/components/LinelistTable.tsx
Otherwise admin 3 is fine but all others are split on new lines
=> apply same visual treatment to all admins

aws/curator.yaml, aws/data.yaml, loadtest/README.md
=> even out cpu limits across curator and data services

verification/curator-service/ui/src/components/App.tsx
=> add link to github in profile menu

README.md, data-serving/scripts/convert-data/README.md, data-serving/scripts/convert-data/convert_data.py, data-serving/scripts/convert-data/converters.py, data-serving/scripts/data-pipeline/README.md, data-serving/scripts/data-pipeline/convert_and_import_latest_data.sh
=> Fix scripts and add documentation

data-serving/data-service/src/index.ts, data-serving/data-service/src/util/validate-env.ts
as per https://docs.mapbox.com/api/#rate-limits
=> rate limit to minute instead of second

verification/curator-service/ui/src/components/ViewCase.tsx
=> Fix UX of additional sources in detailed case view

aws/curator.yaml, aws/data.yaml
https://github.com/globaldothealth/list/compare/1.0.0...0.2.2
=> bump prod to 1.0.0

ingestion/functions/template.yaml
```
2020-09-30T18:10:40.015-04:00 | Retrieving raw data from s3://[...]/content.csv
2020-09-30T18:10:53.456-04:00 | [Errno 28] No space left on device
```
=> Increase memory size for Argentina and Peru parsers

ingestion/functions/parsing/saopaolo/input_event.json, ingestion/functions/parsing/saopaolo/sample_data.csv, ingestion/functions/parsing/saopaolo/saopaolo.py, ingestion/functions/parsing/saopaolo/saopaolo_test.py, ingestion/functions/retrieval/valid_scheduled_event.json, ingestion/functions/template.yaml
Here's a first take for the Sao Paolo parser! Unfortunately, this is not case-level data so it is not possible to dedupe.
=> Sao Paolo Brazil Parser

dev/README.md
Re: #1265 
Chris: you mentioned a procedure of directly contacting you/Spencer/Gaurav in the issue. Do you want me to include your email addresses in this document, or would you prefer another mechanism (e.g. an issue template)?
=> Update values/procedure around .env secrets

ingestion/functions/template.yaml
=> Increase memory allocation for Colombia parser.

ingestion/functions/parsing/brazil_amapa/amapa.py, ingestion/functions/parsing/brazil_amapa/sample_data.csv
Changes to date function to deal with empty fields and minor changes for readability and/or consistency with other parsers
=> Minor changes to Amapa parser

ingestion/functions/parsing/brazil_amapa/amapa.py, ingestion/functions/parsing/brazil_amapa/amapa_test.py, ingestion/functions/parsing/brazil_amapa/broken_date.csv, ingestion/functions/parsing/brazil_amapa/sample_data.csv
This is ready to go; the only thing that's blocked is running the e2e test locally, which I'll update.
=> Amapa date tolerance

ingestion/functions/parsing/japan/japan.py
Hopefully solves issue with validation failing
=> Deal with non-unique additional sources entries

ingestion/functions/parsing/brazil_amapa/amapa.py, ingestion/functions/parsing/brazil_amapa/amapa_test.py, ingestion/functions/parsing/brazil_amapa/broken_date.csv, ingestion/functions/parsing/brazil_amapa/input_event.json, ingestion/functions/parsing/brazil_amapa/sample_data.csv
The format of the data changed, I have edited the parser to deal with this.
=> Changes to parser to reflect data format changes

ingestion/functions/parsing/peru/peru.py
Added to if statement that filters cases: now checks if Date of Confirmation AND UUID are populated before parsing case
=> Added line to check if Date of Confirmation is populated before parsing case

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/App.test.tsx, verification/curator-service/ui/src/components/App.tsx
**What:**
Global.Health logo is now clickable and it navigates to root path /
**Why:**
User experience reasons
Checklist:
=> Logo navigates to home screen

ingestion/functions/parsing/taiwan/taiwan.py, ingestion/functions/parsing/taiwan/taiwan_test.py
Changed parser so travel info is parsed correctly and not just in notes
=> Take into account travel info

verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/LandingPage.test.tsx, verification/curator-service/ui/src/components/LandingPage.tsx
This is a test. We want to check if cookie consent banner is causing the problem with requests on the dev environment.
=> Cookie consent temp removal

data-serving/data-service/package-lock.json, data-serving/data-service/package.json, data-serving/data-service/src/index.ts, verification/curator-service/api/package-lock.json, verification/curator-service/api/package.json, verification/curator-service/api/src/index.ts, verification/curator-service/api/test/auth.test.ts, verification/curator-service/api/test/cases.test.ts, verification/curator-service/api/test/geocode.test.ts, verification/curator-service/api/test/index.test.ts, verification/curator-service/api/test/sources.test.ts, verification/curator-service/api/test/uploads.test.ts, verification/curator-service/api/test/users.test.ts, verification/curator-service/ui/src/components/SearchBar.tsx, verification/curator-service/ui/src/components/SourceTable.tsx
**What**
This is a fix regarding the bug that occurred after the release:
It seems to be a problem with 3rd party library: 'express-openapi-validator'. Here's the source:
https://github.com/cdimascio/express-openapi-validator/issues/447
There is a strong possibility that's similar to out case.
**Checklist:**
=> Update express-openapi-validator package

ingestion/functions/parsing/brazil_distrito_federal/distrito_federal.py
Made the comorbidities simpler and more like recent parsers.
=> Edits to comorbidities section

aws/curator.yaml, aws/data.yaml
=> Bump dev to 1.2.6

ingestion/functions/parsing/germany/germany.py, ingestion/functions/parsing/germany/germany_test.py, ingestion/functions/parsing/germany/input_event.json, ingestion/functions/parsing/germany/sample_data.csv
Expanded the parser as @Mougk noticed date of symptoms entry was included. Also changed it it to a csv.dictReader as this is more robust to changes in data format.
=> Expand Germany parser to include onset of symptoms and convert to dictReader

data-serving/data-service/api/openapi.yaml, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/index.ts, data-serving/data-service/test/controllers/case.test.ts
This would close #1385
This is the second backend part of the bigger task: #1013. 
Checklist:
=> WIP: #1385 Add endpoint for fetching list of excluded case IDs

ingestion/functions/parsing/brazil_acre/acre.py, ingestion/functions/parsing/brazil_paraiba/paraiba.py
As discussed I have altered the smell alteration symptom ontology for all relevant parsers.
=> Changes to symptom ontology for smell alterations

verification/curator-service/ui/src/components/App.tsx
=> Hide drawer by default

ingestion/functions/parsing/brazil_acre/acre.py, ingestion/functions/parsing/brazil_para/para.py, ingestion/functions/parsing/brazil_paraiba/paraiba.py
=> Remove typo in notes

ingestion/functions/parsing/brazil_distrito_federal/dictionaries.json, ingestion/functions/parsing/brazil_distrito_federal/distrito_federal.py, ingestion/functions/parsing/brazil_distrito_federal/distrito_federal_test.py, ingestion/functions/parsing/brazil_distrito_federal/input_event.json
Changed parser to deal with most locations without geocoding as this was returning erroneous locations. 
Closes #1407
=> Changes to location parsing

verification/curator-service/ui/src/components/common-form-fields/FieldTitle.tsx
* syling tootltip in `verification/curator-service/ui/src/components/common-form-fields/FieldTitle.tsx` file
=> Task 1214 design tooltip

verification/curator-service/api/openapi/openapi.yaml, verification/curator-service/api/src/controllers/sources.ts, verification/curator-service/api/test/sources.test.ts, verification/curator-service/ui/src/components/SourceTable.test.tsx, verification/curator-service/ui/src/components/SourceTable.tsx
~~~Draft for the moment, as incomplete and not working.~~~
=> Distinguish email notification failures from backend errors

verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/LandingPage.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
Changes
* Fixed the issue with url search parameters not being applied after successfully going through authentication
=> Task 1462 url parameters fix

ingestion/functions/parsing/hongkong/hongkong.py
Deal with age entries such as '14 days'
=> Deal with age in days

verification/curator-service/ui/src/components/App.test.tsx, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
Changes:
* Navigation drawer on the left is hidden by default for non curator users
* Linelist text changed to COVID-19 Linelist
=> Task 1441 hide drawer

.github/workflows/curator-ui-node.yml, .github/workflows/integration-tests.yml, data-serving/data-service/api/openapi.yaml, data-serving/data-service/package-lock.json, data-serving/data-service/schemas/cases.schema.json, data-serving/data-service/src/model/case.ts, data-serving/data-service/src/model/variant.ts, data-serving/data-service/test/model/variant.test.ts, data-serving/scripts/setup-db/package-lock.json, verification/curator-service/ui/Dockerfile, verification/curator-service/ui/README.md, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/BulkCaseForm.tsx, verification/curator-service/ui/src/components/Case.tsx, verification/curator-service/ui/src/components/CaseForm.test.tsx, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/ViewCase.tsx, verification/curator-service/ui/src/components/assets/variants.json, verification/curator-service/ui/src/components/new-case-form-fields/CaseFormValues.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Variant.tsx
Hi folks,
I'd appreciate some help with the Cypress test here. I'm getting the failure below, because the input element used in the test is hidden. What I'm trying to do is to click on the TOC entry for Variants of Concern, _then_ interact with the input. Looking at the screenshot on failure, the TOC navigation isn't happening. Anyone got an idea how to work around this?
```
1) New case form
Can add row to linelist with variant of concern:
CypressError: Timed out retrying: `cy.type()` failed because this element is not visible:
`<input name="variantName" aria-hidden="true" tabindex="-1" class="MuiSelect-nativeInput" value="">`
This element `<input.MuiSelect-nativeInput>` is not visible because it has CSS property: `position: fixed` and it's being covered by another element:
`<div …
```
=> 1483 variant field

verification/curator-service/api/src/controllers/auth.ts, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/landing-page/LandingPage.tsx
Changes:
* Added new endpoint in Curator API for signing up/in
* Added try catch when trying to sign out
=> Sign in/out fix

verification/curator-service/ui/src/components/landing-page/LandingPage.test.tsx, verification/curator-service/ui/src/components/landing-page/LandingPage.tsx, verification/curator-service/ui/src/components/landing-page/SignInForm.tsx, verification/curator-service/ui/src/hooks/useCookieBanner.tsx
Changes:
* Added links to TOS and PP on Landing Page
* Change "Learn more..." button colors on CookieBanner so that it is visible
* Fixed issue with SignUp interstitial being cropped at the top on smaller screens
Screenshots:
=> Task 1508 bug fixes

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/src/components/App.test.tsx, verification/curator-service/ui/src/components/App.tsx
https://www.dropbox.com/s/biy4b7iydnodr6y/Screen%20Shot%202021-02-03%20at%204.24.33%20PM.png?dl=0
https://www.dropbox.com/s/i3uv2j3485w0xrs/Screen%20Shot%202021-02-03%20at%204.24.05%20PM.png?dl=0
=> 1508 beta bug bash fixes

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/src/components/App.test.tsx, verification/curator-service/ui/src/components/App.tsx
Reverts globaldothealth/list#1518
=> Revert "1508 beta bug bash fixes"

data-serving/data-service/api/openapi.yaml, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/util/search.ts, data-serving/data-service/test/controllers/case.test.ts, verification/curator-service/ui/src/components/SearchBar.tsx, verification/curator-service/ui/src/components/SearchGuideDialog.tsx
Reverts globaldothealth/list#1513
=> Revert "1502 voc filter"

verification/curator-service/ui/src/components/landing-page/LandingPage.test.tsx, verification/curator-service/ui/src/components/landing-page/LandingPage.tsx, verification/curator-service/ui/src/components/landing-page/SignInForm.tsx, verification/curator-service/ui/src/hooks/useCookieBanner.tsx
Reverts globaldothealth/list#1519
=> Revert "Task 1508 bug fixes"

verification/curator-service/ui/src/components/App.tsx
=> 1508 removed menu item from profile menu

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/src/components/App.test.tsx, verification/curator-service/ui/src/components/App.tsx
https://www.dropbox.com/s/biy4b7iydnodr6y/Screen%20Shot%202021-02-03%20at%204.24.33%20PM.png?dl=0
https://www.dropbox.com/s/i3uv2j3485w0xrs/Screen%20Shot%202021-02-03%20at%204.24.05%20PM.png?dl=0
=> 1508 beta bug bash fixes -2nd attempt

verification/curator-service/api/src/controllers/cases.ts
**Changes**
* Changed filename of downloaded dataset to match format `gh_YYYY-MM-DD.tar.gz`
=> 1509 - Add date and time to downloaded CSV

verification/curator-service/ui/src/components/App.test.tsx, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/landing-page/LandingPage.test.tsx, verification/curator-service/ui/src/components/landing-page/LandingPage.tsx
**Changes**
* Added data acknowledgments links on LandingPage in the navigation drawer and in profile menu dropdown
* Updated tests
=> 1508 data acknowledgments links

verification/curator-service/api/src/controllers/auth.ts, verification/curator-service/api/src/index.ts, verification/curator-service/api/test/auth.test.ts
**Changes**
* Configured AWS SES in Curator API
* Changed AWS Lambda responsible for sending verification codes to send custom email content
* Configured sending welcome emails only when the user registers for the first time
* Updated tests in Curator API
⚠️ In order for the new changes to work `EMAIL_USER_ADDRESS` inside `list/dev/.env` should be changed to `ghdsi.info@gmail.com` ⚠️ 
Verification code email:
Welcome email for new users:
=> 1527 Create custom welcome emails for new users

verification/curator-service/api/src/controllers/auth.ts, verification/curator-service/api/src/model/user.ts, verification/curator-service/ui/src/components/landing-page/LandingPage.test.tsx, verification/curator-service/ui/src/components/landing-page/LandingPage.tsx, verification/curator-service/ui/src/components/landing-page/SignInForm.test.tsx, verification/curator-service/ui/src/components/landing-page/SignInForm.tsx
**Changes**
* Added not required checkbox for newsletter on Landing Page
* The newsletter acceptance is being tracked and stored in mongodb for each user 
=> 1546 Add newsletter checkbox as separate and non required element on sign up interstitial

ingestion/functions/retrieval/retrieval.py
The Czechia parser was receiving a header with a spurious extra 'd'
in the second line which broke the parser.
This was happening due to incorrect calculation of the header
offset. Previously the header offset was calculated _after_
decoding, which is fine for ASCII or UTF-8, but in other encodings
there may be a BOM or in the Czechia case, additional characters
like \ufeff which made the offset off by one.
This commit correctly calculates the header offset at the byte
level before decoding.
=> Use correct header offset #1560

ingestion/functions/parsing/mexico/mexico.py
Validation error as Mexico had cases with age > 120
=> Deal with age >120

ingestion/functions/parsing/USA/USA.py, ingestion/functions/parsing/USA/sample_data.csv
Name of a column changed in source data
=> Column name changed in USA data

ingestion/functions/retrieval/retrieval.py
Reduce chunk size as still getting timeouts
=> reduce chunk size

ingestion/functions/retrieval/retrieval.py
=> Reduce chunk size to 2 MiB

verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
**Changes**
* Added breadcrumbs showing currently active filters above Linelist table
=> 1540 filter breadcrumbs

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/src/components/App.test.tsx, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/GHListLogo.tsx, verification/curator-service/ui/src/components/landing-page/LandingPage.test.tsx, verification/curator-service/ui/src/components/landing-page/LandingPage.tsx, verification/curator-service/ui/src/components/landing-page/SignInForm.tsx
Updated all the urls with production ones in Curator UI
=> Updated urls with production ones

verification/curator-service/ui/src/components/SearchGuideDialog.test.tsx, verification/curator-service/ui/src/components/SearchGuideDialog.tsx
**Changes**
* Updated search guide modal content
=> 1540 - Update search guide content

ingestion/functions/retrieval/retrieval.py
Reverts globaldothealth/list#1578
=> Revert "Chunk waiting"

ingestion/functions/retrieval/retrieval.py, ingestion/functions/retrieval/retrieval_test.py
Reverts globaldothealth/list#1577
=> Revert "last ditch attempt to save chunking"

ingestion/functions/parsing/scotland/scotland.py
Looks like they added a new age category which wasn't covered by the convert_age function
=> Deal with new age category Scotland parser

verification/curator-service/api/src/controllers/cases.ts, verification/curator-service/api/src/model/user.ts
**Changes**
* Added tracking for downloads in mongodb users collection
Each download is being saved in mongodb in `users` collection in `downloads` dictionary
=> 1593 - Added tracking for downloads in mongodb users collection

ingestion/functions/parsing/czechia/czechia.py
Quick fix to deal with some cases failing during backfill
=> Deal with missing date of confirmation Czechia parser

verification/curator-service/api/src/clients/aws-lambda-client.ts, verification/curator-service/api/src/controllers/auth.ts, verification/curator-service/api/src/index.ts, verification/curator-service/api/test/auth.test.ts
**Changes**
* Moved sending welcome emails from Curator API to AWS Lambda
* Created new IAM user and policy for lambda function
* Created new Lambda function `SendWelcomeEmail`
=> 1527 welcome emails fix

verification/curator-service/api/openapi/openapi.yaml
Proposed fix for #1622, not sure if complete though so @fojackson8 / @AnyaLindstromBattle any other information missing?
=> Add undocumented fields to the case schema

data-serving/data-service/api/openapi.yaml, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/controllers/preprocessor.ts, verification/curator-service/api/openapi/openapi.yaml, verification/curator-service/api/test/cases.test.ts, verification/curator-service/api/test/clients/email-client.test.ts, verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
#1607 
⚠️ Before pushing to production this solution should be tested on larger data source to see if the performance is good enough
**Changes**
* Added `count_limit` param to `GET /api/cases` query 
* Document count is being limited do `count_limit` param making the queries faster and Linelist pagination displays 'of many' as total results count
* Updated `openapi.yaml`
=> 1607 scale pagination

aws/curator.yaml, aws/data.yaml
Adds source filtering for VoC ingestion
=> Bump data and curator services to 1.5.0

aws/curator.yaml, aws/data.yaml
this is to test the VoC ingestion.
=> bump to v1.5.1 in dev

data-serving/data-service/src/controllers/case.ts, verification/curator-service/ui/src/components/SearchGuideDialog.tsx
added new date filters to Search Guide
=> fixed search guide

ingestion/functions/common/common_lib.py, ingestion/functions/parsing/canada/canada_test.py, ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py, ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py, ingestion/functions/retrieval/retrieval.py, ingestion/functions/retrieval/retrieval_test.py
NamedTemporaryFile has some issues on Windows:
https://bugs.python.org/issue14243
=> Use mkstemp() instead of NamedTemporaryFile

ingestion/functions/aws.py
Added CRUD functions for EventBridge rules and targets
=> added EventBridge commands to ingestion/functions/aws.py

dev/README.md, dev/test_all.sh, verification/curator-service/api/package-lock.json, verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json
Bumped mongodb-client-encryption version in curator service UI (fixing an error on `npm install`)
Added dependency checks installs to test script
Added stack run check and startup to test script
Updated README
=> Run tests locally

ingestion/functions/aws.py
Added --timeout for maximum job runtime.
Feel free to add any other restrictions, such as on ulimits﻿
=> Add --timeout to aws.py, #1751

data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/util/search.ts, data-serving/data-service/test/util/search.test.ts
https://github.com/globaldothealth/list/issues/1669
=> outcome is now working

verification/curator-service/ui/src/components/ViewCase.tsx
https://github.com/globaldothealth/list/issues/1675
=> fixed overlapping

verification/curator-service/ui/src/components/GHListLogo.tsx
https://github.com/globaldothealth/list/issues/1672
=> fixed logo links

data-serving/data-service/schemas/cases.indexes.json, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/util/search.ts
https://github.com/globaldothealth/list/issues/1679
=> fixed filter dates

aws/README.md, aws/curator.yaml, data-serving/data-service/Dockerfile, data-serving/data-service/package.json, dev/docker-compose.dev.yml, dev/docker-compose.yml, dev/run_stack.sh, verification/curator-service/api/README.md, verification/curator-service/api/openapi/openapi.yaml, verification/curator-service/api/package-lock.json, verification/curator-service/api/package.json, verification/curator-service/api/src/controllers/cases.ts, verification/curator-service/api/src/index.ts, verification/curator-service/api/src/workers/downloadAsync.js
There are still open questions on this:
- I can't see how I'd add automated tests (I've been testing by making API calls to the curator service, and checking my inbox) and I'd welcome guidance from reviewers.
- SES has an attachment limit of 10MB, how do we want to deal with that?
- Is the approach to error reporting sufficient?
- How will the extra configuration parameters (SES region and sender address) get populated in k8s?
=> 1608 batch download

data-serving/data-service/api/openapi.yaml, data-serving/data-service/schemas/cases.indexes.json, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/util/case.ts, data-serving/data-service/test/controllers/case.test.ts, verification/curator-service/api/openapi/openapi.yaml, verification/curator-service/api/test/clients/email-client.test.ts, verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/src/components/GHListLogo.tsx, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/constants/types.ts
**Changes**
* Added Select input that let's user to choose which field to sort by
* Added sorting order select input
* Added `sort_by` and `order` parameters to GET `/api/cases/` endpoint
* Updated and added tests
=> 1297 sorting linelist view

data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/util/search.ts, data-serving/data-service/test/util/search.test.ts, verification/curator-service/ui/src/components/GHListLogo.tsx
[#1678](https://github.com/globaldothealth/list/issues/1678)
**changes**
* Added `caseid` filter keyword parsing from `string` to mongodb `ObjectId`
* Updated tests to reflect changes
=> #1678 Filtering by case id

data-serving/data-service/src/controllers/case.ts, data-serving/data-service/test/controllers/case.test.ts, verification/curator-service/ui/src/components/Case.tsx, verification/curator-service/ui/src/components/EditCase.test.tsx, verification/curator-service/ui/src/components/EditCase.tsx, verification/curator-service/ui/src/components/GHListLogo.tsx, verification/curator-service/ui/src/components/ViewCase.test.tsx, verification/curator-service/ui/src/components/ViewCase.tsx
[#1688](https://github.com/globaldothealth/list/issues/1688)
**Changes**
* Changed GET `/api/cases/:id` endpoint to use `aggregate` instead of `findOne` to fetch case
* Updated tests
=> #1688 - "Excluded" record's view case showing the Verification status as "Unknown"

data-serving/data-service/schemas/cases.indexes.json, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/util/search.ts, data-serving/data-service/test/util/search.test.ts, data-serving/samples/cases.json, verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/cypress/support/commands.ts
https://github.com/globaldothealth/list/issues/1685
=> 1685 unable to filter by variant

verification/curator-service/ui/src/components/App.test.tsx, verification/curator-service/ui/src/components/App.tsx, verification/curator-service/ui/src/components/landing-page/LandingPage.test.tsx, verification/curator-service/ui/src/components/landing-page/LandingPage.tsx
https://github.com/globaldothealth/list/issues/1658
=> fixed links

data-serving/data-service/src/controllers/case.ts
Will reduce to `debug` once we figure out what the current issue is
=> Added logging to data service method to list all cases

data-serving/data-service/src/controllers/case.ts
Sort after limiting to reduce mongo load﻿
=> Try fixing line list loading issue #1765

verification/curator-service/ui/src/components/LinelistTable.tsx, verification/curator-service/ui/src/components/VerificationStatusHeader.tsx
https://github.com/globaldothealth/list/issues/1793
=> verification status opens modal

.github/workflows/update-dev-data-db-schema.yaml, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/index.ts
**Changes**
* Modified aggregation pipeline when fetching cases to allow for sorting
* Added missing indexes to DEV database
⚠️ 
This PR was tested on DEV database (17.4M cases) and the sorting was working fine. Some queries were longer than others but the results were always presented. It should be tested on production database as well to see if the amount of data there won't impact the performance to a significant extent.
=> #1005 - Sorting in linelist table fix

verification/curator-service/ui/src/components/LinelistTable.tsx
https://github.com/globaldothealth/list/issues/1808
The field is now fully visible:
=> fixed field UI

.github/workflows/geocoding-service-package.yml, aws/location.yaml
I don't know that there's any more I need to do to deploy the service (other than tag a release on main so that the docker images get built and published to the container registry), so please do tell me if I missed anything off.
=> 1717 deploy geocoding in k8s

geocoding/location-service/Dockerfile
Sorry to introduce this failure: there is a poetry command on my path which I guess is why it works locally for me.
=> Do not rely on poetry being in the user PATH

verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
#1783 
**Changes**
* After clicking on `Filters` breadcrumb `FiltersModal` is opened
* After clicking on any other filter breadcrumbs `FiltersModal` is opened and corresponding input is focused
* Updated `LinelistTable` tests
=> 1783 filter button not working

PROCESS.md
Hi folks, please review to make sure I've captured the meeting discussion fairly. I'll share with the rest of the team when you're happy.
=> Document engineering discussion re issue tracking

verification/curator-service/ui/src/components/FiltersModal.tsx
Filter - No records displayed when filter by source url #1806
https://github.com/globaldothealth/list/issues/1806
=> trimmed strings

verification/curator-service/ui/src/components/FiltersModal.tsx
#1777 
**Changes**
* Increased bottom padding in FiltersModal
=> 1777 - Buttons in filters modal cut off 

ingestion/functions/common/parsing_lib.py
Fixes #1849. There's already a test that the error gets reported, so I know that's still working :)
=> Run through all case batches before reporting validation error

aws/README.md
Yes this is a trivial PR but if I make you review it then I know we've all read it :)
=> Document the package visibility requirement.

verification/curator-service/ui/src/components/LinelistTable.tsx
#1871 
**Changes**
* Hide sorting by confirmed date until fix is found to the timeout error
=> 1871 - Hide sorting by date

aws/curator.yaml, aws/data.yaml, aws/location.yaml
https://kubernetes.io/docs/concepts/containers/images/#updating-images
=> using latest tag on dev containers to set imagePullPolicy to latest

ingestion/functions/aws.py, ingestion/functions/common/common_lib.py, ingestion/functions/common/common_lib_test.py, ingestion/functions/retrieval/retrieval.py, ingestion/functions/retrieval/retrieval_test.py
* Moved get_parser_module() to common_lib
* aws.py now uses common_lib.get_parser_module()
* Updated job_definition() call in register() to new parameter list
=> ingestion: Fix aws.py job registration

verification/curator-service/ui/src/components/App.tsx
=> fixed dictionary link

geocoding/location-service/src/app/main.py
Just pasting interwebs code at this point
=> Try some voodoo

verification/curator-service/api/src/clients/aws-batch-client.ts, verification/curator-service/api/test/clients/aws-batch-client.test.ts
…..the SDK says it exists but the error messages say it does not
=> Checking jobID instead of metadata

verification/curator-service/ui/src/components/SourceRetrievalButton.tsx
related: https://github.com/globaldothealth/list/issues/1909
=> Replaced lambda details with batch job name

.github/workflows/ingestion-functions-deploy.yml
- Fix path in ingestion function deployment action
- ingestion: Tag stable docker image with :stable
=> fix ingestion deployment

verification/curator-service/api/src/workers/downloadAsync.js
This might need a corresponding change in AWS SES
=> download: Change from address to info@global.health #1933

verification/curator-service/api/package-lock.json, verification/curator-service/api/package.json, verification/curator-service/api/src/model/automation.ts, verification/curator-service/api/src/model/source.ts
Also means shuffling some mongoose types
=> Update some vulnerable packages #1943

verification/curator-service/api/src/clients/email-client.ts, verification/curator-service/api/src/controllers/auth.ts
[#1876](https://github.com/globaldothealth/list/issues/1876)
**Changes**
- Updated content in emails that are being sent during password reset process
=> Updated emails content

data-serving/scripts/prune-uploads/prune_uploads.py, data-serving/scripts/prune-uploads/test_prune_uploads.py, ingestion/functions/common/common_lib.py, ingestion/functions/common/parsing_lib.py, ingestion/functions/common/parsing_lib_test.py, verification/curator-service/api/src/model/upload-summary.ts, verification/curator-service/api/src/schemas/sources.schema.json, verification/curator-service/api/test/model/data/source.full.json, verification/curator-service/api/test/model/data/upload-summary.full.json, verification/curator-service/api/test/uploads.test.ts, verification/curator-service/ui/cypress/integration/components/UploadsTableTest.spec.ts, verification/curator-service/ui/src/components/AutomatedBackfill.tsx, verification/curator-service/ui/src/components/UploadsTable.test.tsx, verification/curator-service/ui/src/components/UploadsTable.tsx
- curator/ui: Add numError field to uploads #2018
- ingestion: Report number of validation error cases #2018
=> 2018 validation error threshold

.github/workflows/curator-service-package.yml, verification/curator-service/auth.md, verification/curator-service/ui/src/components/LinelistTable.tsx
- docs: Add authentication information using curl
- curator/ui: Always show full dataset download
=> revert download button

.github/workflows/prune-uploads-dev.yml, .github/workflows/prune-uploads-prod.yml, README.md, data-serving/scripts/convert-data/requirements.txt
- move-notes: Add dnspython dependency for mongodb+srv URLs
- ci: Add prune uploads scheduled action #2002
=> ci prune uploads

verification/curator-service/ui/cypress/integration/components/LandingPage.spec.ts, verification/curator-service/ui/src/components/landing-page/LandingPage.test.tsx, verification/curator-service/ui/src/components/landing-page/SignUpForm.tsx
https://github.com/globaldothealth/list/issues/2049
=> 2049-fixed minor issues on sign up page

ingestion/functions/retrieval/retrieval.py
XLSX file downloads currently work, but fail on encoding detection
because they are not text files, but zip files. Skip normalization
to UTF-8 as we have very few XLSX sources, and let the parsers
specify custom encodings if required.
=> retrieval: Skip encoding detection for XLSX, fixes #1433

data-serving/scripts/export-data/functions/03-parse/app.py, data-serving/scripts/export-data/template.yaml, ingestion/functions/aws.py
- ingestion/aws: Add variable for updated return type
- export(parse): Save temporary files to /mnt/efs
- export(parse): Add exponential backoff for S3 i/o
=> fix data export

ingestion/functions/parsing/brazil_srag/srag.py
=> Changed gender parsing to other

verification/curator-service/ui/cypress/integration/components/ProfileTest.spec.ts, verification/curator-service/ui/src/components/landing-page/SignUpForm.tsx
https://github.com/globaldothealth/list/issues/2043
=> fixe email case sensitive

verification/curator-service/api/src/controllers/sources.ts, verification/curator-service/api/src/model/case.ts, verification/curator-service/api/test/sources.test.ts
It makes me sad that we now have a sources schema in the data service and a cases schema in the curator service, but there it is.
=> Forbid deletion of sources that are referred to by cases #2055

verification/curator-service/api/src/controllers/auth.ts
=> Fixed non Google user password reset bug

aws/curator.yaml
=> Set EMAIL_USER_ADDRESS in curator deploy directly

ingestion/functions/parsing/new_zealand/new_zealand.py, ingestion/functions/parsing/new_zealand/new_zealand_test.py, ingestion/functions/parsing/new_zealand/sample_data.csv
Don't set demographics when age = NA and gender = Unknown
=> parsing(new_zealand): Fix error when age = NA

.dockerignore, verification/curator-service/ui/.env.staging, verification/curator-service/ui/.gitignore, verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/App/App.tsx, verification/curator-service/ui/src/components/util/validate-env.ts
Connected to issue: https://github.com/globaldothealth/list/issues/2011
**
**
There will be 1 new ENV variable: `REACT_ENV_TYPE`
Its values will be:
- local
- staging
- prod
**In Staging server:**
add `.env` file in `staging`
with this content:
`REACT_ENV_TYPE="staging"`
**In the Production server:**
add `.env` file in `/verification/curator-service/ui`
with this content:
`REACT_ENV_TYPE="prod"`
**In Local machine:**
add `.env` file in `/verification/curator-service/ui`
with this content:
`REACT_ENV_TYPE="local"`
In case you need to test it locally, just change: 
`REACT_ENV_TYPE="local"`
to
`REACT_APP_LINK="staging"`
=> 2011 map link redirect to dev site

.github/workflows/export-lambda-functions.yaml, data-serving/scripts/export-data/template.yaml
- export: Run twice daily after prune-uploads
- ci: Add CI for export AWS Lambda functions
=> ci export functions

data-serving/data-service/src/model/vaccine.ts, data-serving/scripts/setup-db/package-lock.json, verification/curator-service/ui/src/components/Case.tsx, verification/curator-service/ui/src/components/CaseForm.tsx, verification/curator-service/ui/src/components/new-case-form-fields/CaseFormValues.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx, verification/curator-service/ui/src/components/new-case-form-fields/Vaccines.tsx
This is the frontend change for #2120, the backend support for the data is already merged in #2134.
#2120 Currently just the new case form not the edit case form; also we have explicitly chosen not to show vaccine data in the line list table.
=> 2120 vaccine form

data-serving/scripts/setup-db/package.json, dev/setup_db.sh, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/ViewCase.tsx
Just adding a few fields to the case view form.
=> 2120 vaccines on view

data-serving/data-service/package-lock.json, data-serving/data-service/package.json, verification/curator-service/api/package-lock.json, verification/curator-service/api/package.json
Merging #2144 and #2145 into a single PR/review. Related to #1943
=> Security rollup

verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
Sharing this PR with you but if it fixes the integration tests today I'm going to unilaterally merge it so I can get a release onto dev before the product meeting. @sergioloporto already made this fix to another test so I'm confident it is the correct change.
=> Tests failing because you cannot type in the country field any more

data-serving/data-service/tsconfig.json, verification/curator-service/api/src/controllers/cases.ts, verification/curator-service/api/src/model/user.ts, verification/curator-service/api/tsconfig.json
And adding logging on errors, and database entries for download formats and queries.
=> Switching findOneAndUpdate with findByIdAndUpdate

verification/curator-service/api/src/controllers/cases.ts, verification/curator-service/api/src/model/user.ts
* More temporary logging, trying to toggle behavior
* ._id -> .id, reverting test
=> 2162 count downloads (#2169)

data-serving/data-service/api/openapi.yaml, data-serving/data-service/tsconfig.json, verification/curator-service/api/openapi/openapi.yaml, verification/curator-service/api/tsconfig.json
Let me know if you need anything more on this @AnyaLindstromBattle @fojackson8
=> Add vaccine schema to openapi #2120

data-serving/scripts/export-data/country_export.sh, data-serving/scripts/export-data/transform.py
- export: Drop .value fields for some event categories
- export: Add support for TSV,JSON,JSONL exports
=> export tsv json

data-serving/scripts/export-data/data_dictionary.txt
First draft of data dictionary, have a look at the TODOs! Some of the events.*.value fields seem to not be needed, we should remove them from export after confirmation.
=> Add proper data dictionary #1610

verification/curator-service/api/README.md, verification/curator-service/api/src/controllers/auth.ts, verification/curator-service/api/src/index.ts, verification/curator-service/api/src/model/user.ts, verification/curator-service/api/test/auth.test.ts, verification/curator-service/auth.md, verification/curator-service/ui/src/api/models/User.ts, verification/curator-service/ui/src/components/Profile.test.tsx, verification/curator-service/ui/src/components/Profile.tsx, verification/curator-service/ui/src/components/User.tsx, verification/curator-service/ui/src/redux/auth/thunk.ts
Reviewers: please particularly make sure that I have got any security implications correct!
=> Api keys 2142

.github/workflows/export-deploy.yml, data-serving/scripts/export-data/Dockerfile_full_export, data-serving/scripts/export-data/README.md, data-serving/scripts/export-data/citation.txt, data-serving/scripts/export-data/common.sh, data-serving/scripts/export-data/full_export.sh, data-serving/scripts/export-data/setup_batch.sh, data-serving/scripts/export-data/setup_full_export.sh, verification/curator-service/api/src/controllers/cases.ts
- export: Add full export scripts #2191
- ci: Build full-exporter images
- curator/api: Use latestdata-csv as we support multiple formats
=> 2191 full export

data-serving/scripts/setup-db/migrations/20211105174857-source-countrycodes.js, verification/curator-service/api/package-lock.json, verification/curator-service/api/package.json, verification/curator-service/api/src/model/source.ts, verification/curator-service/ui/cypress/integration/components/SourceTableTest.spec.ts, verification/curator-service/ui/cypress/integration/components/UploadsTableTest.spec.ts, verification/curator-service/ui/cypress/support/commands.ts, verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/AutomatedSourceForm.tsx, verification/curator-service/ui/src/components/SourceTable.test.tsx, verification/curator-service/ui/src/components/SourceTable.tsx
- curator: Add iso-3166-1 to dependencies
- schemas: Add countryCodes to sources
- curator: Add countryCodes field
=> add country to sources

.github/workflows/prune-uploads-dev.yml, .github/workflows/prune-uploads-prod.yml, .github/workflows/prune-uploads-tests.yml, data-serving/scripts/prune-uploads/README.md, data-serving/scripts/prune-uploads/hooks/country_export.py, data-serving/scripts/prune-uploads/hooks/tests/test_country_export.py, data-serving/scripts/prune-uploads/prune_uploads.py, data-serving/scripts/prune-uploads/requirements.txt
Adds a hook to prune-uploads to trigger appropriate exporter job definitions.
=> Prune triggers country export

data-serving/scripts/export-data/README.md, data-serving/scripts/export-data/country_export.sh, data-serving/scripts/export-data/setup_country_export.sh
BUCKET specifies which S3 bucket to save the files to.
=> export: Require BUCKET for country export job definitions

verification/curator-service/api/src/controllers/auth.ts
The API keys are supposed to be prefixed by the user ID so that we can easily find the correct user to test the key against, but this was not being formatted correctly by the auth controller.
=> Fix bug in generating API keys that made them impossible to find on use

verification/curator-service/ui/.gitignore, verification/curator-service/ui/src/components/assets/variants.json, verification/curator-service/ui/src/components/landing-page/LandingPage.tsx, verification/curator-service/ui/variantsofconcern.csv
When we inevitably decide that we want to track the omicron variant, merge this.
=> Omicron dropdown

verification/curator-service/ui/src/components/FiltersModal.tsx, verification/curator-service/ui/src/redux/filters/thunk.ts
**Changes**
- Added breakpoints to `FiltersModal` so that it becomes smaller on screens with heights less than 800px
=> #2253 - Responsive Filters modal

verification/curator-service/ui/src/components/LinelistTable.tsx
**Changes**
- Age in `LinelistTable` is now rounded
=> #2283 - Rounded age in LinelistTable

data-serving/data-service/src/controllers/case.ts, verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts, verification/curator-service/ui/cypress/support/commands.ts, verification/curator-service/ui/src/components/FiltersModal.test.tsx, verification/curator-service/ui/src/components/FiltersModal.tsx
**Changes**
- Added the ability to filter cases that doesn't have `gender` provided
- Added test case for that
=> #2266 - Filtering by gender: Not Provided

.github/workflows/api-python-tests.yml, api/R/.gitignore, api/R/gdh.r, api/README.md, api/python/gdh.py, api/python/requirements.txt, api/python/test_gdh.py
Draft version, comments welcome! I haven't put up versioned dependencies as the libraries are fairly stable, and people might be stuck on older versions; also not sure what the standard is in R.﻿
=> Add scripts to access API

data-serving/scripts/aggregate/aggregate/Dockerfile, data-serving/scripts/aggregate/aggregate/app.py, data-serving/scripts/aggregate/aggregate/entrypoint.sh
Also providing output at script start
=> Removing reference to nonexistent poetry environment

data-serving/data-service/src/controllers/case.ts, verification/curator-service/ui/src/components/LinelistTable.tsx
also made the file name for filtered downloads equal to the filter
=> Adding citation and data dictionary download links to modal

data-serving/scripts/aggregate/aggregate/app.py
Also added more logging and an exit condition for a while loop.
=> Not exiting if country code not found

geocoding/location-service/src/app/admins_fetcher.py, geocoding/location-service/src/app/main.py
This is a possible fix for #1877
=> geocoding: Return None if tile ID not found in admins collection

data-serving/scripts/convert-data/convert_data.py, data-serving/scripts/convert-data/logger.py, data-serving/scripts/convert-data/move_notes.py, data-serving/scripts/export-data/Dockerfile, data-serving/scripts/export-data/logger.py, data-serving/scripts/export-data/transform.py, data-serving/scripts/prune-uploads/hooks/aggregate.py, data-serving/scripts/prune-uploads/hooks/country_export.py, data-serving/scripts/prune-uploads/logger.py, data-serving/scripts/prune-uploads/prune_uploads.py
Let me know if any of the `setup_logger` functions should change.
=> Replacing data script print statements with logging

verification/curator-service/api/src/controllers/cases.ts, verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts, verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts, verification/curator-service/ui/cypress/integration/components/ViewCase.spec.ts, verification/curator-service/ui/src/components/LinelistTable.test.tsx, verification/curator-service/ui/src/components/LinelistTable.tsx
Not sure if this is as detailed as we'd like, but it's a start.
=> Logging non-default line list filters those causing 500+ errors

.github/workflows/aggregate-deploy.yml, .github/workflows/api-python-tests.yml, .github/workflows/curator-api-node.yml, .github/workflows/curator-service-package.yml, .github/workflows/curator-ui-node.yml, .github/workflows/data-service-node.yml, .github/workflows/data-service-package.yml, .github/workflows/export-deploy.yml, .github/workflows/export-tests.yml, .github/workflows/geocoding-service-package.yml, .github/workflows/geocoding-service-python.yml, .github/workflows/ingestion-functions-deploy.yml, .github/workflows/ingestion-functions-python.yml, .github/workflows/integration-tests.yml, .github/workflows/monitoring-tests.yml, .github/workflows/prune-uploads-tests.yml, .github/workflows/suggest-python.yml, .github/workflows/update-dev-curator-db-schema.yml, .github/workflows/update-prod-curator-db-schema.yaml
GitHub actions throw "Error : .github#L1 Invalid type for `on`" when using `[]` so this PR removes the list and makes `workflow_dispatch` events stand alone.
=> Manually invoke GitHub actions

data-serving/data-service/package-lock.json, verification/curator-service/api/package-lock.json
Dependencies for the dependency god
=> Fix dependabot alerts

data-serving/scripts/aggregate/aggregate/app.py
This is a backend portion of this task: #1602 PR for frontend part is in `react` repository. 
**Changes**
- Added `admin1`, `admin2` and `admin3` to the regional data aggregation script
=> #1602 Multiple query levels for regional map filtering

data-serving/scripts/setup-db/manual-migration-helpers/batch_countries.js
This fixes a bug I found when running the migration in dev, that locations were ending up looking like `{country: "BE"}` without all the other fields like lat, long, query, resolution etc.
Because the script errored out when it detected the validation failures with the first batch, a maximum of 10k cases in dev are affected. I will just drop those, then run the fixed migration. I do not know why mongodb was willing to commit the changed versions despite the validation failures.
=> Correct the country coding script to update location documents, not replace them

data-serving/scripts/setup-db/manual-migration-helpers/batch_countries.js
Special-casing names that don't appear in the library I'm using, and extra exception handling.
=> Robustify country migration

data-serving/data-service/package-lock.json, data-serving/data-service/package.json, data-serving/data-service/src/controllers/case.ts, data-serving/data-service/src/index.ts, verification/curator-service/api/src/controllers/cases.ts
Introduce middleware that will log every request/response, and any errors, in the data-service. It filters out potential PII.
=> Add moar logging

data-serving/scripts/export-data/country_export.sh, data-serving/scripts/export-data/setup_country_export.sh, data-serving/scripts/prune-uploads/hooks/country_export.py, data-serving/scripts/prune-uploads/hooks/tests/test_country_export.py
- export: Use ISO country codes as export filenames
- prune/hooks: Update job definition names for ISO3166 transition
- export: Update country export setup for ISO3166 transition
=> country export isocode

verification/curator-service/api/package-lock.json, verification/curator-service/ui/package-lock.json
- build(deps): bump node-fetch in /verification/curator-service/ui
- build(deps): bump follow-redirects in /verification/curator-service/ui
- build(deps): bump node-fetch in /verification/curator-service/api
=> dependabot 20220204

.github/workflows/update-dev-curator-db-schema.yml, .github/workflows/update-prod-curator-db-schema.yaml, aws/README.md
Fix ref to 1.7 stable in workflow that updates prod schema
=> ci: Fix reference to old stable and update docs

.github/workflows/ingestion-cleanup-deploy.yml, ingestion/functions/Dockerfile-clean
Dockerfile, and GitHub action to push to ECR. Needed before we can use it in Batch.
BTW, what's the plan for deploying in Batch? Do I deploy from the console and replicate the setup in the terraform repo, or define in terraform then apply to the prod infrastructure?
#2217
=> Dockerfile for ADI source cleanup script

ingestion/functions/Dockerfile, ingestion/functions/Dockerfile-test, ingestion/functions/retrieval/retrieval.py
=> retrieval: Use unzip instead of zipfile to support newer formats

ingestion/functions/Dockerfile-clean
Ensure your cleanup scripts run correctly in Batch using this one weird trick!
=> Copy AWS library files into the correct place in the Docker filesystem

ingestion/monitoring/completeness.py
Also do not return null for countries in completeness.json
when download failed.
=> completeness: add exponential backoff for downloading files

ingestion/functions/parsing/hongkong/hongkong.py, ingestion/functions/parsing/hongkong/hongkong_test.py
- parsing(hong_kong): return None in age when ValueError
- parsing(hong_kong): set country code to HK
=> parsing(hong_kong): Fix ValueError and set country code to HK

ingestion/from_spreadsheet/requirements.txt
updated deps and ran script again, still works.
=> update vulnerable dependencies in spreadsheet ingestor

.github/workflows/ingestion-error-reporter-deploy.yml, ingestion/monitoring/Dockerfile, ingestion/monitoring/errorLogsToSlack.py
1. get the slack web hook URL from GH secrets (currently the secret is set to a testing Webhook, when it works I'll update to the real one)
2. define the AWS region in an env (setting to eu-central-1 by default, will need to override on job definition while logs are stored in us-east-1 but that's easy)
=> 1564 extra env values

data-serving/scripts/setup-db/migrations/20220322114358-drop-old-confirmation-date-index.js, data-serving/scripts/setup-db/migrations/20220322114550-add-confirmation-date-index.js
Added two migrations to replace `byConfirmationDateIfListed` index for the one using collation
=> Added db migrations

verification/curator-service/ui/src/components/landing-page/LandingPage.tsx, verification/curator-service/ui/src/components/landing-page/SignInForm.tsx
**Changes**
- Updates styles of login form to make it responsive
=> #2390 - Responsive login form

verification/curator-service/ui/src/constants/types.ts
**Changes**
- Added link to QA map environment
=> #2599 - map QA env

verification/curator-service/api/src/controllers/cases.ts, verification/curator-service/api/src/controllers/users.ts, verification/curator-service/api/src/model/user.ts
Removing mongoose in favour of the mongodb node.js driver, one file at a time.
This work is part of #2559 as it will enable using the indexed query for listing all country codes. Doing it incrementally as I need to fix cypress tests as I go.
=> 2559 incremental mongoose destruction

verification/curator-service/ui/cypress/integration/components/LandingPage.spec.ts, verification/curator-service/ui/src/components/landing-page/LandingPage.test.tsx, verification/curator-service/ui/src/components/landing-page/SignUpForm.tsx
**Changes**
- Added asterisks to all required fields in the sign up form as well as explainer text at the bottom
**Screenshot**
=> 2624 required fields

data-serving/scripts/setup-db/migrations/20220408103648-add-confirmation-date-index.js, verification/curator-service/ui/src/components/App/index.tsx, verification/curator-service/ui/src/components/FiltersDialog/index.tsx, verification/curator-service/ui/src/components/Sidebar/index.tsx, verification/curator-service/ui/src/components/util/helperFunctions.ts
**Changes**
- Last section of filters is hidden for non curators
- New MongoDB index added for `revisionMetadata.creationMetadata.curator`
=> #2384 - some filters hidden for non curators

verification/curator-service/api/src/util/validate-recaptcha-token.ts, verification/curator-service/ui/src/components/FiltersDialog/index.tsx, verification/curator-service/ui/src/components/landing-page/SignInForm.tsx, verification/curator-service/ui/src/components/landing-page/SignUpForm.tsx
Changes:
- changed places between before/after confirmed date filter
- added way for getting ReCaptcha site key for local development
=> #2567 confirmed before after date wrong way around ui fix

verification/curator-service/api/src/controllers/auth.ts, verification/curator-service/api/src/util/single-window-rate-limiters.ts, verification/curator-service/ui/package-lock.json, verification/curator-service/ui/package.json, verification/curator-service/ui/src/components/landing-page/LandingPage.tsx, verification/curator-service/ui/src/components/landing-page/SignInForm.tsx, verification/curator-service/ui/src/components/landing-page/SignUpForm.tsx, verification/curator-service/ui/src/types/index.d.ts
Changes:
- limiters now skip counting attempt when it is successful
- ReCaptcha badge is now invisible
- added information below the sign-in/up button that site is using ReCaptcha
- fixed bug that didn't block the action of a user that failed the ReCaptcha test
- moved part of code responsible for ReCaptcha from SignIn and SignUp form to LandingPage
=> Captcha bug fixes

ingestion/functions/parsing/new_zealand/new_zealand.py, ingestion/functions/parsing/new_zealand/new_zealand_test.py, ingestion/functions/parsing/new_zealand/sample_data.csv, ingestion/functions/tox.ini
Parser and test data have been updated to reflect changes in NZ data availability. URL updated through the curator UI.
=> NZ ingestion parser updated to match governmental data availability

ingestion/functions/common/parsing_lib.py, ingestion/functions/parsing/new_zealand/new_zealand.py, ingestion/functions/retrieval/retrieval.py
- Tidy up New Zealand ingestor (e.g. remove remaining references to 'DHB' which is no longer part of the source dataset)
- Modify retrieval function to stream incoming data to file, and refactor surrounding code. The previous code requested the data in one chunk which can lead to memory issues for very large files (e.g. 10Gb+).
=> Ingestion fixes

ingestion/functions/common/parsing_lib.py, ingestion/functions/retrieval/retrieval.py
- Fix to zip decompression after downloading files in chunks
- Automatically retry downloads if they stall prematurely; especially important when scheduling is sparse
=> Fix to zip decompression; retry large downloads when failing
