globaldothealth/list

- data-serving/data-service/.eslintrc.js
- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/controllers/home.ts
- data-serving/data-service/src/index.ts
- data-serving/data-service/src/server.ts
- data-serving/data-service/test/case.test.ts
- data-serving/data-service/test/home.test.ts
- data-serving/data-service/test/index.test.ts
Removed a (redundant) base config from eslintrc which was causing issues.
Mostly whitespace, double->single quotes, and EOL chars.
> Linting and formatting code. 

- verification/curator-service/.dockerignore
- verification/curator-service/Dockerfile
```
docker build . -t timothe/curator
Sending build context to Docker daemon  440.8kB
Step 1/7 : FROM node:12
---> 406aa3abbc6c
Step 2/7 : WORKDIR /usr/src/app
---> Using cache
---> cf67b089e577
Step 3/7 : COPY package*.json ./
---> Using cache
---> 8c30d5cd4100
Step 4/7 : RUN npm install
---> Using cache
---> d8aa7509a963
Step 5/7 : COPY . .
---> 7cd17bbbe603
Step 6/7 : EXPOSE 3001
---> Running in 448d0419acac
Removing intermediate container 448d0419acac
---> 3f8e34c315c0
Step 7/7 : CMD [ "npm", "start" ]
---> Running in 5b41ebadf68b
Removing intermediate container 5b41ebadf68b
---> d4ca9e9086c5
Successfully built d4ca9e9086c5
Successfully tagged timothe/curator:latest
timothe-macbookpro:curator-service timothe$ docker run -p 44444:3001 timothe/curator
> curator-service@1.0.0 start …
```
> add simple docker file for curator server

- data-serving/data-service/package-lock.json
- data-serving/data-service/package.json
- data-serving/data-service/src/index.ts
- verification/curator-service/package-lock.json
- verification/curator-service/package.json
- verification/curator-service/src/index.ts
Documentation [here](https://www.npmjs.com/package/dotenv). By convention, `.env` contains secrets and is .gitignored/strongly discouraged from being uploaded. We could share a copy in drive for development, perhaps.
As an example:
```
alex@anblox:~/.../data-serving/data-service$ cat .env && echo
PORT=3002
alex@anblox:~/.../data-serving/data-service$ npm run start
> data-service@1.0.0 start [...]/data-serving/data-service
> node dist/server.js
App running at http://localhost:3002.
Press CTRL-C to stop
```
> dotenv set up for both services

- verification/curator-service/package-lock.json
- verification/curator-service/package.json
- verification/curator-service/src/controllers/home.ts
- verification/curator-service/src/index.ts
- verification/curator-service/test/home.test.ts
Couple things:
- Not in love with the solution to type HTTP client responses (e.g. duplicating the interface definition). It's probably worth having a published type for clients to ingest that API data (at least for Node clients), but I'm satisfied with this as a starting point.
- I'll catch up with Allyson on front end plans tomorrow. For now, just getting this on the home page as a placeholder.
- Vagrant set up would be great. ;-) To test locally, I manually ran a local MongoDB and both Node apps. Not terrible, but could be better.
>  Render summary from data-service API on the curator-service home page.

- data-serving/data-service/package.json
- Prepending a clearCache command to prevent issues when files are moved/created.
- Not running coverage for watching specific files; mostly useless information.
- To use the single-file command, it'd be `npm run test-watch -- test/home.test.ts`, for example.
> Add npm scripts for jest watch mode(s).

- data-serving/data-service/schemas/cases.schema.json
This validator is missing a bunch of things, but it's a solid first attempt that at least validates everything's types, required fields, and some of the basic values.
It's still missing things like:
- Requiring one field or another (for source data)
- Actual dictionary values
- Maybe a better way of doing nested validation? (i.e. the location validation is redundant between location and travel_history.location)
> Initial mongodb validator for line-list case data

- .github/workflows/docker.yml
Last time I merged the CL calling /api/cases from the curator service which made the tests fail and I couldn't figure out why, I was just tired I guess.
Now calling the /api/sources and /api/cases directly instead of / to make it explicit and easier to debug.
> reenabled curl fetches of docker stack in github workflow

- verification/curator-service/ui/package-lock.json
- verification/curator-service/ui/package.json
- verification/curator-service/ui/src/components/App.tsx
- verification/curator-service/ui/src/components/EpidNavbar.tsx
- verification/curator-service/ui/src/components/LinelistCaseRow.tsx
- verification/curator-service/ui/src/components/LinelistTable.tsx
- verification/curator-service/ui/src/index.tsx
Paginate the case data table (to make the UI workable with a non-trivial amount of data).
Pagination is far better supported with `material-ui` rather than `bootstrap`, so this change makes that migration. Unfortunately the default material table isn't great (no row striping, low-contrast header), so some quick/light theming and stylization is included. Intended to be temporary, but makes the information easier to read, for now.
Comparison of changes:
> Paginate the case data table (and a couple other things)

- verification/curator-service/ui/src/components/App.tsx
- verification/curator-service/ui/src/components/EpidNavbar.test.tsx
- verification/curator-service/ui/src/components/EpidNavbar.tsx
- change empty list icon into a home button until we have a proper navbar on the left
- add a "Add a new case" button in the bar that navigates to /new
> tweak topbar

- data-serving/scripts/constants.py
- data-serving/scripts/convert_data.py
- data-serving/scripts/converters.py
This PR has a few commits, probably worth looking individually:
- First one is just autopep8 with new line lengths
- Second is separating input and output dataframes in preparation for adding the symptoms field, which has the same name in both input + output data sets -- it's also just cleaner and faster
- Third is the new conversions
Example of a comma-separated chronicDisease field (with unrelated stuff omitted for brevity):
```
{
...
"chronicDisease": {
"provided": [
"diabetes",
"hypertension",
"obesity"
]
},
"importedCase": {
...
"chronic_disease": "diabetes, hypertension, obesity",
...
}
}
```
And one with colon-separated symptoms:
```
{
...
"symptoms": {
"provided": [
"fever",
"cough",
"shortness of breath"
]
},
"importedCase": {
...
"symptoms": "fever:cough:shortness of breath", …
```
> [data conversion] Convert symptoms and chronic_disease fields

- data-serving/data-service/schemas/cases.schema.json
- data-serving/scripts/converters.py
Changes to converter include:
- range representation changes
- the fact that location id should be a string (even though historic data has ints)
Also updates schema to reflect what the imported data will look like (as opposed to new data entered via the server), i.e. the imported data:
- won't have ids (mongodb will autogenerate on import);
- may not have some of the required fields, since almost no column has 100% coverage
- may have many more fields in importedCase
Tested with mongoimport:
`417 document(s) imported successfully. 24 document(s) failed to import.`
> Update converter to export to latest data format

- data-serving/data-service/schemas/cases.schema.json
- data-serving/scripts/README.md
- data-serving/scripts/convert_data.py
- data-serving/scripts/converters.py
No lossiness since original fields are strings, so still 99.7% conversion success
100% successfully imported into mongodb (with removal of a couple of required fields in revisionMetadata in the schema)
Sample notes conversion:
```
{
...
"notes": "https://new.qq.com/omn/20200215/20200215A0LD4100.html; Contact with other confirmed cases; quarantined",
"importedCase": {
"ID": "000-1-10046",
...
"additional_information": "Contact with other confirmed cases; quarantined",
"notes_for_discussion": "https://new.qq.com/omn/20200215/20200215A0LD4100.html",
...
}
}
```
Sample revisionMetadata conversion:
```
{
...
"revisionMetadata": {
"id": 0,
"moderator": "TR"
},
"importedCase": {
"ID": "003-40161",
...
"data_moderator_initials": "TR",
...
}
}
```
> Convert notes and revisionMetadata fields

- data-serving/scripts/README.md
- data-serving/scripts/convert_data.py
- data-serving/scripts/converters.py
This is lossless.
Note that we only have URL/other text present in the source data so these are the only fields of these new objects we can automatically populate.
Examples:
```
"sequenceSource": {
"url": "https://github.com/openZH/covid_19"
}
```
```
"sequenceSource": {
"other": "10.03.2020"
}
```
```
"source": {
"url": "https://coronavirus.health.ny.gov/county-county-breakdown-positive-cases"
}
```
```
"source": {
"other": "Iran Ministry of Health"
}
```
> Covert source and pathogens fields

- .gitignore
- ingestion/functions/.gitignore
- ingestion/functions/README.md
- ingestion/functions/retrieval/requirements.txt
- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
- ingestion/functions/retrieval/scheduled_event.json
- ingestion/functions/template.yaml
Didn't add detailed documentation (I can do that in a subsequent PR). To test locally:
- Install the [SAM CLI](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install.html). Set up your AWS credentials if you haven't.
- Run the following:
```
$ cd ingestion/functions
$ sam build
$ sam local invoke "RetrievalFunction" -e retrieval/scheduled_event.json
```
Finer point: would prefer to add a venv set up for the python, but can do in a later PR. Until then I've found it simplest to run utilities as modules using the function's configured Python version, e.g. `python3.8 -m pytest retrieval/retrieval_test.py`.
Coarser point:
I did a fair bit of research on managing serverless resources, e.g. Lambdas and their accoutrements. _Some_ sort of …
> Create a bare-bones SAM/CF structure and retrieval Lambda function

- data-serving/scripts/README.md
- data-serving/scripts/convert_data.py
- data-serving/scripts/converters.py
Note that this is not lossless; specifically the reported_market_exposure has non-conformant (non-boolean) values.
Conversion success: 99.68%
Import success: 100%
Example outputs:
```
"outbreakSpecifics": {
"reportedMarketExposure": true
},
"importedCase": {
"ID": "002-5226",
"reported_market_exposure": "yes, retailer in the seafood wholesale market",
...
}
```
```
"outbreakSpecifics": {
"reportedMarketExposure": false,
"livesInWuhan": true
},
"importedCase": {
"lives_in_Wuhan": "yes",
"reported_market_exposure": "no",
...
}
```
> Convert the outbreakSpecifics field

- dev/.vscode/settings.json
(And small ~alphabetization fix.)
> Exclude node_modules in sample vscode settings.json.

- verification/curator-service/ui/src/components/LinelistTable.tsx
You have noticed I'm sure but we can't pass dotted.field.expression as material-table columns which means we should flatten all the received Case structure to display each field nicely and be able to update them as well.
I am not sure what to make of arrays yet, let's discuss tomorrow.
> Flatten Case data to display it in the table

- .github/workflows/curator-api-node.yml
- .github/workflows/curator-ui-node.yml
- .github/workflows/data-service-node.yml
```
timothe-macbookpro~/healthmap/healthmap-gdo-temp(nodes|…) % node --version
v12.16.2
```
No strong feeling about this but seems like we're just wasting free build time of github actions with that node version.
> stop testing on node 10.x we're not using it

- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/template.yaml
Overlooked this previously, since `sam local invoke` executes with the default profile/credentials configured in `~/.aws/`. I created a profile referencing the lambda function role ARN in order to test this stuff locally, but there's some issues assuming the role from the CLI. Didn't spin too long on it, since policy updates should be very infrequent.
> Grant retrieval lambda write access to S3.

- verification/curator-service/ui/src/components/App.tsx
- verification/curator-service/ui/src/components/EpidNavbar.test.tsx
- verification/curator-service/ui/src/components/EpidNavbar.tsx
/ will be used as an explanation page about the website and not require authentication, other subpages like /cases or /scrapers, etc will require auth.
> Change routes in frontend so that / can be a simple explanation page and not require auth

- data-serving/scripts/converters.py
- data-serving/scripts/parsers.py
- data-serving/scripts/utils.py
I know this looks like an enormous diff... because it is... but it's actually a no-op, aside from one bug fix* (aside from the bug fix, the diff between the exported cases at head and here is empty).
It's a big change because:
- I added a lot of **documentation**
- I **refactored** converters.py into 3 files: converters, parsers, and utils.
The breakdown is:
- **Converters** are the format-aware pieces that transform input format into output format.
- **Parsers** take a single value and parse it into the correct type/perform validation appropriate for that field.
- **Utils** are the not-those-things functions.
Now all of the logging is done in the converters, and exceptions are only raised in the parsers.
Since it's a reasonable-size refactor, I recommend ignoring the diff and focusing on …
> Refactor conversion script into parsers, converters, and utils

- dev/docker-compose.yml
- verification/curator-service/ui/Dockerfile
- verification/curator-service/ui/package-lock.json
- verification/curator-service/ui/package.json
- verification/curator-service/ui/src/components/LinelistTable.tsx
- verification/curator-service/ui/src/components/NewCaseForm.tsx
- verification/curator-service/ui/src/setupProxy.js
Yes I lied when I said I was out for today, couldn't let that one go sorry.
This is great, this means all /api calls are now made to the same origin. It will make auth much simpler.
I had to customize the proxy as described in https://create-react-app.dev/docs/proxying-api-requests-in-development/#configuring-the-proxy-manually because one cannot use "localhost" in docker composed networks (https://docs.docker.com/compose/networking/).
> proxy requests from 3002 to 3001 so that the UI only talks to itself

- data-serving/scripts/import-data/mongo-cli/index.d.ts
- data-serving/scripts/import-data/mongo-cli/package.json
This allows the import-data script, developed in ts, to understand the types from the mongo CLI.
Used these references for building it:
- https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#global-libraries
- https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-d-ts.html
And these references for the types:
- https://docs.mongodb.com/manual/tutorial/write-scripts-for-the-mongo-shell/
- https://docs.mongodb.com/manual/reference/method/
> Add a private global module for mongo-cli types

- verification/curator-service/api/src/controllers/auth.ts
- verification/curator-service/ui/src/components/App.tsx
- verification/curator-service/ui/src/components/EpidNavbar.test.tsx
- verification/curator-service/ui/src/components/EpidNavbar.tsx
- verification/curator-service/ui/src/index.tsx
- verification/curator-service/ui/src/setupProxy.js
After login:
Steps to try out locally:
```
./dev/run_stack.sh
Then go to http://localhost:3001/auth/google, accept the oauth prompt.
Then go to http://localhost:3002 to access the UI.
```
Because we run the server and the UI on different ports, clicking the login button doesn't work and you have to go to the localhost:3001/auth/google manually now , it will work in prod because they will be served from the same domain but until I find a better solution this manual step is needed.
Logout works as expected.
> add login/logout buttons to navbar

- verification/curator-service/api/package-lock.json
- verification/curator-service/api/package.json
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/test/auth.test.ts
- verification/curator-service/api/test/cases.test.ts
- verification/curator-service/api/test/home.test.ts
- verification/curator-service/api/test/index.test.ts
- verification/curator-service/api/test/sources.test.ts
Otherwise each time the server reloads when we change something the default "in-memory" store gets killed and we have to re-login that's annoying.
All tests importing the top-level app object now require a mongoose connection, so I've mocked them all up.
> Store session info in Mongo

- data-serving/data-service/Dockerfile
- dev/docker-compose.yml
- verification/curator-service/api/Dockerfile
- verification/curator-service/ui/Dockerfile
Specify services build context and dockerfile separately. Define the context as the epid root dir, allowing use to use shared files (e.g. #109).
There are two downsides here, which are:
- Forced compartmentalization can be a good thing at times (though Node TS provides this, to an extent).
- Slightly more cognitive overhead in our docker config.
Happy to revert if we don't want this, though I'm leaning "worth" right now.
> Raise docker-compose build context dir to allow file sharing

- data-serving/scripts/import-data/package-lock.json
- data-serving/scripts/import-data/package.json
- data-serving/scripts/import-data/src/index.ts
- data-serving/scripts/import-data/src/types/mongo-cli.d.ts
Does NOT include inserting data; this can be used in conjunction with `mongoimport` to do that (and the npm script in data-serving/data-service). (I ran into some inconsistent behavior -- to put it lightly -- and think it's best to use mongoimport for that piece.)
Left a TODO for adding indexes once we have defined those.
I'm super aware that the npm script for running this is truly insane, so I'm open to suggestions.
TESTED:
```
npm run setup-cases
> import-data@1.0.0 setup-cases /usr/local/google/home/khmoran/Dev/healthmap-gdo-temp/data-serving/scripts/import-data
> tsc && mongo --eval "let args={databaseName: 'covid19', collectionName: 'cases', schemaPath: './../../data-service/schemas/cases.schema.json'}" dist/index.js
MongoDB shell version v4.2.6
connecting to: …
```
> Initial script to setup db: create collection, apply validator, and drop data

- .dockerignore
- .github/workflows/docker.yml
- .gitignore
- data-serving/data-service/.dockerignore
- dev/README.md
- dev/docker-compose.ci.yml
- dev/docker-compose.dev.yml
- dev/docker-compose.yml
- dev/run_stack.sh
- verification/curator-service/api/.dockerignore
- verification/curator-service/ui/.dockerignore
I noticed the build was *SLLLOOOOWWWW* this morning on my computer, it turns out that .dockerignore files are read from the build context, not from where the Dockerfile is. So we would send all node_modules/ directories to the docker builder daemon for each build which was gigs of data for nothing, now we only send a dozen mb ax and builds are fast again.
I also used a .env which is supported natively by docker-compose to store oauth secrets, I'll send you the secrets so that you can enable login once Gaurav send them to me.
> fix docker build with new context

- data-serving/data-service/schemas/cases.schema.json
Was debugging why the validator on mongoose was rejecting documents created from curator UI -- turns out our server is adding fun new fields I didn't expect, and the additionalProperties field was getting angry.
TL;DR: Sub-documents have their own _id fields, and the case doc gets a version key field: https://mongoosejs.com/docs/guide.html#versionKey
Now if I run:
`dev/run_stack.sh`
`dev/setup_db.sh`
and insert/update a row via the curator CRUD UI, it works!
> Update schema to work with documents created by dataserver

- verification/curator-service/ui/src/components/App.tsx
- verification/curator-service/ui/src/components/SourceTable.test.tsx
- verification/curator-service/ui/src/components/SourceTable.tsx
Breaking this story up to keep PR length sane. For now, just adding a minimal `/sources` page and `SourceTable` component; largely analogous to a simplified `LinelistTable`. The existing `Source` model isn't exactly what Tim and I landed on, but I'll address that after the bulk of the interface boilerplate is taken care of. Still adding the types to the component file to be "correct," though we could technically get away with just defining `_id`/`name`.
> Barebones /sources curator UI page

- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/test/controllers/case.test.ts
- verification/curator-service/api/src/controllers/sources.ts
- verification/curator-service/api/test/sources.test.ts
Making this behavior analogous to the Case API, until we decide on a different standard (to simplify/commonize handling of responses in the UI). Mostly:
- Return the resource from `POST /api/sources`.
- Return 201 from `POST /api/cases` on the data service.
- Test the same behaviors.
> Return the created source from the Source API.

- .github/workflows/integration-tests.yml
- dev/test_all.sh
- verification/curator-service/api/src/util/validate-env.ts
- verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
- verification/curator-service/ui/package-lock.json
- verification/curator-service/ui/package.json
Requires changing the test to an add rather than edit test, because the stack that's brought up with docker-compose doesn't have any existing rows in the table. Will clean up this discrepancy between local / CI in a future PR.  
Will also remove the docker.yaml file once we add an integration test for /sources.
> Run integration tests in CI

- data-serving/data-service/schemas/cases.schema.json
- data-serving/scripts/convert-data/README.md
- data-serving/scripts/convert-data/constants.py
- data-serving/scripts/convert-data/convert_data.py
- data-serving/scripts/convert-data/converters.py
Removes some redundant data and saves some space.
Also to reduce bloat (would've done in a separate PR but too annoying):
- Removes the species field (I'm guessing we can assume human unless otherwise specified -- on the fence about whether to explicitly include)
- Only populates the pathogens field when there's sequence source data (i.e. not just the name of the covid pathogen)
We're still over quota by a bit after the latest cases are published; should figure out what to do there separately (start using prod?)
TESTED: Applied the new schema and data imported without validation errors.
```
2020-05-18T22:06:06.613-0400    Failed: (AtlasError) you are over your space quota, using 516 MB of 512 MB
2020-05-18T22:06:06.613-0400    777000 document(s) imported successfully. 0 document(s) failed …
```
> Don't include lossless fields in the importedCases field to save disk space

- data-serving/scripts/convert-data/parsers.py
- Handle ages (or in theory other ranges) of the format "x+"
- Attempt to parse dates in reverse month/date format if they fail due to a ValueError
The former was resulting in thousands of errors; the latter in just a few, but it allows the date_death_or_discharge to be converted 100% successfully.
> Improve age & date parsing to cut down on parsing erros

- data-serving/data-service/src/index.ts
- verification/curator-service/api/src/index.ts
Otherwise we're left with a non-connected mongoose that makes for a useless server.
Mongoose apparently doesn't have an indefinite retry mechanism built-in.
We could build our own retry mechanism within index.ts for each service but I think for now we're fine with relying on kubernetes or ECS orchestrator to restart containers automatically.
> exit process when DB can't connect

- verification/curator-service/api/src/model/automation.ts
- verification/curator-service/api/src/model/parser.ts
- verification/curator-service/api/src/model/regex-parsing.ts
- verification/curator-service/api/src/model/schedule.ts
- verification/curator-service/api/src/model/source.ts
- verification/curator-service/api/test/model/automation.test.ts
- verification/curator-service/api/test/model/data/automation.full.json
- verification/curator-service/api/test/model/data/parser.full.json
- verification/curator-service/api/test/model/data/regex-parsing.full.json
- verification/curator-service/api/test/model/data/schedule.full.json
- verification/curator-service/api/test/model/data/source.full.json
- verification/curator-service/api/test/model/parser.test.ts
- verification/curator-service/api/test/model/regex-parsing.ts
- verification/curator-service/api/test/model/schedule.test.ts
Need to get a handful of validations and protections in place before we hit the AWS API from our Sources API. This is the bulk of doing so, less one last change for the inclusion of a schedule expression that I'll send subsequently.
Apologies for lumping these together; in this case seemed the lesser evil.
> Prep Source schema for AWS API integration

- verification/curator-service/ui/src/components/App.test.tsx
- verification/curator-service/ui/src/components/App.tsx
- verification/curator-service/ui/src/components/EpidNavbar.test.tsx
- verification/curator-service/ui/src/components/EpidNavbar.tsx
- verification/curator-service/ui/src/components/Profile.test.tsx
- verification/curator-service/ui/src/components/Profile.tsx
I pulled the `axios.get<User>('/auth/profile')` out into the App file because the User information was now being used in EpidNavbar and Profile.
Logged in:
logged out:
> Add a simple profile page

- data-serving/data-service/api/dataserver.api.yaml
- data-serving/data-service/api/openapi.yaml
- data-serving/data-service/package-lock.json
- data-serving/data-service/package.json
- data-serving/data-service/src/index.ts
- This PR just adds a (partial) service definition, and adds a documentation endpoint -- it does NOT validate requests and responses or otherwise integrate with express
- GET is the only endpoint in there right now
- The GET response is incomplete because I didn't want to flesh it out until I was sure that this approach LG
Screenshot of /api-docs endpoint:
> Add a skeleton/partial open API definition for the dataserver

- verification/curator-service/api/src/controllers/auth.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/src/util/validate-env.ts
- verification/curator-service/api/test/auth.test.ts
Exposes a /auth/register handler to create users when node_env != production to enable easy testing of logged in handlers.
> example test using local auth

- data-serving/data-service/package-lock.json
- data-serving/data-service/package.json
Package isn't used -- but has a handful of security vulnerabilities.
Might be a couple other updates here; ran `npm update` after removing swagger. `npm audit` confirms there are no remaining vulnerabilities.
> Remove swagger package and update dependencies.

- data-serving/data-service/api/openapi.yaml
- Removes tags
- Makes error responses reusable (OK response content may differ between endpoints)
- Moves GET params to top-level since {id} is in the URL (and so it would apply to all requests of that path)
- Adds MIT license URL
- Makes /api part of the base path for all requests
> Cleanup of dataserver API spec in preparation for adding more endpoints

- data-serving/data-service/api/openapi.yaml
(Note: first commit is minor cleanup)
Following the inheritance pattern for the entities, since I expect that the case that we POST will be a strict subset of what we GET/LIST, although both are just {} right now:
- Docs: https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/
- Example: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore-expanded.yaml
Screencast:
> Add endpoint definition for create case

- verification/curator-service/ui/cypress/plugins/index.ts
There were two issues with this code:
- resolve wasn't called in the callback so the promise would be resolved even tough the db hadn't been cleared yet
- db.close() wasn't called so dangling connections were left open
https://mongodb.github.io/node-mongodb-native/api-generated/mongoclient.html
> close DB after clearDB task run

- verification/curator-service/api/src/model/schedule.ts
- verification/curator-service/api/test/model/data/schedule.minimal.json
- verification/curator-service/api/test/model/schedule.test.ts
See comment in the model file. Open to suggestions, if there's a better way to facilitate this pattern with Mongoose et al.
> Make source.automation.schedule.awsRuleArn optional

- dev/README.md
- dev/docker-compose.yml
- verification/curator-service/ui/src/components/SourceTable.test.tsx
- verification/curator-service/ui/src/components/SourceTable.tsx
Couple notes:
- Considered doing something with "better" UX around schedule expression, but ended up reversing that. For lack of a bit more thought on the UX, we should probably punt on this for now.
- Not including AWS-esque validation on the schedule. There's a medium-sized regex in the Curator API data layer we can share here, but wasn't totally happy with just copy-pasta'ing that. Can revisit this later on.
- Excuse the inclusion of Docker changes, which I've added to locally E2E test.
> Add automation details to the ingestion sources UI

- verification/curator-service/api/src/controllers/sources.ts
- verification/curator-service/api/src/model/source.ts
- verification/curator-service/api/test/sources.test.ts
NB: This doesn't include deleting a rule in an update. The client library doesn't include delete yet; I'll add this with/after Source delete integration.
I'm also including a small change to rule naming, using `source._id` in lieu of `source.name`. It' not human readable, but avoids issues with formatting restrictions (e.g. can't include spaces) and uniqueness. Can swing around to re-UX this later if it's important.
> Integrate the Source API update method with AWS CloudWatch Events

- verification/curator-service/api/src/clients/aws-events-client.ts
- verification/curator-service/api/src/controllers/sources.ts
- verification/curator-service/api/test/clients/aws-events-clients.test.ts
- verification/curator-service/api/test/sources.test.ts
Doesn't include delete-as-update -- that'll be subsequent.
> Add deletion to the AWS CWE client API; integrate this with the Sources API

- verification/curator-service/api/src/controllers/sources.ts
I'd intended this to be a more interesting change, but ran into a bug with our various APIs' update operations (re: Slack). We cannot yet remove a field on an update, and so the `else` branch I'm adding here is effectively unreachable.
For now, add some simple logic that -- in the event of nefarious alpha particle induced bit flips, or the event that we inadvertently goof up Mongoose validation -- correctly performs either a `put`- or `deleteRule` request to the AWS CW Events API based on a given Source API update.
> Add logic that dictates whether AWS CW rules are put or deleted during source updates

- aws/README.md
- aws/alb-ingress-controller.yaml
- aws/alb-ingress-iam-policy.json
- aws/curator-ingress.yaml
- aws/curator.yaml
- aws/data.yaml
- aws/rbac-role.yaml
Currently login doesn't work as we have to change the oauth callback URLs and I don't have the perms to do that, I asked Spencer for perms and or changes to be made.
Also switches back to `latest` tag for dev images.
dev: http://51cfaa79-default-curatorde-771d-764651811.us-east-1.elb.amazonaws.com/
prod: http://51cfaa79-default-curatorpr-5c7d-1665373250.us-east-1.elb.amazonaws.com/ (old version from last week)
> Expose curator services externally

- data-serving/scripts/convert-data/README.md
- data-serving/scripts/convert-data/constants.py
- data-serving/scripts/convert-data/convert_data.py
- data-serving/scripts/convert-data/converters.py
- data-serving/scripts/convert-data/geocode_util.py
- data-serving/scripts/convert-data/parsers.py
Sorry for the big diff :\ This PR is doing a few things:
- Reusing the same geocoding data for the travelHistory.location as is used in the original CSV for geocoding the location field. This gets us (1) better coverage than pycountries (countries & counties only), (2) more consistency, and (3) full geospatial data (lat/longs).
- Changing the script to take in a path to the location of a locally-checked out nCoV19 repo, for (1) access to the CSV, and (2) for access to the geocoding script & data.
- Adding some very common abbreviations used in the travelHistory.location source, since fixing every one of these would be a lot of work.
- Remove hacks and workarounds, like removing 'Travelled to' prefixes. We're logging these as errors so we can fix them at the source.
Note that the existing …
> Converter: Geocode the travelHistory with the same system as the location field

- data-serving/data-service/schemas/cases.schema.json
- data-serving/scripts/setup-db/README.md
- data-serving/scripts/setup-db/package.json
- data-serving/scripts/setup-db/src/index.ts
This is the first step in letting us trigger updates to the prod db; this will be one of the scripts called by the workflow when the CSV data is updated.
Specifically, after this change, I can update prod MongoDB with the latest CSV by:
1. Git pull on the ` nCoV2019` repo
2. Running `healthmap-gdo-temp/data-serving/scripts/convert-data.py`
3. Running this script (in `healthmap-gdo-temp/data-serving/scripts/setup-db`)
4. Running `mongoimport` on the results of (2)
I'll chain these things together in a master script that will get triggered by the webhook.
And you get a bonus small schema change! Issue discovered after setting up the prod db and importing the newest data. You're welcome!
TESTED=Successfully updated the prod db using this script
> Update the setup-db script to take in an optional connection string

- aws/curator.yaml
- aws/data.yaml
This is to show the charts in prod FE.
Data service doesn't really have to be updated but there's no hurting doing it as well.
http://51cfaa79-default-curatorpr-5c7d-1665373250.us-east-1.elb.amazonaws.com/charts/cumulative
> bump curator and data service to v0.0.4

- .gitignore
- data-serving/scripts/convert-data/README.md
- data-serving/scripts/convert-data/convert_data.py
- data-serving/scripts/convert-data/converters.py
- data-serving/scripts/convert-data/utils.py
This lets us easily import the results into a spreadsheet to share with the folks who will be fixing them
- Format as TSV for easy import into sheet
- Filter out logs from geocoding script by setting log level to error
- Include original field names so that folks correcting original data know where to look
> Improve reporting of conversion errors

- verification/curator-service/api/package.json
- verification/curator-service/api/src/clients/aws-events-client.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/src/util/validate-env.ts
- verification/curator-service/api/test/clients/aws-events-client.test.ts
Couple notes:
- I wouldn't consider the way this synchronizes our state with AWS resources to be particularly "hardened." For instance, if our `putTargets` call fails following a `putRule` call, we'd probably want to rollback the rule creation. This isn't a now problem -- can do this hardening later.
- Now that the test AWS integration is a bit more in depth, I streamlined the way we configure the mock package. Sorry to include this in one change, but thought it was the lesser of two evils as compared to sending a dedicated PR for this.
> Populate source rule targets to trigger the global retrieval function

- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/package-lock.json
- verification/curator-service/api/package.json
- verification/curator-service/api/src/controllers/sources.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/test/sources.test.ts
I wasn't sure whether or not to add /cases to the yaml, since it is already documented/verified in the data-service OpenAPI. I refrained for now, but let me know if you think it would be useful to add here as well.
> Add OpenAPI for curator service api

- verification/curator-service/api/src/clients/aws-events-client.ts
- verification/curator-service/api/src/controllers/sources.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/src/model/source.ts
- verification/curator-service/api/test/clients/aws-events-client.test.ts
- verification/curator-service/api/test/model/source.test.ts
- verification/curator-service/api/test/sources.test.ts
Includes a couple changes to the AWS CWE client itself. Mostly to keep logic as AWS-oriented as possible, and leaving the intepretation from source data model-to-AWS params in the source controller (and source data model custom instance methods).
> Wire up the source API to set rule targets to the global retrieval Lambda ARN

- verification/curator-service/Dockerfile
Otherwise the prod image can't load the openapi definitions.
> copy openapi folder in prod curator image

- .github/workflows/case-data-update.yml
Note that is only run on updates to the data conversion script & on a once-a-day schedule -- the next step is to figure out the webhook piece
TESTED=Using https://github.com/nektos/act, ran:
`act -j update-case-data-prod -P ubuntu-latest=nektos/act-environments-ubuntu:18.04-full -s DB_CONNECTION_URL=<db_conn_url>`
> Creates github workflow to execute the data update pipeline against prod mongodb

- .github/workflows/case-data-update.yml
- data-serving/scripts/convert-data/constants.py
- data-serving/scripts/convert-data/convert_data.py
- data-serving/scripts/convert-data/converters.py
- data-serving/scripts/convert-data/geocode_util.py
- data-serving/scripts/convert-data/parsers.py
Now that the CSV has over 2M rows, the script is taking a long time to run. Especially since it will be run from a GitHub action, I wanted to optimize it a bit. I figured that reducing the amount of json in memory would help, so I'm now reading in 1 row at a time and writing out 1 case at a time. It unfortunately requires a little JSON hackery but it's not too bad.
Since we're doing manipulations only on a single row, and not across columns, I think pandas isn't really speeding things up, so I switched to a pure CSV reader (it's a bit simpler).
The current dataset (2M+ rows) converts on my machine in:
- 9min16s with this version
- 39m44s with the prior version is still running 
Note that the sampling is no longer random; it's systematic. (Which maybe is preferable for diffing changes …
> Improve performance of convert_data.py

- verification/curator-service/api/package-lock.json
- verification/curator-service/api/package.json
- verification/curator-service/api/src/controllers/auth.ts
- verification/curator-service/api/src/model/user.ts
- verification/curator-service/api/test/auth.test.ts
- verification/curator-service/api/test/model/user.test.ts
Since I'm adding a programmatic API consumer elsewhere (ingestion), I've found that the passport Google auth strategy is largely built around the browser flow. While it's conceivable we could _somehow_ manually spoof that flow, the canonical solution for API support is typically to accept bearer token auth.
I'm adding it as a fallback for RBAC'd requests in which there isn't an active user session. Passport's bearer strategy inspects the request for a token (in various RFC 6750 formats), and if present, will execute the strategy I defined.
While I was adding tests, I noticed that a handful of the existing auth tests have a classic async Jest bug -- not returning or awaiting the promise. I can clean this up in a separate PR; some of the cases didn't pass.
> Add an HTTP bearer token auth strategy for the curator server

- .github/workflows/case-data-update.yml
- The workflow failed to run over the weekend because the machine it's running on has newer versions of the mongodb packages installed. I think we want to downgrade to our versions because to ensure a consistent env, so we're now passing the `--allow-downgrades` arg to `apt-get install` (see one of the failed runs here: https://github.com/open-covid-data/healthmap-gdo-temp/runs/748668598)
- I got warnings locally about not being able to install 2 of the packages because their public keys weren't available, so I added the `apt-key adv` line to retrieve those keys from a key server
> Update the case data update workflow to fix mongodb cli install

- verification/curator-service/ui/cypress/integration/components/UsersTest.spec.ts
Key fix is waiting for the http request to finish before checking the updates. The check for updates waits 4 seconds, but that is not enough when running on CI. 
Also removes closing the popup, since it is unnecessary and adds complications.
> Fix flaky test

- verification/curator-service/api/src/index.ts
I was originally going for a full blown csrf token based approach (https://github.com/open-covid-data/healthmap-gdo-temp/compare/csrf?expand=1) but this was waaaaay too involved imo and was breaking the ingestion pipeline calls that Alex wrote yesterday.
You can see here how same site cookie helps defend against CSRF: https://portswigger.net/web-security/csrf/samesite-cookies
We are not using a lax framework in terms of POST becoming GET (express doesn't do that kind of change itself) so I am fine with just relying on samesite cookies as a starting point or even staying like this long-term.
We can also think about moving to "lax" mode if navigation from other sites becomes impractical, for now there should be no issues like that.
> use same site cookie strict for session cookie

- .github/workflows/case-data-update.yml
This prepares our workflow action to run when we receive a repository_dispatch event from the nCoV2019 repo (which isn't yet sending them)
> Add a repository_trigger event to the case-data-update workflow

- .gitignore
- ingestion/functions/ci-requirements.txt
- ingestion/functions/retrieval/requirements.txt
- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
- ingestion/functions/retrieval/valid_scheduled_event.json
- ingestion/functions/template.yaml
Few notes:
- Per the title, just covering JSON for now. Not that it'll be difficult to add other formats, but starting with just the JSON to support the data API from India.
- Now that there's a fair amount more meat in the function, restructured tests around individual units (with one end-to-end happy path).
- Ended up storing service account credentials in S3. Bundling them into the Lambda package made it hard to keep the file hidden, and it didn't feel like encrypting individual fields in env variables was any better than using S3.
> Add full, authenticated retrieval using the Source API (for JSON content)

- dev/.vscode/settings.json
Will pick up eslint actions and auto format instead which makes it consistent with npm lint --fix
> update settigns json to not format on save

- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
- ingestion/functions/template.yaml
Couple small notes:
- Small additional change to the retrieval function, so that I could generalize the SourceApiUrl SAM template param to work for both retrieval and parsing.
- Testing isn't super thorough for the AWS Lambda client. Gave it a fair shot, but it's a PITA to test -- even with the stub library I'm using to test s3 (`moto`). This code will probably change a few times in the next couple weeks, and be relatively stable thereafter, so I'm OK with saving the testing gore.
> Add India parser function SAM definition; trigger source parser lambdas in retrieval

- data-serving/data-service/schemas/cases.schema.json
- data-serving/data-service/src/model/demographics.ts
- data-serving/data-service/test/controllers/case.test.ts
- data-serving/data-service/test/model/data/case.full.json
- data-serving/data-service/test/model/data/demographics.full.json
- data-serving/data-service/test/model/demographics.test.ts
- data-serving/samples/cases.json
- data-serving/scripts/convert-data/README.md
- data-serving/scripts/convert-data/converters.py
- Species has been nixed
- Profession, nationality, and ethnicity have been added: All optional string fields. In the future should be validated against a data dictionary.
In the future, profession and nationality will be validated against data dictionaries (no free text entry); ethnicity will have a data dictionary but the option to write in free text
> Bring demographics schema in line with data model standard spec

- verification/curator-service/ui/src/components/Users.test.tsx
- verification/curator-service/ui/src/components/Users.tsx
Some users (ingestion lambda API users for example) have no public name, show emails in the users list to help identify all users.
> handle empty names and display email

- verification/curator-service/api/src/clients/aws-events-client.ts
- verification/curator-service/api/src/controllers/sources.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/test/clients/aws-events-client.test.ts
- verification/curator-service/api/test/sources.test.ts
Moved the `AddPermission` invocation from the sources controller to the CloudWatch Events client, which covers us for update operations now, in addition to creations. Needing the permission is a result of creating the target -- so it's cleaner to make this call here. Keeping the `AwsLambdaClient` separate, because it's still a helpful abstraction and I'm anticipating calling it directly in a future PR.
> Configure resource-based policy for Lambdas in update operations

- verification/curator-service/api/src/clients/aws-events-client.ts
- verification/curator-service/api/src/clients/aws-lambda-client.ts
- verification/curator-service/api/src/controllers/sources.ts
- verification/curator-service/api/src/model/source.ts
- verification/curator-service/api/test/clients/aws-events-client.test.ts
- verification/curator-service/api/test/clients/aws-lambda-client.test.ts
- verification/curator-service/api/test/model/source.test.ts
- verification/curator-service/api/test/sources.test.ts
Based on #270 -- diff here is from the 3rd commit onwards.
> Remove resourced-based policy permissions in source API delete operations

- verification/curator-service/ui/src/components/Location.test.tsx
- verification/curator-service/ui/src/components/Location.tsx
Not plugging it in yet in the new case form until we can query geolocation info from the curator service.
With content from mocks:
Without location:
> add component to display geolocation information

- suggest/README.md
- suggest/nationalities.txt
- suggest/place_of_transmission.txt
This is based on the sheets in "Line list data model: Standard specification" spreadsheet from Stephen.
I didn't add the professions because they are way too noisy and need cleaning before we check it in.
They will be fetched using https://material-ui.com/components/autocomplete/#asynchronous-requests
> add files that will be used for async fetch of suggestions in new case form

- data-serving/data-service/schemas/cases.schema.json
- data-serving/data-service/src/model/location.ts
- data-serving/data-service/src/model/revision-metadata.ts
- data-serving/data-service/test/model/data/case.full.json
- data-serving/data-service/test/model/data/case.minimal.json
- data-serving/data-service/test/model/data/location.full.json
- data-serving/data-service/test/model/data/location.minimal.json
- data-serving/data-service/test/model/data/travel.full.json
- data-serving/data-service/test/model/location.test.ts
- data-serving/samples/cases.json
- data-serving/scripts/convert-data/README.md
- data-serving/scripts/convert-data/constants.py
- data-serving/scripts/convert-data/convert_data.py
- data-serving/scripts/convert-data/converters.py
- data-serving/scripts/convert-data/parsers.py
- data-serving/scripts/data-pipeline/convert_and_import_latest_data.sh
- verification/curator-service/ui/cypress/support/commands.ts
- verification/curator-service/ui/src/components/LinelistTable.test.tsx
- verification/curator-service/ui/src/components/LinelistTable.tsx
- verification/curator-service/ui/src/components/NewCaseForm.test.tsx
- verification/curator-service/ui/src/components/NewCaseForm.tsx
- verification/curator-service/ui/src/components/SourceTable.tsx
Sorry as usual for the large diff :\ womp womp -- some of it is autoformatting though
Major changes:
- Remove location.id field; @attwad thinks we won't need it (and I agree)
- Add enum field `location.geoResolution`, and modify the converter to populate it (for location and travelHistory.location)
- Replace `location.locality` with `location.administrativeArea3` -- we do need this to be able to fully specify locations, and it is present in current data (it's not in the spec, though I'll see if Stephen wants to add it; even so, would rather not lose this precision even if we're not going to export this field)
- Add `location.place`: A POI, like a hospital
- Add `location.name`: A human-readable, short name for the location
- In the converter, use all the fields that are populated by the …
> Bring location schema in line with spec

- data-serving/data-service/schemas/cases.schema.json
- data-serving/data-service/src/model/event.ts
- data-serving/data-service/test/model/data/case.full.json
- data-serving/data-service/test/model/data/event.full.json
- data-serving/samples/cases.json
Adding a "value" field to the event schema to capture the content of the event, as well as the date; 
The values we expect include:
- Method of confirmation | String | Multiple choice | - PCR test- Serological test- Clinical diagnosis- 
- Hospital admission | String | Multiple choice | - Yes- No- Unknown
- Admitted to isolation unit in hospital | String | Multiple choice | - Yes- No- Unknown
- Outcome | String | Multiple choice | - Death- Recovered- Unknown
Not going to specify these values in the schema to keep it more open; I think it's probably OK for the UI to be the arbiter here.
> Bring events schema up to spec

- data-serving/scripts/setup-db/README.md
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/geocoding/fake.ts
- verification/curator-service/api/src/geocoding/geocoder.ts
- verification/curator-service/api/src/geocoding/mapbox.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/src/util/validate-env.ts
- verification/curator-service/api/test/auth.test.ts
- verification/curator-service/api/test/cases.test.ts
- verification/curator-service/api/test/geocoding/mapbox.test.ts
- verification/curator-service/api/test/index.test.ts
- verification/curator-service/api/test/sources.test.ts
- verification/curator-service/api/test/users.test.ts
- verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
- verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts
- verification/curator-service/ui/cypress/support/commands.ts
- verification/curator-service/ui/src/components/LinelistTable.test.tsx
- verification/curator-service/ui/src/components/LinelistTable.tsx
- verification/curator-service/ui/src/components/NewCaseForm.test.tsx
- verification/curator-service/ui/src/components/NewCaseForm.tsx
If a new case doesn't have lat/lng it will trigger geocoding based on the request's `location.query` string.
I replaced `country` in the new form with this `query` field. It will be an autocomplete field once we have it working (ETA 4-5 years based on early assessment).
In order to be able to run the dev stack connected to map box and the integration tests as well I made the cases controller accept an array of geocoders that are called in sequence. This way we can fake locations in integration tests and play with real geocodes on our local stack.
We also should probably retire the edit/new functionality of the linelist table soon, fixing the tests is not super fun now that the new form and the table have drifted a bit.
> Geocode new cases

- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/test/cases.test.ts
Only non-triviality here is geocoding. I've just extracted the biz logic to be shared by create and upsert mechanisms.
> Add a proxy upsert API to the curator service

- verification/curator-service/api/src/geocoding/mapbox.ts
- verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts
- verification/curator-service/ui/src/components/NewCaseForm.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Location.test.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Location.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Notes.tsx
A few nit fixes a long the way, making the API consistent between what the UI has and what the curator service expects to avoid a bunch of transformations when sending the request/receiving the geocode results.
Also fix the geocode of top level features (countries) which do not have context attached to them so we couldn't iterate over those.
> Prepare for geo suggestions

- data-serving/data-service/schemas/cases.schema.json
- data-serving/data-service/src/model/case-reference.ts
- data-serving/data-service/src/model/case.ts
- data-serving/data-service/test/model/case-reference.test.ts
- data-serving/data-service/test/model/data/case-reference.full.json
- data-serving/data-service/test/model/data/case-reference.minimal.json
- data-serving/data-service/test/model/data/case.full.json
I'll chat with Kelly next week, but for the time being, this adds the `CaseReference` object defined in the official line list spec to our data service schema/model. This is necessary to perform upsert for the purpose of deduplication, which I'll send subsequently.
I suspect we'll want to somewhat merge this with the `Sources` field; something for me to pick Kelly/Stephen's brain on next week.
> Add CaseReference object, per spec, to our case schema/model

- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/index.ts
- data-serving/data-service/test/controllers/case.test.ts
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/test/cases.test.ts
I'd originally envisioned implementing this with `Mongoose.Model.findOneAndUpdate([...], {upsert=true})`, but it turns out that behavior's pretty thorny. I've used some straight-forward base calls instead, which seems to be the simplest solution here.
One thing I'm lukewarm on is the fact that we're allowing partial updates here. But, best to leave that consistent with the PUT update API until we introduce a PATCH endpoint.
> Add the case upsert API to the data service

- verification/curator-service/ui/src/components/NewCaseForm.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/FormikAutocomplete.tsx
undefined can't be set as a default value for dates. When it is set the date picker UI element shows today's date rather than a blank picker (as it does for null).
> Use undefined rather than null where possible

- verification/curator-service/api/src/geocoding/mapbox.ts
- verification/curator-service/api/test/geocoding/mapbox.test.ts
- verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx
Use the `place_name` field instead of the `text` which is more suitable for suggest and overall.
Add an icon next to the suggestions.
New suggest UI:
> Better looking place suggest

- verification/curator-service/ui/src/components/LinelistTable.test.tsx
- verification/curator-service/ui/src/components/LinelistTable.tsx
A bit more in line with the figma mocks now. Chose the interval display for age `[,...)` instead of  `xx-yy` not sure what's best yet.
Also disable reordering of columns and put actions at the end as per the mocks (we'll want to switch to a menu instead perhaps)
> Remove ID column and display age properly

- data-serving/scripts/convert-data/converters.py
- verification/curator-service/ui/src/components/LinelistTable.test.tsx
- verification/curator-service/ui/src/components/LinelistTable.tsx
> Display only location name and country in linelist table instead of various geo fields

- verification/curator-service/ui/src/components/App.tsx
The white primary color was causing issues with invisible text + buttons.
> Update color theme

- .github/workflows/case-data-update.yml
- data-serving/scripts/setup-db/package.json
There are two errors in the logs from the workflow:
```
MongoDB shell version v4.2.6
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
2020-06-23T05:15:20.984+0000 E  QUERY    [js] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed: SocketException: Error connecting to 127.0.0.1:27017 :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:341:17
@(connect):2:6
2020-06-23T05:15:20.986+0000 F  -        [main] exception: connect failed
2020-06-23T05:15:20.986+0000 E  -        [main] exiting with code 1
```
The change in the package.json is meant to address this, by having the `mongo` command connect to the proper connection string (even though the subsequent js that it evals will re-connect to it)
``` …
```
> Maybe try to fix daily case update workflow?

- data-serving/data-service/schemas/cases.schema.json
- data-serving/data-service/src/model/transmission.ts
- data-serving/data-service/src/model/travel.ts
- data-serving/data-service/test/model/data/case.full.json
- data-serving/data-service/test/model/data/transmission.full.json
- data-serving/data-service/test/model/data/travel-history.full.json
- data-serving/data-service/test/model/transmission.test.ts
- data-serving/data-service/test/model/travel.test.ts
- data-serving/samples/cases.json
- verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts
- verification/curator-service/ui/src/components/LinelistTable.tsx
- verification/curator-service/ui/src/components/NewCaseForm.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/NewCaseFormValues.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Transmission.tsx
Per comments & updates to spec, updating 3 fields to be lists instead of singletons:
- transmission.places
- transmission.routes
- travel.methods
(I asked for clarity on the spec on which things were lists; this should bring it in alignment with the doc)
I copied the UI for other multi-selects but have no idea what I'm doing so LMK if that needs work!
> Make transmission.places, transmission.routes, and travel.methods arrays

- data-serving/data-service/schemas/cases.schema.json
- data-serving/data-service/src/model/dictionary.ts
- data-serving/data-service/test/model/data/case.full.json
- data-serving/data-service/test/model/data/dictionary.full.json
- data-serving/data-service/test/model/dictionary.test.ts
- data-serving/samples/cases.json
- data-serving/scripts/convert-data/converters.py
- verification/curator-service/ui/src/components/LinelistTable.tsx
- verification/curator-service/ui/src/components/NewCaseForm.tsx
- Adds status field (previously missed this in the spec!)
- Renames 'provided' to 'values'
- Removes 'imputed' (we can add later if we ever need it... ontology dreams are looking far away)
> Bring symptoms and preexisting conditions up to spec with addition of status

- verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts
- verification/curator-service/ui/src/components/LinelistTable.tsx
- verification/curator-service/ui/src/components/NewCaseForm.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/NewCaseFormValues.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx
Removes locationQuery which is no longer used.
This is the beginning of the travel history section to get the framework in place. We still need to add the other travel history fields, and add a way to delete travel history sections once added.
> Add travel history to NewCaseForm

- .github/workflows/integration-tests.yml
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/geocoding/fake.ts
- verification/curator-service/api/src/geocoding/geocoder.ts
- verification/curator-service/api/src/geocoding/mapbox.ts
- verification/curator-service/api/test/cases.test.ts
- verification/curator-service/api/test/geocoding/mapbox.test.ts
The /api/cases geocoding requests now accept a `location.limitToResolution` param which allows to filter the geocode results.
This should allow parsers that know they are about a region/district/country to limit geocodes to upper regions and not end up geocoding admin3 when they wanted admin2 for example.
Verified with a modified UI that hardcoded Admin2 as the resolution that geocoding of Puri returns the region instead of the city.
With `Admin2` restriction:
Without:
Kind of hard to ensure that properly in unit tests as the fake geocoder ignores options in order to keep it dead simple, happy to make it more complex (accept options and store and expose requests for example via another http handler) if you think it's worth it.
> Add param to limit geocode to a specific resolution

- .github/workflows/case-data-update.yml
Pasting from the bug:
This problem seems to be an issue with the default nameservers on Ubuntu 18.04. It seems like Cloudflare or Google's DNS nameservers would probably work fine, but I can't figure out how to change the default nameserver in this GitHub workflow container.
Some cool background reading:
- https://stackoverflow.com/questions/60541611/mongodb-dump-fails-with-cannot-unmarshal-dns-message
- https://github.com/actions/virtual-environments/issues/798
Unfortunately none of the workarounds have worked yet (locally), including:
`sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf`
(resource in use error)
Since it seems like it could be a problem with ubuntu 18.04 specifically, I might try ubuntu-20.04, even though it's [only in …
> Another hail mary to try to get the update workflow to work

- verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts
- verification/curator-service/ui/src/components/NewCaseForm.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Events.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/FormikFields.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/NewCaseFormValues.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Transmission.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx
- Removes unnecessary ".clear()" calls in cypress test
- Consolidates formik fields into it's own file
- Unfortunately couldn't use a material date *range* picker since it is not stable yet: https://dev.material-ui-pickers.dev/demo/daterangepicker So I went with two date pickers
> Add more travel history fields

- verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
- verification/curator-service/ui/src/components/LinelistTable.test.tsx
- verification/curator-service/ui/src/components/LinelistTable.tsx
This simplifies the edit code as it is in one place instead of two and allows full edit of the case.
Also moved the errors in the linelist at the top of the page otherwise one would have to scroll further down the table to see that there was an error.
> Edit in full page instead of inline in linelist

- .github/workflows/case-data-update.yml
- data-serving/scripts/data-pipeline/convert_and_import_latest_data.sh
The real magic of this PR is in the different connection string, which is a github secret. It follows the < 3.4 connection string format here: https://www.mongodb.com/blog/post/mongodb-3-6-here-to-SRV-you-with-easier-replica-set-connections
PERHAPS without the +srv URL, it won't do a DNS lookup, and magic will happen.
Note that this format of URL requires the database name in the conn string, hence the change in the data-pipeline script.
TESTED=It works locally... but so did so many other things.
> Last-last hail mary to get the update workflow to work

- data-serving/data-service/package-lock.json
- data-serving/data-service/schemas/cases.schema.json
- data-serving/data-service/src/model/genome-sequence.ts
- data-serving/data-service/src/model/transmission.ts
- data-serving/data-service/src/model/travel-history.ts
- data-serving/data-service/src/model/travel.ts
- data-serving/data-service/test/model/data/case.full.json
- data-serving/data-service/test/model/data/genome-sequence.full.json
- data-serving/data-service/test/model/data/travel-history.full.json
- data-serving/data-service/test/model/travel-history.test.ts
- data-serving/samples/cases.json
Each commit represents a different small schema  removal:
- 'Unknown' options from enums (decided on another PR that an empty field implies this, and we can export or display absence of data as 'Unknown' as necessary)
- travelHistory.numLocations (decided Friday during design review)
- genomeSequence.notes: Consolidating into the top-level notes field (already exists)
> 3 schema removals per various conversations

- .github/workflows/case-data-update-dev.yml
- .github/workflows/case-data-update-prod.yml
Apparently there's no way to do workflow composition or inheritance so I've duplicated the logic to keep a clean dev/prod separation -- and because they need to be triggered on different things.
Right now, *prod* mainly updates when the *data* should change: nightly after the expected CSV upload, and whenever the conversion script changes.
Now *dev* will mainly update when the *schema* should change, because we don't care about the data in dev being fresh -- but we don't want our dev instance to go down because the schema doesn't match the dataserver.
Ideally, we'd really trigger these things when we trigger the binary pushes, but I believe that's blocked ATM.
TESTED=Ran it locally with `act`
> Add a case data update script for dev

- data-serving/samples/cases.json
- data-serving/scripts/setup-db/README.md
- data-serving/scripts/setup-db/package.json
- data-serving/scripts/setup-db/src/index.ts
- data-serving/scripts/setup-db/src/types/mongo-cli.d.ts
- dev/setup_db.sh
As of this change, `dev/setup_db.sh` will still drop all data from the local db, but other callers of this `setup-db` script (namely our update db workflows) will only drop imported data. This is to protect any data created via the portal, dev or prod (though we can discuss whether we want this for dev).
TESTED=I imported the sample data below, which I've modified to have 1 record that simulates coming from the new curator portal, i.e. it has no `importedCase` record. The script successfully drops the 99 "imported" documents and keeps the 
```
npm run setup-db
Read schema from ./../../data-service/schemas/cases.schema.json
Read index from ./../../data-service/schemas/cases.index.json
Connected to instance at 127.0.0.1:27017
Connected to database "covid19"
Dropped imported documents (99 …
```
> By default, drop only imported data as part of setup-db script

- verification/curator-service/ui/src/components/ViewCase.tsx
Otherwise we'd get
```
TypeError: Cannot read property 'map' of undefined
at (ViewCase.tsx:365)
...
```
> add unknown check for genome sequence details

- data-serving/data-service/src/model/revision-metadata.ts
- verification/curator-service/ui/src/components/App.tsx
- verification/curator-service/ui/src/components/Case.tsx
- verification/curator-service/ui/src/components/CaseForm.test.tsx
- verification/curator-service/ui/src/components/CaseForm.tsx
- verification/curator-service/ui/src/components/EditCase.tsx
- verification/curator-service/ui/src/components/ViewCase.test.tsx
- verification/curator-service/ui/src/components/ViewCase.tsx
- verification/curator-service/ui/src/components/common-form-fields/FormikFields.tsx
- verification/curator-service/ui/src/components/fixtures/fullCase.json
- verification/curator-service/ui/src/components/new-case-form-fields/CaseFormValues.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Events.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/GenomeSequences.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Pathogens.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Transmission.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx
Sorry got git-snipped here where I got two PRs in one somehow :(
- one does s/NewCaseForm/CaseForm everywhere
- one sets the udpateMetadata upon edits, waiting for #394 to be properly implemented to show the last editor in the details page.
> Remove "New" from NewCaseForm(Values) and send curator edits

- verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx
When something exists:
When you click on the field:
When you change:
Fixes #416
> pass down initial location nameto autocomplete field when editing a case

- verification/curator-service/ui/cypress/fixtures/fullCase.json
- verification/curator-service/ui/cypress/integration/components/EditCase.spec.ts
- verification/curator-service/ui/src/components/fixtures/fullCase.json
This is a first step towards merging the add->edit->view tests to match CUJs, it just covers checking all fields in the edit component and is now more comprehensive than unit tests.
I couldn't figure out how to match the profession but it's defiintely there... maybe later.
> Full edit checks in cypress tests

- verification/curator-service/ui/src/components/ViewCase.tsx
Also adds some buffer at the end of the page to not have the last outline match the botton of the page exactly.
FIxes #407
> fix padding of travel methods

- verification/curator-service/ui/src/components/CaseForm.tsx
Validating the entire form on every change was making the form very laggy. Now it will validate on blur and form submission, and the form is responsive again.
> Don't validate on change

- verification/curator-service/ui/src/components/LinelistTable.test.tsx
- verification/curator-service/ui/src/components/LinelistTable.tsx
While material team fixes its issues with the details icon, use our own:
fyi @axmb
> change icons in table

- verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts
- verification/curator-service/ui/src/components/CaseForm.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Events.tsx
It can have value "Unknown" which we are currently saving as undefined in the schema.
> Don't require method of confirmation

- data-serving/data-service/.eslintrc.js
- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/test/controllers/case.test.ts
- data-serving/scripts/setup-db/.eslintrc.js
- verification/curator-service/api/.eslintrc.js
- verification/curator-service/ui/.eslintrc.js
This allows bulk ingestion to check all cases prior to saving them to the DB, to avoid partial uploads.
I'm using a query param in the existing creation API, which is a [relatively canonical technique](https://google.aip.dev/163).
Spotted a conflict between our eslint config and prettier in the controller file. So including a tiny fix to our eslint configs that properly delegates indentation formatting to prettier.
> Add a validate_only param to the case creation API

- verification/curator-service/ui/src/components/BulkCaseForm.tsx
- verification/curator-service/ui/src/components/Case.tsx
Primarily need to define a type in the component to hold case data such that we can cleanly construct each case once, and reuse the object for validation and eventual submission. Cutting this as a separate PR so that the eventual surfacing of validation errors isn't too massive/dense.
See the note on the partial type I've created. I'm hoping that we eventually find cycles to label fields optional in `Case` if they're optional in the API case document.
> Create an API-ready case interface in BulkCaseForm to facilitate forthcoming validation

- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/test/cases.test.ts
Ran into this while implementing bulk upload errors.
Previously, the curator service would completely swallow the nature of the error. E.g., for validation issues it'd return something along the lines of:
```
{
code: 500
message: 'Request failed with code 422.'
}
```
Which has the downside of (1) removing helpful information as to the nature of the error (say, a specific validation issue), and (2) casts all errors (except geocoding 422s) to 500. What I've added isn't totally perfect, and assumes (probably safely) that we're satisfied with just catching errors made using axios and which received a response from the case server. But, that seems fair enough for now.
> Preserve proxied error status/data in curator case API.

- verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts
- verification/curator-service/ui/src/components/BulkCaseForm.tsx
Styling isn't perfect, and I think we'll want to aggregate errors in some situations (in lieu of truncating). But I think we'll get a lot of mileage out of this initial cut, which should suffice to begin testing.
> Display validation errors in the bulk upload form.

- ingestion/functions/parsing/common/python/input_event.json
- ingestion/functions/parsing/common/python/parsing_lib.py
- ingestion/functions/parsing/common/python/parsing_lib_test.py
- ingestion/functions/parsing/common/python/sample_data.json
- ingestion/functions/parsing/india/india.py
- ingestion/functions/parsing/india/india_test.py
- ingestion/functions/parsing/india/input_event.json
- ingestion/functions/template.yaml
Diff appears large, but it's mostly just moving code around.
The code being moved isn't optimal -- there are a number of things (in the API, and in Pythonicisms) that should be changed. As a Python expert I'm sure you'll have comments on it! Feel free to comment, or, it might simply be better to sync offline and for us to make changes in subsequent PR(s). And of course please do comment on anything that isn't a drag-and-drop.
There are a couple oddities (like the way parsers import the lib), that are mostly a function of the way AWS Lambda Layers work. The import shenanigans are specifically so that we can run pytest unit tests in addition to invoking the function locally via `sam local invoke`. [This post is a pretty good summary of what this change …
> Move reusable parsing subroutines into a common lib file/Lambda Layer

- ingestion/functions/parsing/common/python/parsing_lib.py
> Add a TODO addressing case resource documentation in parsing_lib.

- data-serving/data-service/schemas/cases.schema.json
Note that these are still validated by Mongoose in the data server so this is a no-op
> Remove enums from the mongodb json schema in favor of strings

- ingestion/functions/parsing/common/python/parsing_lib.py
- ingestion/functions/parsing/common/python/parsing_lib_test.py
- ingestion/functions/parsing/india/india.py
Not pursuing the optimization of `parsing_lib` too much just yet, but this was low-hanging fruit that I wanted to knock out.
Allows us to introduce a solid ~E2E test for the library, which is a plus.
> Add a common lib function to encapsulate Lambda handler boilerplate.

- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/geocoding/geocoder.ts
- verification/curator-service/api/src/geocoding/mapbox.ts
- verification/curator-service/api/test/cases.test.ts
- verification/curator-service/api/test/geocoding/mapbox.test.ts
Adding a feature to limit the impact of issues like #530 while we wait on resolving admin2 geocoding.
> Allow specifying multiple geocode limits/types.

- verification/curator-service/ui/src/components/bulk-case-form-fields/FileUpload.tsx
- verification/curator-service/ui/src/components/common-form-fields/FieldTitle.tsx
There isn't a mocked tooltip or copy for this, but it's a helpful stopgap while we iron out issues.
> Add a tooltip for the CSV file upload component, linking to docs.

- data-serving/data-service/api/openapi.yaml
- data-serving/data-service/test/controllers/case.test.ts
These requests & responses are now validated against the `Case` object definition in the API YAML -- and these show up in the API docs
Note that the `create` request has some required properties that the responses don't have (since legacy data might not have these properties)
Next PRs will be to flesh out the sub-props of the `Case` object
> Add the top-level properties to the case requests & responses in data service

- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/test/cases.test.ts
- verification/curator-service/ui/src/components/BulkCaseForm.tsx
This is necessary to distinguish, e.g., between creations and updates performed as a result of calling the upsert API.
Related: #539.
> Preserve status in successful requests proxied via the curator service API

- data-serving/data-service/api/openapi.yaml
- data-serving/data-service/src/model/location.ts
- data-serving/data-service/test/controllers/case.test.ts
- data-serving/data-service/test/model/data/case-reference.full.json
- data-serving/data-service/test/model/data/case-reference.minimal.json
- data-serving/data-service/test/model/data/case.full.json
- data-serving/data-service/test/model/data/case.minimal.json
- data-serving/data-service/test/model/data/location.minimal.json
- data-serving/data-service/test/model/location.test.ts
- data-serving/samples/cases.json
- verification/curator-service/ui/cypress/support/commands.ts
- verification/curator-service/ui/src/components/LinelistTable.test.tsx
- verification/curator-service/ui/src/components/ViewCase.test.tsx
- verification/curator-service/ui/src/components/fixtures/fullCase.json
Open to different names for `Case` vs. `NewCase` although I've seen this naming convention in OpenAPI examples. `NewCase` only modifies what's required, not the actual property defs.
> Add API docs for caseReference, demographics, and location props

- data-serving/data-service/api/openapi.yaml
dateRange.start and dateRange.end should be strings with the date-time format, but apparently we call it with all sorts of things so leaving it pretty loosey-goosey for now
> Document API objects for events, symptoms, pre-existing conditions, and transmissions properties

- verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts
- verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts
- verification/curator-service/ui/cypress/integration/components/Curator.spec.ts
- verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts
cy.contains('htmltag', 'text') seems to be quicker and more stable than cy.get('htmltag').contains('text')
> Hopefully de-flake cypress tests

- verification/curator-service/api/src/controllers/auth.ts
This fixes the issue by forcing the account selection prompt dialog when clicking login the first time even if there's already an account in the system.
Based on the solution proposed in https://github.com/jaredhanson/passport-google-oauth2/issues/18
Verified that it works with multi account on the same browser session now:
Fixes #486
> fix multi account login issue

- verification/curator-service/ui/cypress/integration/components/Curator.spec.ts
- verification/curator-service/ui/src/components/new-case-form-fields/Location.test.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Location.tsx
This enables curators to manually add missing admin levels for example.
Temporary unblock #426.
This PR follows #595.
> Make location fields editable

- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/test/cases.test.ts
Re: #571 
This was a little tricky, due to geocoding happening on the curator service, but I think this is the best balance of clarity and efficiency. It might be somewhat better if we moved geocoding to the data service, but that's a separate thread. For now, orchestrating this work in the curator service API, taking advantage of the batchValidate endpoint I'd added to the data service API.
The plan is to migrate the bulk upload UI to use this endpoint, and likely to use it from parsing functions as well. I think this should more or less fix the aforementioned issue (since the bulk of the slowdown seemed to be network latency between clients/our server), but there are a couple TODOs with improvements should we need them.
> Add a batchUpsert endpoint in the curator service case API.

- verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts
- verification/curator-service/ui/src/components/new-case-form-fields/Location.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/LocationForm.tsx
The new button when clicked opens the location form with all fields editable below and the button disappears.
Also added the name field to the location fields to be able to tune whatever mapbox returns and also because that's a required field so we have to have a way to specify it manually.
Last small nit fix: make all fields input label shrink for consistency (they were all shrunck except geoResolution).
> Add ability to specify arbitrary geocode from scratch

- verification/curator-service/api/src/index.ts
Verified locally that we only got 1 session stored upon login instead of 20 (!).
Dev had 125k sessions in mongo (!!), I cleared them you'll have to relogin there.
> Saner session settings

- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/controllers/sources.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/test/cases.test.ts
- verification/curator-service/api/test/geocoding/fake.test.ts
- verification/curator-service/api/test/sources.test.ts
- verification/curator-service/api/test/users.test.ts
- Fixed the issue where requests & responses weren't being validated because we needed to await installing the OpenAPI validator in `index.ts`
- Added the endpoints that were missing from the OpenAPI spec
- Fixed incorrect requests/response definitions in the spec
- Fixed tests using incorrect requests/responses
- Left TODOs in the OpenAPI spec where things need to be.... spec'ed (which I'll be doing next)
- Cried
> Enable request & response validation in curator service

- data-serving/data-service/src/index.ts
- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/test/cases.test.ts
- verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts
- verification/curator-service/ui/src/components/BulkCaseForm.tsx
Not including the OpenAPI spec tweaks just yet -- I'll merge/write that commit after #604 is in.
Did some light testing with 1,000 rows of Ohio data:
- Under ideal conditions (my Linux machine, serving on localhost) it's a ~7X speed up.
- Under more realistic deployed conditions (as above, but with an induced 100ms network latency) it's a ~31X speed up.
Highly dependent on the number of cases used of course, since it's a scaling change, but this should make it tractable to submit thousands of cases via bulk upload. That previously took several minutes for low thousands, and hours for many tens of thousands (which was effectively impossible, since at least one request was likely to encounter an error).
> Use the new batchUpsert API in the bulk case upload component

- .gitignore
- verification/scripts/boundaries.sh
Mapbox sales gave us access to 3 files for boundaries that contain the IDs and the names (amongst many other things) of the boundaries returned when doing a tilequery lookup for a point (Cf. other PR I sent you earlier).
These files shouldn't become public as per Mapbox terms of service, so we need to put them as config maps in kubernetes and the curator service will then be able to access them from there.
Before doing that though we need to optimize them a bit because 99% of the stuff in there is useless to us.
Before:
```
du -hs ~/Downloads/boundaries-adm*
1.6M	/Users/timothe/Downloads/boundaries-adm1-v3.json
20M	/Users/timothe/Downloads/boundaries-adm2-v3.json
36M	/Users/timothe/Downloads/boundaries-adm3-v3.json
wc -l ~/Downloads/boundaries-adm*
3915 …
```
> Add script to generate boundaries files that is optimized for serving

- verification/curator-service/api/src/geocoding/adminsFetcher.ts
- verification/curator-service/api/src/geocoding/geocoder.ts
- verification/curator-service/api/src/geocoding/mapbox.ts
- verification/curator-service/api/test/geocoding/adminsFetcher.test.ts
- verification/curator-service/api/test/geocoding/mapbox.test.ts
This is step 1/2: it gets the admins but not their name so not filling this in just yet in the geocode results.
Getting the names is going to be slightly complex due to the way mapbox gives it to us (not via an API but via static files (!)) so I'll do that in a next PR.
For #426
> Add admins fetcher using mapbox boundaries API

- aws/curator-ingress.yaml
This prevents 413s and 504s for large batch requests.
We're still getting 500 after a minute (`socket hang up`), but I believe that's a node issue as opposed to nginx.
> Increase allowable body size, and increase response timeout, for curator ingress

- verification/curator-service/api/src/geocoding/README.md
- verification/curator-service/api/src/geocoding/adminsFetcher.ts
- verification/curator-service/api/src/geocoding/geocoder.ts
- verification/curator-service/api/src/geocoding/mapbox.ts
- verification/curator-service/api/test/geocoding/adminsFetcher.test.ts
- verification/curator-service/api/test/geocoding/mapbox.test.ts
Turns out administrative areas are hard [citation needed], we were previously trying to guess them from the geocode feature context but it was mostly wrong past the admin 1, admin 2 and admin 3 definitions depend on countries (for example Brasil doesn't have an admin 3, UK has "country" as admin 1, county as admin 2, etc. It's a mess and we can't just try to get the feature type "region" for admin 1, "district" for admin2 etc as we were trying to do before.
From now on we'll rely on the mapbox boundaries API which has very decent coverage and give us correct results.
Just check out https://www.mapbox.com/boundaries/#coverage-map and visit various countries to see how many different admin level -> meaning there are. I realized that looking at that page, hence this PR.
Also:
- reorder …
> Use only boundaries API admin areas 

- .github/workflows/case-data-update-dev.yml
- .github/workflows/case-data-update-prod.yml
- data-serving/scripts/convert-data/convert_data.py
- data-serving/scripts/convert-data/converters.py
- data-serving/scripts/data-pipeline/convert_and_import_latest_data.sh
- verification/curator-service/api/openapi/openapi.yaml
Required a small fix in our data converter (wrong event name) -- found a couple other small things to fix along the way
> Make the event names in the curator OpenAPI spec an enum

- verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts
- verification/curator-service/ui/src/components/BulkCaseForm.test.tsx
- verification/curator-service/ui/src/components/BulkCaseForm.tsx
Broadly:
- Adds header title/blurb
- Adds cancel button
- Adds in-progress copy
- Lays out the page per spec
This PR doesn't include a couple elements that'll end up linking to local files, nor does it address some common elements that aren't quite to spec (like typography, or the form elements).
> Bring the bulk form layout to ~spec

- data-serving/data-service/package-lock.json
- data-serving/data-service/package.json
- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/util/search.ts
- data-serving/data-service/test/util/search.test.ts
For #679
This makes use of https://www.npmjs.com/package/search-query-parser which is a zero-dependency parser that does what we want AFAICT. I'm happy to not have to write such a common parser/tokenizer, next step is to specify keywords and modify the mongo query accordingly.
> add basic search query parser

- data-serving/scripts/data-pipeline/README.md
- data-serving/scripts/data-pipeline/convert_and_import_latest_data.sh
The connection strings for the cron contain the db in the path, which they have to because of how they're structured; I forgot about that and didn't have it as an arg when running it locally, thought I was smart to add it in the script, and was not.
> Fix bug in conversion pipeline

- data-serving/data-service/api/openapi.yaml
- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/index.ts
- data-serving/data-service/test/controllers/case.test.ts
Primary goal here is to make the bulk upsert MongoDB invocation more efficient.
In pursuit of avoiding a super large/dense PR, I'm cutting this at what's _sort of_ an intermediate state. Rather than expose this endpoint directly in a subsequent PR, I'll probably wrap it together with the existing batchValidate method before doing so (in that same PR). Happy to hear thoughts on this.
> Add batchUpsert method to data service case API

- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/test/controllers/case.test.ts
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/test/cases.test.ts
- verification/curator-service/ui/src/components/BulkCaseForm.tsx
Results in a 3-4X speed-up locally. Expecting the speed up in dev to be appreciably larger, given the appreciable increase in latency. Due to (what I think will be) an expensive query in the data service `batchUpsert` call, I think adding an index to support the query will further improve the performance. But, will send this change off to dev first in order to measure the impact of that index.
> Use the data service batchUpsert endpoint in the curator API.

- ingestion/functions/parsing/india/india_test.py
Instead of relying on the presence of a /tmp dir
> use tempfile in india parsing tests

- verification/curator-service/api/src/geocoding/adminsFetcher.ts
- verification/curator-service/api/test/geocoding/adminsFetcher.test.ts
Admins can now be undefined but the checks were only for empty strings so admins were not fetched when providing undefined admins.
> Fix check for empty admin areas

- verification/curator-service/ui/src/components/LinelistTable.tsx
The LinelistTable component is re-rendered on every state change and each keystroke into the search bar caused a state change. This led to a 2-3 second lag on each keystroke in the search bar (the table is very expensive to render). By pulling the search bar out into it's own component the LinelistTable is only re-rendered after hitting enter in the search bar, when we want the table to update to show the search results.
> Improve performance of search bar in linelist

- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
Tested locally after adding a source in the UI:
```
SOURCE_API_URL=http://localhost:3001/api sam local invoke "RetrievalFunction" -e retrieval/valid_scheduled_event.json --docker-network=host
Invoking retrieval.lambda_handler (python3.6)
Failed to download a new amazon/aws-sam-cli-emulation-image-python3.6:rapid-1.0.0 image. Invoking with the already downloaded image.
Mounting /Users/timothe/healthmap/healthmap-gdo-temp/ingestion/functions/.aws-sam/build/RetrievalFunction as /var/task:ro,delegated inside runtime container
05 Aug 2020 15:13:05,298 [INFO] (/var/runtime/awslambda/bootstrap.py) main started at epoch 1596640385298
05 Aug 2020 15:13:09,304 [INFO] (/var/runtime/awslambda/bootstrap.py) init complete at epoch 1596640389305
START RequestId: 97982b06-b371-1cd5-e7d9-964b738db44d …
```
> support csv in retrieval lambda

- data-serving/data-service/api/openapi.yaml
- verification/curator-service/ui/src/components/new-case-form-fields/Demographics.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Events.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx
- verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx
Since the values can't be extracted from the openAPI, we'll need to define the lists in two places anyways. So there's no harm in defining the lists in the UI rather than the API and removes the need for several more HTTP requests.
> Add openAPI validation on select fields and remove TODOs

- data-serving/data-service/src/controllers/case.ts
This option allows for (theoretically) better parallelization for our bulk work.
Difference is pretty slight locally, but might be more perceptible in Atlas.
> Specify unordered for the batchUpsert bulk write operation.

- .github/workflows/case-data-export-prod.yml
- data-serving/scripts/export-data/export_data.sh
The secret I'm using is my own PAT (with public_repo scope), and we should transition this to one of the future maintainers after I confirm this works
I tested it locally with `act` but it probably won't work the first time. Never has, never will!
```
act -j export-case-data-prod -P ubuntu-latest=nektos/act-environments-ubuntu:18.04-full -s DB_CONNECTION_URL=<CONN_STRING> -s EXPORT_DATA_ACCESS_TOKEN=<GITHUB_TOKEN>
```
> Workflow to export prod db data daily and commit to repo

- data-serving/data-service/src/index.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/test/geocoding/adminsFetcher.test.ts
https://mongoosejs.com/docs/deprecations.html
> Use Mongoose useCreateIndex option to prevent deprecation warnings.

- data-serving/data-service/api/openapi.yaml
- data-serving/data-service/schemas/cases.schema.json
- data-serving/data-service/src/model/case-reference.ts
- data-serving/data-service/test/model/data/case-reference.full.json
- data-serving/data-service/test/model/data/case-reference.minimal.json
- data-serving/data-service/test/model/data/case.full.json
- verification/curator-service/api/openapi/openapi.yaml
Not making it required, for now. We could consider requiring this, and having it be ~unused for manual (and perhaps bulk) entry, but doesn't seem worthwhile at the moment.
> Add upload ID to the case data model

- ingestion/functions/parsing/common/python/parsing_lib/input_event.json
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
- ingestion/functions/parsing/hongkong/input_event.json
- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/model/automation.ts
- verification/curator-service/api/src/model/date-filter.ts
- verification/curator-service/api/src/model/source.ts
- verification/curator-service/api/test/model/data/automation.full.json
- verification/curator-service/api/test/model/data/date-filter.full.json
- verification/curator-service/api/test/model/data/source.full.json
- verification/curator-service/api/test/model/date-filter.test.ts
- verification/curator-service/ui/cypress/integration/components/SourceTableTest.spec.ts
- verification/curator-service/ui/src/components/SourceTable.test.tsx
- verification/curator-service/ui/src/components/SourceTable.tsx
For #744 
Wanted to do this in two PRs but I ended up merging the UI in here by accident sorry about that :( I hope you don't mind reviewing this whole together (might make more sense actually).
- The UI bit is adding 2 columns in the sources table, the cypress tests refuse to pass I have no idea why I tried everything really... but it seems that one can't select the last column whatever I do to it (I tried moving the JSON/CSV bit there and it fails as well so it seems position-related...). I verified that one could add/edit/remove date filter options locally though.
- The API bit is moving the dateFilter in the source model instead of automation as we also want to be able to run on specific dates without being automated (for testing for example and before setting up automation).
> Implement filtering of dates in parsing lib and add date filter columns to the UI

- ingestion/functions/parsing/ch_zurich/input_event.json
- ingestion/functions/parsing/ch_zurich/zurich.py
- ingestion/functions/parsing/ch_zurich/zurich_test.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/retrieval/retrieval.py
The dates filtering code expects the dates to be formatted in a certain way, the zurich parser wasn't producing them accordingly (they were understandable by JS on the backend but not by the python code).
Also logs received event that should help debugging.
Confirmed that the date filtering now works as expected.
> Fix typo in event param and handle dates consistently

- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
- verification/curator-service/api/openapi/openapi.yaml
Doesn't include error handling, which'll be a separate PR (I'll base the branch off this PR). Tested locally with `india` parser.
Some autofmt changes included (I have `autopep8` as my configured Python formatter in vscode).
>  Add happy-path upload API usage to parsing_lib.

- verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts
- verification/curator-service/ui/cypress/integration/components/Curator.spec.ts
- verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
- verification/curator-service/ui/src/components/AppModal.tsx
- verification/curator-service/ui/src/components/LinelistTable.test.tsx
- verification/curator-service/ui/src/components/LinelistTable.tsx
Moves edit and delete within a three-dot menu. The details view can be accessed by clicking anywhere on the row. 
I don't think the three-dot menu can be moved to the left of the checkboxes until https://github.com/mbrn/material-table/issues/2317 is fixed.
> Move table actions to spec-ed locations

- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/retrieval/retrieval.py
Addresses two issues:
1. If we don't receive a 2xx from the server, we can't be sure the response contains json (and `res.json()` will fail with a decoding error).
2. If something goes _truly_ wrong in `requests.$verb([...])`, it's possible `r/res` will be None.
> Make error checking (type-) safer in parsing/retrieval.

- verification/curator-service/ui/src/components/App.tsx
- verification/curator-service/ui/src/components/LinelistTable.tsx
This is what I meant, sorry I wasn't clear last time. Concensus on the internet seems to favor Link or NavLink vs accessing the history object directly. The internet is never wrong, obviously!
https://stackoverflow.com/questions/51116747/react-router-link-vs-redirect-vs-history
https://www.lorenzweiss.de/common_mistakes_react_hooks/#2-using-routerpush-instead-of-a-link
etc
> use links instead of pushing to the history whenever possible

- .github/workflows/integration-tests.yml
- verification/curator-service/ui/package.json
Fixes #776 
Haven't looked into edge yet, it's not bundled with ubuntu by default (figures...) so we'd need to spin a windows VM, will look into that next.
> Use cypress action to run on firefox and chrome in parallel

- data-serving/scripts/export-data/export_data.sh
My b-- introduced a bug in #806 that caused the workflow to fail on CSV (that's what I get for only testing with JSON)
Apparently the CSV export doesn't mind an extra --jsonArray flag, but it *does* mind an empty string.
> Fix bug with csv format command in export_data.sh

- ingestion/functions/template.yaml
For #810 
Deploy script [fails](https://github.com/globaldothealth/list/runs/997734463?check_suite_focus=true) with 
```
Lambda was unable to   
configure your         
environment variables  
because the            
environment variables  
you have provided      
contains reserved keys 
that are currently not 
supported for          
modification. Reserved 
keys used in this      
request:               
AWS_SESSION_TOKEN
```
Cf. https://seed.run/docs/serverless-errors/lambda-was-unable-to-configure-your-environment-variables.html
I removed the ovverride from the template.yaml and I could run the functions locally just fine.
> remove reserved env var override

- .github/workflows/ingestion-aws-sam-deploy.yml
Apologies for any commit churn. Not feasible to test this locally with `act`.
(Checks aren't run on this final commit, since it isn't against `main`, but you can view previous successful runs in the Checks tab.)
> Use the sam CLI, now installed by default in action images, to sam deploy pushes to main

- verification/curator-service/ui/src/components/CaseForm.tsx
- verification/curator-service/ui/src/components/util/date.tsx
The datepicker returns dates in the local timezone, which can then show up as the wrong date in UTC. So here we convert all dates to UTC (maintaining the current date values) before submitting.
> Switch dates to UTC before submitting

- ingestion/functions/README.md
- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
We could also abstract python away and provide our own $YEAR, $MONTH, $DAY params instead but I am not sure the added indirection is worth doing just yet.
Fixes #831
> Format source URLs with strftime

- verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
Passes 50-out-of-50 locally.
Based on cursory research, seems that `wait`'ing on parallel, identical requests is a common pain point. There's various hacks around it, but I think specifying the precise route is probably the clearest.
I'm not sure why we haven't run into this in the (very similar) delete test case. Perhaps those requests are slower, such that Cypress's XHR handler consistently catches them all.
> Work around Cypress difficulties awaiting fast, identical, wildcard requests

- .github/workflows/case-data-export-prod.yml
- .github/workflows/case-data-update-dev.yml
Workflows have been failing because MongoDB 4.4 split a package into to; 4.4 is installed by default on these images but we need 4.2
Failed workflow: https://github.com/globaldothealth/list/runs/1020205741?check_suite_focus=true
Error:
```
dpkg: error processing archive /var/cache/apt/archives/mongodb-org-tools_4.2.6_amd64.deb (--unpack):
trying to overwrite '/usr/bin/install_compass', which is also in package mongodb-org-database-tools-extra 4.4.0
E: Sub-process /usr/bin/dpkg returned an error code (1)
##[error]Process completed with exit code 100.
```
> Remove conflicting packages during mongo install in workflows

- .github/workflows/case-data-export-prod.yml
- .github/workflows/case-data-update-dev.yml
This time the error was:
```
dpkg: dependency problems prevent removal of mongodb-org-database-tools-extra:
mongodb-org-tools depends on mongodb-org-database-tools-extra.
```
https://github.com/globaldothealth/list/runs/1025080844
> Attempt 2 at fixing mongodb installs for workflows

- verification/curator-service/ui/src/components/LinelistTable.tsx
Before:
After: 
I removed the search icon because when used as a start adornment the UI became what it was apparently that's a bug :(
Also moved the tooltip to a separate portion of the UI after the search bar so that we can have the X to clear input in it I think it's cleaner:
> fix search bar ui

- aws/curator.yaml
- ingestion/functions/common/common_lib.py
- ingestion/functions/common/common_lib_test.py
- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
- ingestion/functions/retrieval/valid_scheduled_event.json
- verification/curator-service/api/src/clients/aws-events-client.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/src/util/validate-env.ts
- verification/curator-service/api/test/clients/aws-events-client.test.ts
This covers:
- Creating the env var in our AWS deployment(s).
- Supplying it as JSON in our scheduled CloudWatch events.
- Using it to determine G.h API URL in retrieval.
Next step is using it in the parsing_lib, and removing references to the legacy os.environ param.
Handful of files impacted, but the commits should be nice logical chunks if you'd like to review that way.
To expand on the overall approach:
I'd considered doing full separation of serverless resources between environments. The "right" way to do that with AWS is to create separate CloudFormation stacks for each environment (using aliases to do it isn't recommended). It'd add a fair bit of cognitive overhead and complexity -- just didn't seem worth the payoff, given that there's no real resource separation advantage, since …
> Determine G.h environment in parsing functions via an env input parameter

- aws/curator.yaml
WIthout this kind of access we get:
```
The Deployment "curator-dev" is invalid: spec.template.spec.containers[0].env[0].valueFrom.fieldRef.fieldPath: Invalid value: "metadata.labels.environment": error converting fieldPath: field label not supported: metadata.labels.environment
```
when trying to apply the change
> fix environment label reference

- verification/curator-service/api/src/model/date-filter.ts
- verification/curator-service/api/test/model/date-filter.test.ts
- verification/curator-service/ui/src/components/SourceTable.tsx
This chokes up parsing, since dateFilter [isn't falsey](https://github.com/globaldothealth/list/blob/main/ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py#L116), but it also doesn't contain necessary fields.
> Don't populate source dateFilters unless we really want them

- ingestion/functions/README.md
- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
- ingestion/functions/retrieval/valid_scheduled_event.json
Fixes #880
Bonus points: this makes us independent of python date formatting directives in our sources URL so if we ever switch to a different language for our retrieval lambda the source URLs will still work.
> fix URL mangling due to date directives being incorrectly applied

- ingestion/functions/README.md
- ingestion/functions/retrieval/retrieval.py
Fixes #867 
FYI the code could be _slightly_ simpler if we didn't write the output file in chunks, but if we don't the lambda times out because decoding takes too long.
Test methodology:
- pytest passes (encoding is "ascii" in tests)
- downloaded the Peru csv:
```
file -I positivos_covid.csv
positivos_covid.csv:                         text/plain; charset=iso-8859-1
```
Ran the retrieval function locally with the changes in this PR built-in:
```
...
Requesting source configuration from http://localhost:3001/api/sources/5f48e71090ac8000280d2d9d
Received source API response: {'_id': '5f48e71090ac8000280d2d9d', 'name': 'Peru', 'origin': {'_id': '5f48e71090ac8000280d2d9e', 'url': 'https://cloud.minsa.gob.pe/s/Y8w3wHsEdYQSZRp/download'}, 'format': 'CSV', 'uploads': [{'created': …
```
> encode all downloaded sources as utf-8

- .github/workflows/case-data-export-prod.yml
We were seeing errors like:
```
Create gzip of CSV and JSON prod case data0s
##[error]Process completed with exit code 2.
Run python3 data-serving/scripts/export-data/export.py -mongodb_connection_string "***" --format csv
usage: export.py [-h] [--mongodb_connection_string MONGODB_CONNECTION_STRING]
[--collection COLLECTION] [--fields FIELDS]
[--format {csv,json}]
export.py: error: argument --fields: can't open 'case_fields.yaml': [Errno 2] No such file or directory: 'case_fields.yaml'
##[error]Process completed with exit code 2.
```
> fix prod export by pointing to case_fields.yaml file

- ingestion/functions/parsing/ch_zurich/zurich.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
- ingestion/functions/parsing/hongkong/hongkong.py
- ingestion/functions/parsing/india/india.py
- ingestion/functions/parsing/japan/japan.py
- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
Instead of checking for a magic string that can break anytime, that also makes it feasible with the new indent to ran autopep8 formatter automatically and it won't mistakenly move the failing imports above the others.
> try catch imports that need sys path to be changed locally

- data-serving/data-service/api/openapi.yaml
- data-serving/data-service/src/model/case-reference.ts
- data-serving/data-service/test/model/case-reference.test.ts
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
- verification/curator-service/api/openapi/openapi.yaml
Required for #891. This prevents a case from appearing modified if it's been previously verified by a curator, and no new data is found in the ADI run.
This unfortunately won't set a case to `UNVERIFIED` if new information is found in an update, which might be nice, but I'd reckon that the vast majority of upserts of existing cases will _not_ contain new information (so this behavior is desirable), and that searching for verified cases within an upload is a reasonable workaround.
> Make verificationStatus default to UNVERIFIED.

- verification/curator-service/ui/cypress.json
https://docs.cypress.io/guides/guides/screenshots-and-videos.html#Video-encoding
Also not saving videos when test passes.
Apparently now taking around 11 min instead of 15 that I used to see.
> faster cypress by not compressing videos

- ingestion/functions/retrieval/retrieval.py
Requests follows the redirects by default https://requests.readthedocs.io/en/master/user/quickstart/#redirection-and-history so we shouldn't get a 301 explicitely unless I missed something?
> remove todo about 301 in retrieval func

- verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts
- verification/curator-service/ui/cypress/integration/components/Curator.spec.ts
- verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts
- verification/curator-service/ui/cypress/integration/components/UploadsTableTest.spec.ts
- verification/curator-service/ui/src/components/ViewCase.test.tsx
- verification/curator-service/ui/src/components/util/date.test.tsx
- verification/curator-service/ui/src/components/util/date.tsx
Don't know about you but single digit day or months look incomplete to me.
Notice how I am *not* using any leftpad library to do that, pure magic.
https://en.wikipedia.org/wiki/Npm_(software)#Notable_breakages
> zero pad month and day when rendering dates

- ingestion/functions/README.md
- ingestion/functions/common/common_lib.py
- ingestion/functions/common/common_lib_test.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
- ingestion/functions/retrieval/valid_scheduled_event.json
- verification/curator-service/api/openapi/openapi.yaml
First step for #754, will tackle the parsing functions next.
This also includes a quick fix for the utf-8 encoding of sources, turns out one cannot just "decode" utf-8 into a utf-8 file if there are surrogates already present, instead if the source is already utf-8 I just dump it as is, no need to do the decoding/reencoding step that's simpler and faster and we just get the raw source as is this way. (Noticed the issue when trying on Estonian data source).
> make local runs of ingestion functions able to register a user and use it

- verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
- verification/curator-service/ui/src/components/LinelistTable.tsx
I made it so that you could only select all rows across pages if there is a search query. So the action buttons can always be present.
> Allow toggling verification status for rows across pages

- ingestion/functions/common/common_lib.py
- ingestion/functions/common/common_lib_test.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
`finalize_upload` was calling `finalize_upload` if it failed to finalize the upload. nope.
Also removes TODO handling of `res.json().errors` field as well as the text is contained in the runtime exception we throw in each case or the API just doesn't provide fine grained errors like this (uploads API for example).
> do not loop endlessly on error-writing failure

- ingestion/functions/retrieval/retrieval.py
- verification/curator-service/api/src/clients/aws-lambda-client.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/test/clients/aws-events-client.test.ts
- verification/curator-service/api/test/clients/aws-lambda-client.test.ts
Missed that during your PR review, the invoke() call that builds the event must also pass in an env key.
Also logging the whole event when we fail to get a required key to figure out what's going on more easily.
> Add env as required var when invoking lambda from ui

- data-serving/data-service/api/openapi.yaml
- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/controllers/preprocessor.ts
- data-serving/data-service/test/controllers/case.test.ts
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
- ingestion/functions/parsing/hongkong/input_event.json
- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/test/cases.test.ts
- verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts
- verification/curator-service/ui/src/components/BulkCaseForm.tsx
- verification/curator-service/ui/src/components/UploadsTable.tsx
Slight change in behavior for post-bulk-upload, which I broached with Aaron/Shroo.
On a minor note, we're saving one query in the nominal case for ADI (batchUpsert with many existing cases), which seems to shave off about 10-15% of the total time.
> Return counts, with true modification numbers, from batchUpsert

- ingestion/functions/retrieval/retrieval.py
Otherwise Japan source would be guessed as ascii while it is utf-8 really.
Before: `Source encoding is presumably {'encoding': 'ascii', 'confidence': 1.0, 'language': ''}`
After: `Source encoding is presumably {'encoding': 'utf-8', 'confidence': 0.99, 'language': ''}`
> read more data to guess encoding

- verification/curator-service/api/src/clients/aws-events-client.ts
- verification/curator-service/api/test/clients/aws-events-client.test.ts
Prior to this, editing a source in SourcesTable (one that was configured for automation) would fail with an exception from AWS. Because setting permissions for a Lambda function is a create operation (as opposed to say put, as in putTargets, which doesn't suffer from this problem), it throws an error if the requested permission exists.
> Catch 409 errors adding invocation permissions to allow source editing.

- data-serving/data-service/api/openapi.yaml
- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/test/controllers/case.test.ts
- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/test/cases.test.ts
- verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts
- verification/curator-service/ui/src/components/App.tsx
- verification/curator-service/ui/src/components/LinelistTable.tsx
Fixes #937
This also makes the linelist visible to admins so that they can issue the delete call from there.
I did not give them more permissions other than delete (for example edit/verify is not granted).
> Limit num of deletable cases to 10K for curators with no limit for admins

- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/test/controllers/case.test.ts
- data-serving/scripts/setup-db/src/index.ts
- data-serving/scripts/setup-db/src/types/mongo-cli.d.ts
- verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
Mongo docs about collation: https://docs.mongodb.com/manual/reference/collation/
+ simple
- mongoose doesn't allow to set collation when creating indexes, we do not use mongoose to create collections so we can't set the default collation that way either.
- no way to do case-sensitive matches (but did we want that really? I don't think so)
- we have to run the setup-db which drops indexes created by mongoose when server starts so it requires a restart of the prod/dev jobs once done.
For #925
> create all indexes with default collation set for case insensitivity

- verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
- verification/curator-service/ui/cypress/integration/components/UsersTest.spec.ts
- verification/curator-service/ui/src/components/LinelistTable.tsx
- verification/curator-service/ui/src/components/SourceTable.tsx
- verification/curator-service/ui/src/components/UploadsTable.tsx
- verification/curator-service/ui/src/components/Users.test.tsx
- verification/curator-service/ui/src/components/Users.tsx
> Move pagination bar to the top of the tables

- data-serving/data-service/schemas/cases.indexes.json
- data-serving/data-service/src/model/demographics.ts
- data-serving/data-service/src/model/location.ts
- data-serving/data-service/src/model/pathogen.ts
- data-serving/data-service/src/model/revision-metadata.ts
- data-serving/scripts/setup-db/src/index.ts
Had to revert to this because there is no way to update an existing collection after it's created to properly setup the default collation as I attempted in my previous PR.
This way we can drop the indexes and recreate them as does the setup-db script and we don't have to touch the collection itself.
For #925
> Define all case insensitive text keyword indexes in index schema instead of relying on mongoose

- ingestion/functions/README.md
SAM template and `local invoke` calls do not allow for specifying volume mounts that we could have used to store the results locally instead of on s3. Remove the TODO about this in the README and welcome PRs if people want to use something else than S3 in the future.
Fixes #754
> Remove todo about not using s3 for ingestion functions

- data-serving/data-service/src/server.ts
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/server.ts
This is a little heavy-handed, but I can dial it back to the right level if this works.
Trying to debug #961 (which I can't repro locally), so casting a wide net at first.
> Don't set HTTP timeouts.

- ingestion/functions/README.md
- ingestion/functions/parsing/ch_zurich/input_event.json
- ingestion/functions/parsing/ch_zurich/zurich.py
- ingestion/functions/parsing/ch_zurich/zurich_test.py
- ingestion/functions/parsing/common/python/parsing_lib/input_event.json
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
- ingestion/functions/parsing/india/india.py
- ingestion/functions/parsing/india/india_test.py
- ingestion/functions/parsing/japan/japan.py
- ingestion/functions/parsing/japan/japan_test.py
- ingestion/functions/retrieval/valid_scheduled_event.json
For #961 
Overall feels much efficient than storing the whole list in memory in multiple places.
> Send parsed cases in batches to avoid OOMs and ease lambda memory usage

- ingestion/functions/template.yaml
Note: the json input file is 30Mb (as of today, still growing of course), there is no way to stream this in unfortuantely as the object that it contains is an array of cases :(
They do not have a csv as an alternative format.
When ran locally the function was just timing out on json.load(f) with no logs.
After increasing the memory to 512Mb it worked.
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-memorysize
#961
> increase memory of japan parsing func

- ingestion/functions/template.yaml
A timeout of 900 is the "default" (in that Lambdas are terminated after 900 seconds). It's probably worthwhile to declare it, so that our behavior doesn't implicitly change if AWS defaults are tweaked in the future.
> Move common parsing template values into Globals.

- data-serving/data-service/api/openapi.yaml
- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/index.ts
- data-serving/data-service/test/controllers/case.test.ts
- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
- verification/curator-service/ui/src/components/LinelistTable.tsx
Fixes #909
The download option for selected rows is in the table toolbar, whereas the download button next to the search bar will always download all cases matching the search result.
Changes download requests from GET to POST. This is to allow for a request body so that many caseIds can be sent in the request.
> Add a download option for selected rows

- README.md
- ingestion/functions/retrieval/retrieval_test.py
- verification/curator-service/api/src/controllers/sources.ts
- verification/curator-service/api/src/controllers/users.ts
- verification/curator-service/api/src/model/origin.ts
- verification/curator-service/api/test/model/data/source.minimal.json
- verification/curator-service/api/test/sources.test.ts
- verification/curator-service/ui/cypress/integration/components/AutomatedSourceForm.spec.ts
- verification/curator-service/ui/cypress/support/commands.ts
- verification/curator-service/ui/src/components/AutomatedSourceForm.tsx
- verification/curator-service/ui/src/components/SourceTable.test.tsx
- verification/curator-service/ui/src/components/SourceTable.tsx
Not making the origin.license field mandatory as it is not possible to specify it in the bulk/manual entry flow (yet).
This PR however includes the license in a few more tests just to be more realistic, also calls lean() on users and sources listing, somehow we forgot to do that but we do for cases.
For #972
> Make specifying a license mandatory for automatic ingestion sources

- ingestion/functions/common/common_lib.py
- ingestion/functions/common/common_lib_test.py
- ingestion/functions/parsing/brazil_amapa/amapa.py
- ingestion/functions/parsing/brazil_amapa/amapa_test.py
- ingestion/functions/parsing/brazil_paraiba/paraiba.py
- ingestion/functions/parsing/brazil_paraiba/paraiba_test.py
- ingestion/functions/parsing/ch_zurich/zurich.py
- ingestion/functions/parsing/ch_zurich/zurich_test.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
- ingestion/functions/parsing/estonia/estonia.py
- ingestion/functions/parsing/estonia/estonia_test.py
- ingestion/functions/parsing/hongkong/hongkong.py
- ingestion/functions/parsing/hongkong/hongkong_test.py
- ingestion/functions/parsing/india/india.py
- ingestion/functions/parsing/india/india_test.py
- ingestion/functions/parsing/japan/japan.py
- ingestion/functions/parsing/japan/japan_test.py
- ingestion/functions/parsing/peru/peru.py
- ingestion/functions/parsing/peru/peru_test.py
- ingestion/functions/parsing/thai/thai.py
- ingestion/functions/parsing/thai/thai_test.py
- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
Basically ran autopep8 and `python3 -m flake8 **/*.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics` on the ingestion dir, it seems that we have a CI for that but it doens't error out when errors are encountered:
https://github.com/globaldothealth/list/runs/1100557888?check_suite_focus=true
I'd love to have an autopep8 pre-commit hook as well as we do for the typescript code, will look into that.
> fix all flake8 issues

- verification/curator-service/api/src/clients/email-client.ts
- verification/curator-service/api/test/clients/email-client.test.ts
I liked the static factory pattern better, but it was a nightmare to test with Jest, given our relatively high fidelity app/controller tests. Because we don't await app async set up in our superagent controller tests, I needed to mock the `email-client` module (reaching the test SMTP server was too slow, and our unit tests ran before the source controller finished installation). And mocking an ES6 class (via the module mocker, because we can't touch the actual client prototype in the unit test) with a static factory method proved difficult.
> Testability changes to EmailClient.

- ingestion/functions/template.yaml
For #1016
Deployed that new version and tried out a retrieval, it worked this time without the memory error.
> bump memory of retrieval function

- verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts
- verification/curator-service/ui/src/components/App.tsx
Fixes #1020
Rationale:
- we should have a proper homepage instead
- doesn't show up when in incognito mode
- charts are potentially expensive until we figure out proper indexes for them (#790)
> do not show charts on homepage for non curators or admins

- dev/README.md
- dev/make_superuser.sh
- ingestion/functions/README.md
- ingestion/functions/common/common_lib.py
- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/src/model/user.ts
- verification/curator-service/api/test/cases.test.ts
- verification/curator-service/api/test/model/user.test.ts
- verification/curator-service/api/test/users.test.ts
- verification/curator-service/auth.md
- verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts
- verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
- verification/curator-service/ui/cypress/integration/components/ProfileTest.spec.ts
- verification/curator-service/ui/cypress/integration/components/UsersTest.spec.ts
- verification/curator-service/ui/cypress/support/commands.ts
- verification/curator-service/ui/src/components/App.tsx
- verification/curator-service/ui/src/components/LinelistTable.test.tsx
- verification/curator-service/ui/src/components/Profile.test.tsx
- verification/curator-service/ui/src/components/Profile.tsx
- verification/curator-service/ui/src/components/Users.test.tsx
- verification/scripts/README.md
Fixes #1025 
I will remove the reader roles from existing users with the mongo shell command:
`db.users.updateMany({}, {$pull: {roles: 'reader'}})`
so that updates pass validation.
> remove reader from roles, all logged-in users can now see the linelist and sources

- aws/curator.yaml
- verification/curator-service/api/src/util/validate-env.ts
Tried to reload dev today but it failed because the env vars weren't defined.
Just setting them to empty for now until a proper account is available.
> fix email env vars in dev

- ingestion/functions/parsing/estonia/estonia.py
They didn't have that when I tested locally but now they do it seems, from stacktrace in dev:
```
[ERROR] ValueError: Unhandled age: üle 85
Traceback (most recent call last):
  File "/var/task/estonia.py", line 109, in lambda_handler
    return parsing_lib.run_lambda(event, context, parse_cases)
  File "/opt/python/parsing_lib.py", line 250, in run_lambda
    common_lib.complete_with_error(
  File "/opt/python/common_lib.py", line 88, in complete_with_error
    raise exception
  File "/opt/python/parsing_lib.py", line 237, in run_lambda
    count_created, count_updated = write_to_server(
  File "/opt/python/parsing_lib.py", line 110, in write_to_server
    batch = batch_of(cases, CASES_BATCH_SIZE)
  File "/opt/python/parsing_lib.py", line 96, in batch_of
    batch.append(next(cases)) …
```
> handle estonian age over 85

- verification/curator-service/ui/cypress/fixtures/no_header.csv
- verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts
- verification/curator-service/ui/src/components/BulkCaseForm.tsx
- verification/curator-service/ui/src/components/bulk-case-form-fields/CaseValidationError.test.ts
- verification/curator-service/ui/src/components/bulk-case-form-fields/CaseValidationError.ts
For #1144
Not sure how we could 100% detect that a CSV without header was uploaded but this adds a fall back in case the error returned are not formatted as expected.
> show geocoding errors properly in bulk upload

- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
Advantage is that it requires no configuration per source, disadvantage is that it makes assumptions like having one file in the zip file that we're interested in. Fortunately I think that's the case for Mexico data that we're trying to ingest so it seems fine to me. I couldn't confirm though as I can't download the original zip file (need to vpn somewhere it seems, can't DL from Europe :( ).
For #1155
> uncompress zip files when source URL points to one

- verification/curator-service/ui/src/components/App.tsx
- verification/curator-service/ui/src/components/LinelistTable.test.tsx
- verification/curator-service/ui/src/components/LinelistTable.tsx
- verification/curator-service/ui/src/components/SearchBar.tsx
loading state is up in the App component because it has to be sent to the search bar by the linelist component, feels a bit clunky but I think that's right (aka. the React way of moving the state up).
Fixes #1115
> Disable search bar when search is ongoing

- data-serving/data-service/package-lock.json
- data-serving/data-service/package.json
- data-serving/data-service/src/geocoding/mapbox.ts
- data-serving/data-service/src/index.ts
- data-serving/data-service/src/util/validate-env.ts
- data-serving/data-service/test/geocoding/mapbox.test.ts
Fixes #1131
Will talk to @gtuli to raise the limits on the mapbox side now that we have that in place.
Note that this assumes 600 requests per second per task, it's not global rate limiting (no shared state between dev/prod tasks), we'll need a more complex solution if we want to support that.
> Client-side rate limit geocode requests

- verification/curator-service/ui/src/components/App.tsx
Previously it was briefly showing after logging.
> Don't show the landing page while the get user request is ongoing

- aws/curator.yaml
- aws/data.yaml
For #961
Basically took away 768Mi of RAM from dev and prod curator which do not need much memory (only data service is OOMing) and reassigned that to prod data service.
We're currently capping our RAM limits but for CPU we're totally still in the green so I've bumped it quite a lot.
FTR we currently have two t3.small nodes for workers which gives us 4Gigs of RAM and 4vCPU in total:
> Give more RAM and CPU to prod data service

- verification/curator-service/api/src/controllers/sources.ts
- verification/curator-service/api/src/model/origin.ts
- verification/curator-service/api/test/sources.test.ts
- verification/curator-service/ui/cypress/integration/components/EditCase.spec.ts
- verification/curator-service/ui/cypress/integration/components/SourceTableTest.spec.ts
- verification/curator-service/ui/src/components/SourceTable.test.tsx
- verification/curator-service/ui/src/components/SourceTable.tsx
It turns out that fields with undefined values are just dropped from the request body by the openapi validator, so we were sending {dateFilter: undefined} and within the source controller updater handler we were seeing req.body == {}
:-(
There doesn't seem to be an option in openapi to keep those fields, there is "nullable" but that just sets the field to null when we save the source document, it doesn't remove it from the document as we want.
So the manual-and-cumbersome alternative that I found was to check and set the field to undefined ourselves if we got an empty {} (non null and non undefined) dateFilter.
Also fixes a typo in the edit case cypress test (how was it working until now??) and better English on the displayed date filter.
For #1198
> Fix inability to clear dateFilter fields on source updates

- ingestion/functions/parsing/germany/germany.py
- ingestion/functions/parsing/germany/germany_test.py
The mapbox geocoder prefers query text in the reverse order from how I initially had it. This commit should fix that issue.
> Flip order for geocoding query

- ingestion/functions/parsing/common/python/parsing_lib/input_event.json
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
Apologies, I missed this reviewing [this change](https://github.com/globaldothealth/list/commit/22f2ab7ef994e20888944134615868a6d71b6b40#diff-f4c0cfa1bb556db884ca7efd0b4d60b9). The data provided in the `parsing` input event is sent from the retrieval function. The field between the two should still be a single upload ID, since it's just the ID generated for the new upload as part of retrieval.
> Ensure retrieval->parsing upload continuity

- verification/curator-service/ui/src/components/LinelistTable.tsx
Fixes #1213
Fixes #1211
Before:
After:
> Don't wrap table headers and certain values so they fit on one line

- ingestion/functions/retrieval/retrieval.py
This is slightly simpler than what we had before and has the other benefit of working.
Tested with the source `https://covid19.ssp.df.gov.br/resources/dados/dados-abertos.csv?param=[random]`, fetched the result from s3 and running vimdiff over the raw data vs the retrieved data showed no textual difference (just the BOM being removed as the source encoding is indeed utf-8-sig).
> Use codec.getreader to read files

- aws/cluster.yaml
- aws/curator.yaml
- aws/data.yaml
@attwad: Gaurav mentioned in Slack that it'd be fine to move to `r6g.large` -- thoughts on this resource allocation?
I've drafted this up for 2x`t3.small` --> 1x `r6g.large`, but:
- Two instances is better than one from a redundancy standpoint, but with the current set up we require both instances to meet our resource allocations, anyway.
- We lose 2 total vCPU by doing this -- though I can't tell if we're ever CPU limited.
- I haven't actually used the full 16 GiB of memory.
We could do something like 1x `t3.small` and 1x `t3.large` instead, though I'd have to check if there are consequences to running multiple managed node groups.
> Increase node group instance size

- .github/workflows/curator-api-node.yml
- .github/workflows/curator-ui-node.yml
- .github/workflows/data-service-node.yml
- .github/workflows/ingestion-aws-sam-build.yml
- .github/workflows/ingestion-functions-python.yml
- .github/workflows/integration-tests.yml
- .github/workflows/suggest-python.yml
As opposed to merely those against main.
Since these actions are now unlimited/free, and since folks occasionally chain PRs, this is useful.
> Run actions on all pull requests

- aws/data.yaml
We have headroom for another 2Gi, according to the current node configuration (the other node is just running one replica of each prod service):
```
Non-terminated Pods:          (13 in total)
Namespace                   Name                                         CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
---------                   ----                                         ------------  ----------  ---------------  -------------  ---
cert-manager                cert-manager-9b8969d86-49w62                 0 (0%)        0 (0%)      0 (0%)           0 (0%)         109m
cert-manager                cert-manager-cainjector-8545fdf87c-lt8xv     0 (0%)        0 (0%)      0 (0%)           0 (0%)         109m
cert-manager                cert-manager-webhook-8c5db9fb6-974qj …
```
> Temporarily increase dev data server memory

- data-serving/data-service/schemas/cases.schema.json
- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/controllers/preprocessor.ts
- data-serving/data-service/test/controllers/preprocessor.test.ts
Reverting the preprocessor changes and the bulk write changes from #1226. It broke the mongo charts since the date types were saved as strings. The bulkWrite call converts the dates into the right format for us which the other bulk method didn't do. There are occasionally OOM errors with the bulkWrite call locally for 10k cases. But with dev and prod getting memory upgrades it shouldn't happen there. We also think it unlikely that bulk upload will be a highly used feature.
> Revert some changes from #1226

- ingestion/functions/template.yaml
For #508 I could successfully trigger a retrieval with that much RAM otherwise it fails with OOM.
> bump memory available to retrieval function to 1GB

- verification/curator-service/api/src/controllers/auth.ts
I noticed that doing a load test /api/cases was returning 403 and /api/sources was working fine, turns out we do not authenticate token bearer in the `mustBeAuthenticated` middleware as we do in the `mustHaveAnyRole` one. Now they are on par.
Now the load test passes fine locally, I need to push this to dev to be able to load test there.
For #1263
> authenticate bearer holders in mustBeAuthenticated method

- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
- ingestion/functions/parsing/india/input_event.json
- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/model/date-filter.ts
- verification/curator-service/ui/src/components/SourceTable.tsx
For large sources with UUIDs, this is the best way to get recent data. We can't ingest the entire corpus in each run, and using `EQ` runs the risk of missing data (a risk that's necessary/mitigated by delays for data without UUIDs).
> Add a dateFilter for greater than X days ago

- ingestion/functions/parsing/india/india.py
- ingestion/functions/parsing/india/india_test.py
- ingestion/functions/parsing/india/sample_data.csv
Backfilling this data, I noticed that the vast majority isn't actually able to be disaggregated into our platform. While I'd previously assumed the patientNumber/entryID represented a unique case/report, that isn't true for the "bulk" data they include. We should/must avoid such cases (which are represented as rows with >1 numCases) for two reasons:
- Rows with >1 numCases don't contain demographic information (merely location/count). Which is a bummer, though not a deal breaker, however:
- They don't always represent new data; for instance, a state might publish the amount of currently hospitalized patients
AFAICT, for rows with numCases == 1 we can be sure:
- For cases that receive updates, a state patient number is used, which we can use ourselves to dedupe
- Rows without state patient …
> Don't disaggregate non-line-list India data

- ingestion/functions/parsing/india/india.py
- ingestion/functions/parsing/india/india_test.py
- ingestion/functions/parsing/india/sample_data.csv
Some of the early CSV data is pretty loosely formatted. This cleans up a couple odds-and-ends, and allows the first set (`raw_data1.csv`) to be ingested without error. Each commit title tl;dr's the issue being addressed, but to expand slightly:
- I'd cleverly thought to avoid conflating an updated case's initial confirmation date with the date on which an outcome is reported by omitting a `confirmed` event for updates. As it turns out, this won't work because the presence of a `confirmed` event is required, and despite `events` being an array, we're rewriting (rather than appending to) the array with batchUpsert.
- Our schema specifies that additional sources must be unique. Which makes sense, but for whatever reason some rows have duplicate sources listed within them.
- A few rows have …
> Handle a number of remaining edge cases in India's data set

- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
Fixes issue reported on #1315.
Looking at the latest failure, on log stream 2020/10/19/[$LATEST]4a51da6751da47a59c77810aad2af821:
```python
{'env': 'prod', 's3Bucket': 'epid-sources-raw', 'sourceId': '5f7716e4e78c686408f6743e', 's3Key': '5f7716e4e78c686408f6743e/2020/10/19/1205/content.csv', 'sourceUrl': 'https://drive.google.com/uc?export=download&id=16JBgPV2Px93iD_NbuDo13b3ye4KGxlcW', 'uploadId': '5f8d8104b5daec3b1f5d2670', 'dateFilter': {'numDaysBeforeToday': 3, 'op': 'EQ'}, 'dateRange': None}
```
The problem was that if the CloudWatch event doesn't pass `dateRange` (because it specified a filter instead), the lib uses an empty dict. Then `filter_cases_by_date` tests whether that empty dict is not `None` (it isn't), and if it isn't it destructures it: boom.
Here I leave either of these …
> Avoid filling in unprovided date filters or ranges

- ingestion/functions/parsing/mexico/input_event.json
- ingestion/functions/parsing/mexico/mexico.py
- ingestion/functions/parsing/mexico/mexico_test.py
- ingestion/functions/retrieval/valid_scheduled_event.json
Now if a location code doesn't exist in the dictionary, the query string will simply contain 'MÉXICO'
I also changed the order of the query string to more closely match the way addressed are actually used in the country.
> add catch for if location code not in dictionaries

- ingestion/functions/template.yaml
Parser is running out of memory, hopefully this should do the trick.
> increase Mexico parser memory allocation

- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
@z023 reported that backfill hasn't worked since Oct 2. What I found is that when you request a backfill, you set the date range on the retrieval request (which is fed through to the parser). The parser lib loads the definition for the source, _including its date filter_. But this means that the parser lib tries to use _both_ the range and the filter when limiting the dates of cases, and boom. Backfill always errors.
I could have fixed this by removing the filter if the range is specified, but instead I chose to relax the "one or the other" assumption and instead document that the range always trumps the filter. That's because the range has always been explicitly requested by the user for this specific event, so should always be treated as deliberate.
> Allow both date filter and date range, only using range

- ingestion/functions/README.md
I added documentation to the parser README on using the GHDSI portal together with CloudWatch logs to find the cause of a failure in a parser.
> Describe using AWS logs in documentation

- ingestion/functions/parsing/japan/japan.py
- ingestion/functions/parsing/japan/japan_test.py
- ingestion/functions/parsing/japan/sample_data.json
I realize this is quite a crude fix so please let me know if there is a better way. 
In the absence of knowing exactly how the geocoding works I am also not 100% sure this will return the country Japan and not the neighbourhood in Indonesia called Japan, but `query: country` seems to have worked in the case of Argentina. 
Closes #1345
> Changes to parser to deal with port quarantine cases

- verification/curator-service/ui/src/components/LinelistTable.test.tsx
- verification/curator-service/ui/src/components/LinelistTable.tsx
- verification/curator-service/ui/src/components/ViewCase.tsx
- verification/curator-service/ui/src/components/util/date.test.tsx
- verification/curator-service/ui/src/components/util/date.tsx
**What:**
The list view now shows latitude and longitude and hospitalisation date/period along with symptoms onset date (where applicable). 
**Why:**
Per global.health team request
Checklist:
> [#1283] Add more details to list view (table)

- verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
- verification/curator-service/ui/src/components/App.tsx
- verification/curator-service/ui/src/components/LinelistTable.test.tsx
- verification/curator-service/ui/src/components/LinelistTable.tsx
#1006 Fix
**What:**
Now, when we move between the case details and the list view, the value doesn't change (#1006). At first, I wanted the changes to be consistent with the search (also stored in the same location object), but I've decided to do that in a more straightforward way so it could be more maintainable in the future. Now, the current page number and page size are persisted in the App component to avoid resetting between list re-render events.
The issue was about the page number, but the page size should be included in this fix as well. Otherwise, it doesn't make sense to save only the page number. There was also a bug that is very closely related to the pagination feature. When the user is changing the page size, the request to the backend is sending twice. This problem also …
> [#1006] Current page number & page size should be persisted while moving between case details and list view

- verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
- verification/curator-service/ui/src/components/LinelistTable.tsx
What:
Using search after switching the page or viewing a case details would result in blank page. This was caused by an infinite loop trigged on search query change in those cases. Search is now done using a different approach and flips back to page one after query change - regardless of whether the result includes the page a user was on when doing the search.
Why:
To improve user experience, as this situation occurred quite often during our tests of the application (#1360)
Checklist:
> #1360 Fix blank page after using search in certain cases 

- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/util/case.ts
- data-serving/data-service/test/model/data/case.events.json
- data-serving/data-service/test/util/case.test.ts
- data-serving/scripts/export-data/case_fields.yaml
This PR covers issue #1015
**What:**
As we agreed, I've made the following changes to the downloaded csv file:
- For both fields: **symptoms** and **nationalities**.
- Changed array to comma-separated values for the following fields:  
For example: `["chest pain","cough"] -> "chest pain, cough"`
- If the array is empty, return an empty string: `[] -> ''`
- **Events** are now separated to the following columns:
- _events.confirmed.value_
- _events.confirmed.date_
- _events.onsetSymptoms.date_
- _events.firstClinicalConsultation.date_
- _events.selfIsolation.date_
- _events.hospitalAdmission.value_
- _events.hospitalAdmission.date_
- _events.icuAdmission.value_
- _events.icuAdmission.date_
- _events.outcome.value_
- _events.outcome.date_
**Comment:**
A single **event** has the date range, …
> #1015: Adjust downloaded CSV file structure

- ingestion/functions/template.yaml
Increase memory to solve timeouts for Germany and Sao Paolo and inability to load data for Japan.
> Increase memory allocation for Japan, Germany, Sao Paolo

- data-serving/data-service/api/openapi.yaml
- data-serving/data-service/schemas/cases.schema.json
- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/index.ts
- data-serving/data-service/src/model/case.ts
- data-serving/data-service/src/model/exclusion-data.ts
- data-serving/data-service/test/controllers/case.test.ts
- data-serving/scripts/export-data/case_fields.yaml
- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/index.ts
This would close #1375 
This is the backend part of the bigger task: #1013. Whole description available here: #1376.
Technical note:
As is mentioned in #1399,  a new endpoint for changing the case status and handling all logic has been introduced for consistency purposes. This will require additional work on the frontend to accommodate that change.
**Important**
Database schema update is needed for excluding (since we introduced a new subdocument in case schema). The appropriate command to be executed in Mongo shell can be found here: https://gist.github.com/AKorzeniowski/0337ca2573d33484b61526f55279466f
Checklist:
> #1375 Add status change endpoint (incl. excluding)

- ingestion/functions/parsing/india/india.py
- ingestion/functions/parsing/india/india_test.py
- ingestion/functions/parsing/india/input_event.json
Per title, limit ingesting `covid19india` data to rows with the `Hospitalized` `currentStatus`.
We'd previously hoped to get data with other statuses by deduping on a state-specific UUID (in other words, allowing non-`Hospitalized` cases to be ingested on the basis that they'd be folded into an existing row with the same state-specific UUID), but that doesn't appear to have held up.
We'll get a slightly lower quantity of detailed information this way, but the data we get will be solid. There's one last hitch, which is that we can't reliably process rows with negative `numCases`. This is mostly a wash, however -- for the `raw_data16.csv` file, out of ~1.3M cases, the total of negative case counts for hospitalizations is 571.
On the whole, the linelist style data is a bit all over the place …
> Don't attempt to collate non-'Hospitalized' cases in covid19india data.

- verification/curator-service/ui/cypress/integration/components/AppTest.spec.ts
- verification/curator-service/ui/cypress/integration/components/EditCase.spec.ts
- verification/curator-service/ui/cypress/integration/components/UploadsTableTest.spec.ts
This fixes the problem with integration tests. Cypress selectors were too general and pointed to the wrong DOM elements.
> Fix integration tests due to too general cypress selectors

- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib_test.py
- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/index.ts
Closes #1374.
This is the final part of the bigger task: #1013. This PR introduces handling of case exclusion in the parsing process (via `parsing_lib`).
Checklist:
> #1374 Handle cases exclusion in parsers

- ingestion/functions/parsing/common/python/parsing_lib/parsing_lib.py
The new case id exclusion endpoint requires either a date_range or a date_filter argument. For sources small enough that the entire dataset is ingested every time, this causes an error.
This PR adds a catch, retrieving all excluded case ids from the endpoint when no date limits are included for a source.
> Add catch for case exclusion when no date limits

- ingestion/functions/parsing/mexico/mexico.py
- ingestion/functions/parsing/mexico/mexico_test.py
This PR adds `ID_REGISTRO` as the UUID for the Mexico parser.
> add UUIDs to Mexico parser

- ingestion/functions/template.yaml
template.yaml had a lot of lines commented out by error, which I totally missed. This is as good an opportunity as any to give the retrieval function a needed memory boost anyhow.
> uncomment all the parsers and bump retrieval function memory

- ingestion/functions/parsing/argentina/argentina.py
- ingestion/functions/parsing/argentina/argentina_test.py
Using newline as the delimiter for the notes was unfortunately causing some parsing issues for the download for the whole dataset! This is a quick fix, simply switching out newlines for commas to match the other parsers.
> Change Argentina notes delimiter from "\n" to ", "

- ingestion/functions/parsing/germany/germany.py
This should solve [ERROR] ValueError: Unhandled data: time data '2020/11/23 0' does not match format '%Y/%m/%d %H:%M:%S'
Also will make the parser more resistant to future errors.
> Deal with non-standard date format

- data/README.md
Remove data export from deprecated workflow. This workflow had been failing for a long time before being put on pause due to the data becoming too big for the job to complete.
Full data is now stored on S3, and requires acceptance of TOS and PP for access.
> remove deprecated data export

- data-serving/data-service/api/openapi.yaml
- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/util/search.ts
- data-serving/data-service/test/controllers/case.test.ts
- verification/curator-service/ui/package-lock.json
- verification/curator-service/ui/package.json
- verification/curator-service/ui/src/components/SearchBar.tsx
- verification/curator-service/ui/src/components/SearchGuideDialog.tsx
Going to open this up to review now with 1/3 requirements from the checklist at #1502 implemented to get input on my plan for the other 2/3. Variant field is parsed in the search on the backend, and available in the search bar on the frontend.
- there's a request for a "non-null" search, i.e. for any variant. Our current search doesn't allow for that, so I was thinking of testing for the string `*` as a search value and special-casing that. `variant:foo` would execute the query `Case.find().where('variant.name').equals('foo')` as is currently the case, but `variant:*` would execute `Case.find().where('variant.name').exists()`. This would work for all other properties, e.g. `admin3:*`.
- map: I haven't looked at the map code yet at all. I know it's going to be easy to add the variant to …
> 1502 voc filter

- verification/curator-service/ui/src/components/landing-page/LandingPage.tsx
- verification/curator-service/ui/src/components/landing-page/SignInForm.tsx
- verification/curator-service/ui/src/components/landing-page/VerificationCodeForm.tsx
> 1508 - Fix text field alignment on email signup form

- ingestion/functions/parsing/germany/dictionaries.json
- ingestion/functions/parsing/germany/germany.py
- ingestion/functions/parsing/germany/germany_test.py
- ingestion/functions/parsing/germany/sample_data.csv
Issue was that German locations were only geocoding to admin1. Because of issues with German admin3 locations and mapbox previously identified by @calremmel I have added location information based on lat/long info from https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/esri-de-content::kreisgrenzen-2019
Note that the only locations not covered by this are the subdivisions within Berlin which are officially admin2 (not admin3) and so therefore no information for them was present in the source above. These will be geocoded using mapbox as Berlin, Germany.
> Germany geocoding error

- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
This PR adds chunking support for CSV files to solve the backfill issue. Other file types (currently JSON and XLSX) are not chunked.
* Change return type of `retrieve_content()`. `retrieve_content()` now returns list of `(filename, s3 object key)`
tuples instead of a single tuple corresponding to the chunks. Only for CSVs, `retrieve_content_csv()` is called which performs chunking, with each chunk limited to `CSV_CHUNK_BYTES`. No chunking is performed for JSON and XLSX.
* `invoke_parser()` is called in a loop with the s3 object keys.
What's the best practice to test the output of retrieval_content_csv()? Currently there are no content tests (such as checking filetype). As I see it, one would need to have a fake local URL to pass to requests. Any pointers welcome!
Also, what happens if one …
> Ingestion chunking [partial fix for #1434]

- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
- ingestion/functions/template.yaml
This PR adds large file ingestion support by saving temporary files to a EFS volume which is attached to the retrieval function.
**Note**: At the moment tests **do not** check whether the EFS is mounted properly, as I wasn't sure whether that would work in the Github CI environment. There is a `tempdir` parameter that controls where temporary files are saved that is set to `/tmp` for Github CI.
> 1488 large data ingestion

- verification/curator-service/ui/src/components/App.tsx
- verification/curator-service/ui/src/components/LinelistTable.tsx
- verification/curator-service/ui/src/components/SearchBar.tsx
- verification/curator-service/ui/src/hooks/useDebounce.tsx
**Changes**
* When search query is typed into SearchBar filters are automatically applied after given duration (1 second for now)
* Created custom hook `useDebounce`
* Stopped setting SearchBar as disabled when data is loading
> 1537 Apply search filters automatically after delay

- verification/curator-service/ui/src/components/App.tsx
changed text from Global.Health to About Global.Health
> 1540 - changed menu dropdown text

- ingestion/functions/retrieval/retrieval.py
Some chunks are still causing timeouts during backfill such as for Mexico, Germany and Sao Paolo, reduce the chunk size
to see if this is fixed.
> Reduce chunk size to 50 MiB #1560

- ingestion/functions/parsing/USA/USA.py
- ingestion/functions/parsing/USA/USA_test.py
using 'query: Unites States' in mapbox was returning Cloud, Cloud, Kansas. We want only United States to be the name.
> Hard-code USA location

- ingestion/functions/parsing/czechia/czechia.py
- ingestion/functions/parsing/czechia/czechia_test.py
Deal with empty region or district columns.
> Fix to deal with empty location fields in Czechia parser

- verification/curator-service/ui/src/components/App.tsx
It was Global.Health -> it is Global.health
> fixed about letter in data menu

- data-serving/data-service/package-lock.json
- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/test/controllers/case.test.ts
- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/package-lock.json
- verification/curator-service/api/src/model/source.ts
- verification/curator-service/api/src/schemas/sources.schema.json
- verification/curator-service/api/test/sources.test.ts
- verification/curator-service/ui/src/components/SourceTable.tsx
Whew! This was quite the ride: implementing this change involved switching large chunks of the data service from `Collection.find()` to `Collection.aggregate()` because finding cases now involves a join on the sources collection to ensure you're allowed to expose this case.
I'm putting this up now because the approach basically works, and I just need to colour it in. So I'd like a review to ensure we all agree this is a good way to implement it.
I have _not_ altered the upsert/delete operations, because then the parsers that work with excluded sources couldn't modify any records.
This PR addresses #1520.
> Filter sources

- ingestion/functions/README.md
This PR suggests some steps for debugging the retrieval function when it breaks. These steps should still be somewhat useful for the Batch method, though there will be some differences concerning where configuration takes place. Please excuse the typo in the branch name.
> add debugging info for retrieval function to ingestion README

- data-serving/data-service/api/openapi.yaml
- data-serving/data-service/schemas/cases.schema.json
- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/model/location.ts
- data-serving/data-service/src/model/travel.ts
- data-serving/data-service/test/controllers/case.test.ts
- verification/curator-service/api/openapi/openapi.yaml
This unblocks the VoC ingestion because not all the VoC reports have detailed travel history, but it was decided that we should keep as much incomplete info as possible.
> No location in travel history

- data-serving/data-service/src/index.ts
From [data-dev logs](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Fcontainerinsights$252Fghdsi$252Fapplication/log-events/data-dev-58845ff9f7-2mjdl_default_data-042226c72ddc14d690c5acad6a597263453b7ae12474530b198ce6ab69d8ce70$3Fstart$3D1619014800000$26end$3D1619015100000) while running Estonia ingestion "Longjohn is known to cause CPU usage due to its extensive data collection during runtime"
[Longjohn] puts a lot of strain on V8's garbage collector and can greatly slow down heavily-loaded applications
https://www.npmjs.com/package/longjohn#production-use
> Removing longjohn from dev environment

- ingestion/functions/common/parsing_lib.py
I noticed that the list returned by the API is never used (and the tests mock this function so hadn't picked up on that)
> Use the value of excluded cases returned by the backend

- aws/location.yaml
- geocoding/location-service/src/app/main.py
Pass database from DB environment variable to AdminsFetcher
instead of the client, which raises an exception because
.find_one() gets called on a database instead of a collection
in admins_fetcher.py:47
> geocoding: Pass database to AdminsFetcher

- ingestion/functions/common/common_lib.py
- ingestion/functions/common/common_lib_test.py
- ingestion/functions/common/parsing_lib.py
This updates the fix in 1b0659347624eae79692ebb1baf2dd488c9ef7d6
In a nested try-except the outer exception is always called, but
we do not want to raise an exception for a 401.
This changes the return type of common_lib.finalize_upload() to a
tuple of (status, text) that is checked in parsing_lib which
raises a RuntimeError if required.
> ingestion: Fix reauthentication during finalize_upload()

- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
Relates to #1881, which is blocked by #1880
> retrieval: Use awsLambdaArn before #1880 is fixed

- data-serving/data-service/package.json
- verification/curator-service/api/package-lock.json
- verification/curator-service/api/package.json
Always fetching the latest mongo fixes the issue where
mongodb-memory-server tries to fetch mongo and fails because
the version does not exist.
Using fix from mongodb-memory-server issue #316
> data,curator: Fetch latest in mongodb-memory-server

- README.md
- aws/README.md
- ingestion/functions/README.md
- docs: Update aws/README with new kubernetes output, config
- docs: Update main README links and badges
- docs: Add manual ingestion steps, closes #1724
> 202105 update docs

- geocoding/location-service/poetry.lock
- geocoding/location-service/src/app/admins_fetcher.py
- geocoding/location-service/src/app/main.py
The problem in dev and prod for the geocoding service is a failure to authenticate for a mongodb operation. I have gone through the workflow manually in the python command line using the dev secret and have found the commands I've switched to here to work, so I'm hoping this change works in deployment too!
> Ensure pymongo knows how to authenticate

- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/test/controllers/case.test.ts
- ingestion/functions/common/parsing_lib.py
- ingestion/functions/common/parsing_lib_test.py
This changes the validation handling in the data service such that if a validation failure happens, the data service tries to insert any valid cases and reports a mixed status rather than giving up. It also changes the ingestion library to interpret responses sent in this case.
> #1866 no early abort upsert

- verification/curator-service/api/package-lock.json
I wanted to just update the y18n version, but running `npm install --package-lock-only y18n@4.0.3` recreated the entire lock file...so I also ran `npm audit` since it seemed relatively low-impact.
EDIT: that broke mongoose somehow...copy/pasted y18n section from package-lock.json and left the rest alone.
> bumped y18n and ran npm audit

- ingestion/functions/parsing/argentina/argentina.py
- ingestion/functions/parsing/argentina/dictionaries.json
Argentina parser was crashing with missing 'corea republicana'.
Fix by adding entry to country code list, and fixes the error class
of missing country codes to log an error instead of crashing.
Fixes: #1922
> parsing: Fix crash with missing country code in Argentina

- data-serving/data-service/api/openapi.yaml
- data-serving/data-service/package.json
- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/controllers/preprocessor.ts
- data-serving/data-service/src/index.ts
- data-serving/data-service/src/model/case.ts
- data-serving/data-service/test/controllers/case.test.ts
- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/package-lock.json
- verification/curator-service/api/src/controllers/sources.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/src/model/source.ts
- verification/curator-service/api/src/schemas/sources.schema.json
- verification/curator-service/api/test/model/data/source.full.json
- verification/curator-service/api/test/sources.test.ts
- verification/curator-service/ui/package-lock.json
- verification/curator-service/ui/src/components/AutomatedBackfill.tsx
- verification/curator-service/ui/src/components/AutomatedSourceForm.test.tsx
- verification/curator-service/ui/src/components/AutomatedSourceForm.tsx
- verification/curator-service/ui/src/components/SourceTable.test.tsx
- verification/curator-service/ui/src/components/SourceTable.tsx
- verification/curator-service/ui/src/components/common-form-fields/Source.tsx
This is the backend work for #1921, the parser lib work will come in another PR (assuming we don't decide to move away from the data-service before that happens!).
> 1921 delete and reimport sources without stable ids

- ingestion/functions/common/parsing_lib.py
- ingestion/functions/common/parsing_lib_test.py
- verification/curator-service/ui/package-lock.json
- verification/curator-service/ui/src/components/AutomatedSourceForm.tsx
- verification/curator-service/ui/src/components/SourceTable.tsx
Mostly putting this up as draft now as it's the easiest way to get the dockerised tests to run, which are the only way to test the function I need to change.
#1921
> Check in parser if the source has stable IDs and if not, delete the existing cases

- ingestion/functions/common/parsing_lib.py
- parsing: Default to has_stable_ids = True
- parsing: Pass headers and cookies to fix 403
> fix ingestion

- verification/curator-service/ui/cypress/integration/components/UploadsTableTest.spec.ts
- verification/curator-service/ui/src/components/UploadsTable.test.tsx
- verification/curator-service/ui/src/components/UploadsTable.tsx
#1355 it is confusing to lose track of an upload because it made no changes, when those are the ones we are most likely to want to diagnose!
> Do not filter the list of uploads to exclude zero-case uploads.

- .github/workflows/ingestion-functions-deploy.yml
- ingestion/functions/aws.py
The latest stable branch is used to build a :stable image
for gdh-ingestor. Also updates the job definition section
in aws.py to use stable images from prod environment.
> Build ingestion image from stable branch #1954

- .github/workflows/curator-service-package.yml
- .github/workflows/data-service-package.yml
- .github/workflows/geocoding-service-package.yml
Followed migration instructions at https://github.com/docker/build-push-action/blob/master/UPGRADE.md
I didn't touch the ingestion functions deployment as that's using a different workflow. Not sure how to test this without tagging or merging though.
> Upgrade docker publish action to v2

- data-serving/data-service/package-lock.json
- data-serving/data-service/package.json
- data-serving/data-service/src/controllers/case.ts
Geocoding has been moved to its own service, so we don't need
mapbox dependency in data service.
Fixes: CVE-2021-33502
> Remove mapbox dependency from data service

- verification/curator-service/api/test/sources.test.ts
Tests for non-UUID sources were not running because of this error:
Returning a Promise from "describe" is not supported. Tests must be defined synchronously.
Returning a value from "describe" will fail the test in a future version of Jest.
> Enable tests for case deletion in non-UUID sources

- verification/curator-service/Dockerfile
The reason downloads are failing in #1949 is this error reported in the app logs:
Error: Cannot find module '/usr/src/app/src/workers/downloadAsync.js'\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
> Copy the downloadAsync worker into the production docker image

- ingestion/functions/retrieval/retrieval.py
Alternative is to set it in the parser
> ingestion: Use utf-8 if encoding detection fails

- verification/curator-service/ui/src/components/ViewCase.tsx
Safari doesn't support lookahead/lookbehind in regex, so the syntax highlighting had broken Safari support. I've changed the regex so it doesn't use them, which obviously means it doesn't match the same things any more so I've basically broken syntax highlighting. @sergioloporto hoping your regex skills can help design a highlight implementation that will work, any ideas?
Here's the compatibility matrix: https://caniuse.com/js-regexp-lookbehind
> Remove regex features that Safari does not support #1976

- dev/Dockerfile
- dev/README.md
- dev/docker-compose.dev.full.yml
- dev/iam_role.json
- dev/run_full_stack.sh
- dev/setup_localstack.py
- dev/test_all.sh
- verification/curator-service/api/src/clients/aws-batch-client.ts
- verification/curator-service/api/src/clients/aws-events-client.ts
- verification/curator-service/api/src/clients/aws-lambda-client.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/src/util/validate-env.ts
- verification/curator-service/api/src/workers/downloadAsync.js
- verification/curator-service/api/test/auth.test.ts
- verification/curator-service/api/test/clients/aws-batch-client.test.ts
- verification/curator-service/api/test/clients/aws-events-client.test.ts
- verification/curator-service/ui/cypress/integration/components/AutomatedSourceForm.spec.ts
- Create S3 buckets
- Create Batch Job Queue
- Add email address to SES
- Curator AWS clients use localstack when using locale2e docker-compose stack
- Curator async download uses localstack when using locale2e docker-compose stack
> Added localstack batch and locale2e

- .github/workflows/prune-uploads-tests.yml
- data-serving/scripts/prune-uploads/prune_uploads.py
- data-serving/scripts/prune-uploads/test_prune_uploads.py
Epoch date specified using PRUNE_EPOCH is the date after which
successful uploads are considered for non-UUID sources. This is
to facilitate transition from the previous approach where non-UUID
sources were ingested over multiple, rather than single, uploads.
> prune-uploads: Use epoch and remove ERROR uploads

- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/workers/downloadAsync.js
Including a `name` field in the logs for the worker
> Adding logging around downloadAsyncWorker

- data-serving/scripts/export-data/functions/02-export/app.py
Fix quoting error that caused subprocess.run() to incorrectly
interpret the arguments leading to a broken mongoexport call.
> export: Hardcode query as list=true #2058

- data-serving/data-service/src/model/case-reference.ts
- data-serving/data-service/test/model/data/case.minimal.json
prune-uploads requires uploadIds which are not mandatory at present.
This doesn't matter for UUID sources where all data is ingested,
but for non-UUID sources, not having an uploadId means the corresponding
data will never be deleted.
Fixes: #2056
> data-service: Make uploadIds mandatory in batchValidate

- data-serving/data-service/src/controllers/case.ts
batchUpsert for UUID sources is randomly failing with the error
that duplicate caserevision (same case ID and revision) is being
inserted into the caserevisions collection (issue #2005, but
seen in other UUID sources as well).
The responsibility for making sure that a case with the same
revision is not upserted again is in batchUpsertDropUnchangedCases()
which drops unchanged cases, by using findCasesWithCaseReferenceData().
As findCasesWithCaseReferenceData() calls select({}) which
only returns _id (if fieldsToSelect is not specified), this would not
be able to match against an entire case (existingCase.equalsJSON(c))
This commit drops .select() if fieldsToSelected is undefined
which should include all fields, allowing matches against existing
cases to succeed.
> data-service: Attempted fix for duplicate caserevisions insertion

- data-serving/scripts/prune-uploads/prune_uploads.py
- data-serving/scripts/prune-uploads/test_prune_uploads.py
Previously older, accepted uploads were not pruned. This was
incorrect behaviour for non-UUID sources (UUID sources don't get
pruned) as only the latest successful upload should be present
in the database, with older accepted uploads being deleted as well.
> prune-uploads: Prune older accepted uploads

- ingestion/functions/retrieval/retrieval.py
- ingestion/functions/retrieval/retrieval_test.py
Using the ::daysbefore=N suffix will offset the current date
by N days in the past before substitution in the source URL. This
is useful for sources that publish regularly, but whose filename
is offset by a fixed number of days.
> retrieval: Add ::daysbefore=N suffix support to source URLs

- data-serving/scripts/prune-uploads/prune_uploads.py
- data-serving/scripts/prune-uploads/test_prune_uploads.py
Previously, prune-uploads would re-mark existing accepted cases
again unnecessarily.
> prune-uploads: Skip accepted uploads

- data-serving/data-service/schemas/cases.indexes.json
MongoDB requires indices to have the same collation as the query
for string indices. As queries in the data service use en_US collation,
all string indices in the schema require the collation to be set.
This fixes the issue of sourceId searches taking too long that was
introduced in 1415d75dc7ae7d73d95996086098ef61b7e8bf2e.
> data-service: Add collation to sourceId index

- data-serving/data-service/src/controllers/preprocessor.ts
Case revision inserts fail intermittently when trying to
write a case revision with the same ID and revision number to
the caserevisions collection which enforces uniqueness on
these two fields. An exception is raised even if one insert
fails.
As case revisions are not exposed to the UI, and we save the
original data files for each source (which can be used to recreate
older versions of cases), this commit ignores the exception but
logs it.
This only affects UUID sources; non-UUID sources are always
ingested in full and do not update case revisions.
This is the second attempted fix for #2005, previous attempt
at c7a21c5a002369f822b906426e3cb00bffdb1cc9 did not fix.
> data-service: Ignore case revision insert errors

- data-serving/data-service/schemas/cases.indexes.json
Without the date index, the initial page of data after logging
in gives a 504, as no country is selected.
> db: Re-add creation metadata date index

- data-serving/data-service/package-lock.json
- data-serving/data-service/package.json
- verification/curator-service/api/package-lock.json
- verification/curator-service/api/package.json
I didn't bump major version because ain't nobody got time for that, but I believe this pushes us past the dependabot complaint about `mpath`.
> Update vulnerable mongoose version

- dev/docker-compose.dev.full.yml
- dev/setup_localstack.py
- ingestion/functions/common/parsing_lib.py
- ingestion/functions/common/parsing_lib_test.py
- ingestion/functions/retrieval/retrieval.py
- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/index.ts
When a source ingestion without a date filter finishes ingestion will push .json, .tsv, and .csv files to a versioned S3 bucket.
When a user requests a country-only filtered download from the curator it will look in the S3 bucket for that file, return it if it exists, and fall back to the data service if it does not.
> Added S3 cache layer to locale2e and Curator API

- .github/workflows/export-deploy.yml
- .github/workflows/export-tests.yml
- .github/workflows/prune-uploads-dev.yml
- .github/workflows/prune-uploads-prod.yml
- data-serving/scripts/export-data/Dockerfile
- data-serving/scripts/export-data/Dockerfile_full_export
- data-serving/scripts/export-data/README.md
- data-serving/scripts/export-data/common.sh
- data-serving/scripts/export-data/country_export.sh
- data-serving/scripts/export-data/full_export.sh
- data-serving/scripts/export-data/setup_country_export.sh
- data-serving/scripts/export-data/setup_full_export.sh
- data-serving/scripts/export-data/transform.py
- data-serving/scripts/prepare_fields_list/src/index.ts
- data-serving/scripts/prune-uploads/README.md
- data-serving/scripts/prune-uploads/hooks/country_export.py
- data-serving/scripts/prune-uploads/hooks/tests/test_country_export.py
- data-serving/scripts/prune-uploads/prune_uploads.py
- data-serving/scripts/prune-uploads/test_prune_uploads.py
We don't need to run export on dev, so disable hooks by default.
> Add hooks in prune, support multiple environments in export

- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/model/case.ts
- data-serving/data-service/test/model/case.test.ts
- data-serving/scripts/setup-db/migrations/20211109102327-denormalise-confirmation-date-1875.js
I've added an index on confirmed date. To do that I've added a migration to extract the date on the confirmed event and store it in a top-level field, and I've added mongoose middleware to keep that in sync for new additions/changes. This means that there are no changes to ingestion scripts or the APIs, the app works as previously but the data-service does the heavy lifting of keeping this extra field in sync.
The reason I've gone for mongoose middleware here is simply that mongo itself doesn't have database triggers (mongodb atlas does, via realm, but then we couldn't actually synchronise those triggers with our existing migration tools). I could've written express middleware to rewrite the requests in the same way that our creation metadata works, but then there's more work remembering …
> 1875 denormalise confirmed date

- data-serving/scripts/prune-uploads/hooks/country_export.py
- data-serving/scripts/prune-uploads/prune_uploads.py
- data-serving/scripts/prune-uploads/test_prune_uploads.py
Currently, find_acceptable_upload() returns a tuple ([], [])
when no pending uploads are present for UUID sources.
Change this to None to bring in sync with non-UUID sources.
This should no-op prune-uploads when no pending uploads are
found. Also add a check that sources were actually ingested
in this prune before calling hooks for country export, both
in prune-uploads and in the country export hook.
> prune-uploads: No-op when no pending uploads for UUID sources

- verification/curator-service/api/src/controllers/cases.ts
Filtered downloads (country only) throw `There was an error while downloading data, please try again later. TypeError: o.headers['content-disposition'] is undefined`. Full data set downloads and non-country-only filtered downloads (e.g. country + gender) work as expected.
> Removing string template

- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/ui/src/components/LinelistTable.tsx
A country-only download query should download from S3, which will return a presigned URL the curator should redirect to.
Other filtered download queries should stream through the data service, which will set the file name through the content-disposition header.
> Checking for presigned URL before checking for content-disposition header

- dev/docker-compose.dev.full.yml
- dev/setup_localstack.py
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/ui/src/components/LinelistTable.tsx
The 'blob' responseType ate the signedUrl, making it look like it was undefined. We don't need it anymore, as the filtered data downloads can work from S3 and the data service without it.
I also replaced spaces in country names with underscores, removed some `console.log` statements, and updated the local environment.
> Removing responseType headers from request to curator API

- verification/curator-service/ui/src/redux/filters/thunk.ts
**Changes**
- Created and uploaded file to AWS S3: https://covid-19-aggregates.s3.amazonaws.com/countries-list.json containing a list of all countries that we have data from. This file is now used to populate country dropdown in filters modal in Curator UI. This fixes Cypress tests sometimes failing due to missing countries in latest data exports
> #2278 Updated countries list source file

- ingestion/functions/docker-compose-test.yml
Fixes failing ingestor tests in CI caused by https://github.com/localstack/localstack/issues/4903
> Changing localstack version due to SSL cert issue

- data-serving/scripts/setup-db/migrations/20211204203100-fix-byDateIfListed.js
Sorting in the data UI uses collation with en_US and strength 2.
The landing page shows cases with list: true and sorts by
revisionMetadata.creationMetadata.date, which should have been
handled by the byDateIfListed index. This index was not
collated, leading MongoDB to do a collection scan on the landing
page. This issue type (504s due to missing collation) has
happened before, see 0b01e0a059c68cea09975394022c168a3a23b039.
Other pages such as filtering by country were not affected as the
corresponding indices were collated already.
Fixes: #2298
> migrations: Add collation to byDateIfListed index collated

- README.md
- data-serving/data-service/README.md
- dev/run_session.py
- verification/curator-service/ui/src/components/App/App.test.tsx
- verification/curator-service/ui/src/components/App/App.tsx
- verification/curator-service/ui/src/components/landing-page/LandingPage.test.tsx
- verification/curator-service/ui/src/components/landing-page/LandingPage.tsx
The full version of the data dictionary (data_dictionary.txt)
is now linked to from the UI, and references to the older
01-split/fields.txt has been changed to the correct location.
Fixes: #2309
> Update data dictionary and fields.txt references

- ingestion/functions/retrieval/retrieval.py
This prevents UnboundLocalError when creating the payload.
> retrieval: Assign auth a value if cookies unset

- data-serving/scripts/prune-uploads/hooks/aggregate.py
- data-serving/scripts/prune-uploads/prune_uploads.py
Now that aggregate is fixed, we can hook it up to prune-uploads, which will avoid us having to manage another EventBridge rule, as well as making sure it runs *after* prune.
> prune-uploads: Add aggregate hook to prune-uploads

- data-serving/scripts/export-data/test_transform.py
- data-serving/scripts/export-data/transform.py
In transform.py, both the input and output variables were named
event, which caused all event.get("value") to be None. Renamed
output variable to fix this. Also removed unused imports and
added a test.
Fixes: #2349
> export: Fix bug where events.*.value is always null

- api/R/gdh.r
- api/README.md
- api/python/gdh.py
- api/python/test_gdh.py
Countries with spaces in names might fail on download as they are using streaming, this will be fixed once #2353 closes. Limiting to country only as we should test all index and filter combinations on UI and download before allowing API access.
- api: Only support country filter
- api: Add documentation
> api client country only

- data-serving/scripts/setup-db/manual-migration-helpers/batch_countries.js
Before I re-run the country codes migration in dev I need to fix the problem that made it bomb out last time, and ensure it doesn't try to migrate data that's already been fixed.
> Robustify country migration

- ingestion/monitoring/freshness.py
daily_metrics.py assumes all JSON files in country/
are in a certain format, and fails on freshness.json
> monitoring: Move freshness data to metrics

- data-serving/data-service/src/model/vaccine.ts
Vaccine side effects are an array in the Mongoose schema, but
of the form {values: [string], status: string} in the MongoDB
schema, which led to validation passing but raised an error
on insert to MongoDB.
Fixes: #2410
> data-service/model: Fix mismatch in vaccine sideEffects schema

- ingestion/functions/common/parsing_lib.py
When travelHistory is None, the first condition succeeds but
the second raises a TypeError as NoneType is not iterable.
> parsing: Fix TypeError when travelHistory is None

- dev/setup_ingestion.py
- dev/setup_localstack.py
- ingestion/functions/.env
- ingestion/functions/aws.py
- ingestion/functions/aws_access/EventBridgeClient.py
- ingestion/functions/aws_access/S3Client.py
- ingestion/functions/aws_access/ScheduleRuleTests.py
- ingestion/functions/aws_access/globaldothealth_configuration.py
- ingestion/functions/clean_old_ingestion_source_files.py
- ingestion/functions/poetry.lock
- ingestion/functions/pyproject.toml
- ingestion/functions/test_clean_old_ingestion_source_files.py
Draft because I still need to integrate this into the LocalStack e2e test runner (and into ops too), but asking for feedback on the script and the approach. Also, how _will_ this get run? Is there somewhere I can run this on a schedule that already has access to a service account for our AWS?
> 2217 delete old ADI source data

- .github/workflows/ingestion-cleanup-deploy.yml
This fixes one problem. The build action failed on merge, looks like the connection to ECR timed out but will reevaluate if this merge fails too.
> Remove unused arg from the cleanup script image build

- geocoding/location-service/src/app/geocoder.py
- geocoding/location-service/src/app/geocoder_suggester.py
- geocoding/location-service/src/app/main.py
- geocoding/location-service/test/test_fake_geocoder.py
- geocoding/location-service/test/test_geocoder.py
Problem was that the name-to-country mapping used in the location service correctly rejects ambiguous names, but that mapbox returns "United States" for the USA which is ambiguous. I've special-cased that, and added enough logging that we should be able to find other cases much more quickly.
> 2526 fix geocoding

- ingestion/functions/common/common_lib.py
- ingestion/functions/common/parsing_lib.py
- parsing_lib: use import workaround
- parsing_lib: fix error on get() call for non-dictionaries
> Fix AttributeError in parsing_lib.prepare_cases()

- data-serving/scripts/setup-db/migrations/20220223130636-add_origin_fields_to_sources.js
- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/model/origin.ts
- verification/curator-service/api/test/model/data/origin.full.json
- verification/curator-service/api/test/model/data/origin.minimal.json
- verification/curator-service/api/test/model/origin.test.ts
- verification/curator-service/ui/cypress/integration/components/BulkCaseForm.spec.ts
- verification/curator-service/ui/cypress/integration/components/Curator.spec.ts
- verification/curator-service/ui/cypress/integration/components/NewCaseForm.spec.ts
- verification/curator-service/ui/src/components/AutomatedSourceForm.test.tsx
- verification/curator-service/ui/src/components/AutomatedSourceForm.tsx
- verification/curator-service/ui/src/components/BulkCaseForm.tsx
- verification/curator-service/ui/src/components/CaseForm.tsx
- verification/curator-service/ui/src/components/SourceTable.test.tsx
- verification/curator-service/ui/src/components/SourceTable.tsx
- verification/curator-service/ui/src/components/common-form-fields/Source.tsx
Add the extra fields that can be used to generate the acknowledgements page for #2499. I noticed that the "source name" wasn't being used in a very informative way so I've added _another_ name field that should be used to identify the data provider.
> 2185 source info in source data

- ingestion/functions/retrieval/retrieval.py
This should fix MemoryError on attempting encoding
> retrieval: remove unnecessary decode-encode step

- .github/workflows/ingestion-error-reporter-deploy.yml
- ingestion/monitoring/Dockerfile
- ingestion/monitoring/README.md
- ingestion/monitoring/errorLogsToSlack.py
- ingestion/monitoring/poetry.lock
- ingestion/monitoring/pyproject.toml
> 1564 error logs to slack

- .github/workflows/ingestion-error-reporter-deploy.yml
> push the correct image to ECR #1564

- verification/curator-service/ui/src/components/SnackbarAlert/index.tsx
- verification/curator-service/ui/src/components/landing-page/LandingPage.tsx
- verification/curator-service/ui/src/components/landing-page/PartnerLogos.tsx
- verification/curator-service/ui/src/components/landing-page/SignUpForm.tsx
- verification/curator-service/ui/src/redux/auth/slice.ts
https://github.com/globaldothealth/list/issues/2297
> fix for login page ready

- geocoding/location-service/api/openapi.yaml
- geocoding/location-service/src/app/main.py
- geocoding/location-service/src/app/utm_to_latlong.py
- geocoding/location-service/test/test_utm_converter.py
- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/controllers/geocode.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/test/geocode.test.ts
This conversion will be useful for getting Panama data ingested.
> Utm coordinates in location service

- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/controllers/sources.ts
- verification/curator-service/ui/cypress/fixtures/acknowledgment_data.json
- verification/curator-service/ui/cypress/integration/components/AcknowledgmentsPage.spec.ts
- verification/curator-service/ui/cypress/integration/components/SourceTableTest.spec.ts
- verification/curator-service/ui/cypress/integration/components/UploadsTableTest.spec.ts
- verification/curator-service/ui/cypress/support/commands.ts
- verification/curator-service/ui/src/api/models/AcknowledgmentData.ts
- verification/curator-service/ui/src/components/AcknowledgmentsPage/EnhancedTableHead.tsx
- verification/curator-service/ui/src/components/AcknowledgmentsPage/helperFunctions.ts
- verification/curator-service/ui/src/components/AcknowledgmentsPage/index.tsx
- verification/curator-service/ui/src/components/AcknowledgmentsPage/types.ts
- verification/curator-service/ui/src/redux/acknowledgmentData/selectors.ts
- verification/curator-service/ui/src/redux/acknowledgmentData/slice.ts
- verification/curator-service/ui/src/redux/acknowledgmentData/thunk.ts
**Changes**
- Updated `AcknowledgmentSource` schema
- Moved sorting and pagination logic from backend to frontend (this had to be done due to filtering out duplicated results on the frontend)
- Updated tests
> Updated acknowledgment table

- verification/curator-service/ui/cypress.json
- verification/curator-service/ui/cypress/integration/components/LinelistTableTest.spec.ts
- verification/curator-service/ui/src/components/FiltersDialog/FiltersDialog.test.tsx
- verification/curator-service/ui/src/components/FiltersDialog/index.tsx
- verification/curator-service/ui/src/components/FiltersDialog/styled.ts
- verification/curator-service/ui/src/components/LinelistTable.test.tsx
- verification/curator-service/ui/src/components/SearchBar.tsx
- verification/curator-service/ui/src/components/util/searchQuery.test.tsx
- verification/curator-service/ui/src/components/util/searchQuery.tsx
**Changes**
- Renamed `FilterdModal` -> `FiltersDialog`
- Added UX sugestions (`x` icon, "Filter" -> "Apply", the ability to select `None` in Country dropdown)
- Updated tests
> Implemented UX changes for filter dialog

- verification/curator-service/ui/src/components/App/index.tsx
- verification/curator-service/ui/src/components/FiltersDialog/index.tsx
**Changes**
- Fixed bug where user could input more than 4 digits as a year in `FiltersDialog`
> #2637 UI: Disallow future dates in filters

- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/util/search.ts
**Changes**
- Filtering by dates now uses the new `confirmationDate` field in MongoDB `cases` documents
> #2638 - Updated filtering by date logic

- data-serving/data-service/README.md
- data-serving/data-service/package-lock.json
- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/src/model/age-bucket.ts
- data-serving/data-service/src/model/case.ts
- data-serving/data-service/src/model/demographics.ts
- data-serving/data-service/src/util/case.ts
- data-serving/data-service/test/controllers/case.test.ts
- data-serving/data-service/test/util/case.test.ts
- data-serving/scripts/setup-db/migrations/20220420100113-add-age-buckets.js
- data-serving/scripts/setup-db/schemas/README.md
These are the changes to schema and data-service to support bucketed age ranges and to use them whenever a case is added or returned via the API, but not to remove the existing age range data or change data exports/UI to work with the ranges.
See documentation on the migration and data-service README for rationale behind this design.
I fully expect some e2e breakages so will wait not merge until the cypress tests are passing.
> 2670 bucket ages

- .github/workflows/update-prod-curator-db-schema.yaml
- verification/curator-service/api/src/controllers/cases.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/src/util/validate-env.ts
The S3 bucket containing data needs to change for the EU migration, and should be injected into the service to accommodate dev/QA/prod environments.
> Data bucket fix

- .github/workflows/aggregate-ci.yml
- .github/workflows/aggregate-deploy.yml
- .github/workflows/api-python-tests.yml
- .github/workflows/completeness.yml
- .github/workflows/curator-api-node.yml
- .github/workflows/curator-service-package.yml
- .github/workflows/curator-ui-node.yml
- .github/workflows/data-service-node.yml
- .github/workflows/data-service-package.yml
- .github/workflows/export-deploy.yml
- .github/workflows/export-tests.yml
- .github/workflows/freshness.yml
- .github/workflows/geocoding-service-package.yml
- .github/workflows/geocoding-service-python.yml
- .github/workflows/ingestion-cleanup-deploy.yml
- .github/workflows/ingestion-functions-deploy.yml
- .github/workflows/ingestion-functions-python.yml
- .github/workflows/integration-tests.yml
- .github/workflows/kubemon.yml
- .github/workflows/monitoring-notify.yml
- .github/workflows/monitoring-tests.yml
- .github/workflows/prune-deploy.yml
- .github/workflows/prune-uploads-tests.yml
- .github/workflows/r-package.yml
- .github/workflows/suggest-python.yml
- .github/workflows/update-dev-curator-db-schema.yml
- .github/workflows/update-prod-curator-db-schema.yaml
- data-serving/data-service/package.json
- verification/curator-service/api/package.json
Now that 22.04 LTS has been released, at some point ubuntu-latest
will point to ubuntu-22.04 which can cause unplanned breakage,
pinning CI to 20.04 until we have a migration plan.
Additionally, drop main-eu builds as EU migration is complete.
> ci: Pin Ubuntu release to 20.04 LTS

- data-serving/data-service/src/controllers/case.ts
- data-serving/data-service/test/controllers/case.test.ts
- data-serving/data-service/test/model/data/case.full.json
Data service CI was failing due to the notes removal change. After this,
setting the 'notes' field of a case document doesn't actually result in
a updated case, as the notes field is deleted by controllers, and it is
not returned from the data service APIs.
To simulate an updated document, this adds a pathogen key to a case.
> Fix data-service CI failures

- data-serving/scripts/setup-db/manual-migration-helpers/batch_delete_age_ranges.js
This is the last part of the age-bucketing work: delete the old data. Fixes #2670.
> #2670 script to delete unused age range data

- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/api/src/controllers/users.ts
- verification/curator-service/api/src/index.ts
- verification/curator-service/api/test/users.test.ts
This PR adds API endpoints to delete users. It does not have the UI changes or the cleanup process which will assign cases created by them to a nobody or community user
> curator(api): allow deleting users

- verification/curator-service/api/openapi/openapi.yaml
- verification/curator-service/ui/src/components/User.tsx
- verification/curator-service/ui/src/components/Users.tsx
Here is the UI change that allows an admin user to delete any user. There is no bulk delete action: you must choose one user, press two buttons (bring up the menu, then press delete), then confirm in a dialog box. Deleting your own account is possible, and on doing so you'll be redirected to the homepage (where you find you are logged out).
> 2672 forget users

- verification/scripts/README.md
- verification/scripts/country_codes_map/country_codes_map.py
- verification/scripts/country_codes_map/pyproject.toml
I did the work to enable this last month then got pulled into other things so never actually created the script that gathers the data. The idea is for this script's output to sit alongside the data dictionary so people know how to interpret the country data in the database.
> Add a script to fetch the list of countries #2559

- data-serving/scripts/export-data/Dockerfile_full_export
- data-serving/scripts/export-data/full_export.sh
Extra environment variables for this are already in terraform and applied, thanks @jim-sheldon!
> Add country codes maps to the data dictionaries #2559

- README.md
- data-serving/data-service/src/model/case.ts
- data-serving/data-service/src/model/date-range.ts
- data-serving/data-service/src/model/date.ts
- data-serving/data-service/src/model/exclusion-data.ts
- data-serving/data-service/src/model/genome-sequence.ts
- data-serving/data-service/src/model/revision-metadata.ts
- data-serving/data-service/src/util/validate-env.ts
- data-serving/data-service/test/model/date.test.ts
- dev/docker-compose.yml
Defines an environment variable, `OUTBREAK_DATE`, that must be configured for any G.h deployment. The data service constrains the case schema to use dates that are after this date as part of the quality control process.
> 2712 parameterise outbreak

- api/R/R/cases_cachefile.R
- api/R/R/constants.R
- api/R/R/get_cached_cases.R
- api/R/R/get_cases.R
- api/R/R/get_server.R
- api/R/man/get_cached_cases.Rd
- api/R/man/get_cases.Rd
- api/README.md
- api/python/gdh.py
- api/python/test_gdh.py
Replaced the `server` parameter with a `disease` parameter, so instead of saying "the production covid-19 line list or you have to give us a full URL", we say "the production covid-19 line list or you ask for another disease".
I used different approaches in Python and R to accept this parameter: a class constructor in Python and changing the function argument in R. I don't get the impression that R programmers expect or use classes much, and I found three different implementations of classes which made me wonder if I might pick a "wrong" one that users don't expect to see.
I'm not fully satisfied with this solution as you now can't specify self-hosted or a dev/qa instance. But I couldn't work out a way to easily parameterise the disease name (which gives the "marketing" benefit that we …
> 2712 api parameterisation

- verification/curator-service/ui/README.md
- verification/curator-service/ui/src/components/App/App.test.tsx
- verification/curator-service/ui/src/components/App/index.tsx
- verification/curator-service/ui/src/components/CaseForm.test.tsx
- verification/curator-service/ui/src/components/CaseForm.tsx
- verification/curator-service/ui/src/components/EditCase.test.tsx
- verification/curator-service/ui/src/components/EditCase.tsx
- verification/curator-service/ui/src/components/Profile.tsx
- verification/curator-service/ui/src/components/Sidebar/index.tsx
- verification/curator-service/ui/src/components/Sidebar/styled.ts
- verification/curator-service/ui/src/components/landing-page/LandingPage.tsx
- verification/curator-service/ui/src/constants/types.ts
I have parameterised the outbreak name in numerous places throughout the curator UI. Some notes:
- I didn't do the Terms of Use, because they need updating anyway (see #2675) so it can be done then
- The link on the profile page to `/api-docs` works in every environment except locally, because the UI and API are served on different ports in the local environment.
> 2712 curator UI disease name

- data-serving/reusable-data-service/reusable_data_service/controller/case_controller.py
- data-serving/reusable-data-service/reusable_data_service/main.py
- data-serving/reusable-data-service/reusable_data_service/model/filter.py
- data-serving/reusable-data-service/reusable_data_service/stores/mongo_store.py
- data-serving/reusable-data-service/tests/test_case_controller.py
- data-serving/reusable-data-service/tests/test_case_end_to_end.py
Added the first filter terms (the only field in the schema at the moment is confirmation date, so the filter is for confirmation date). Some design notes:
1. The controller parses the filter terms from the HTTP query and builds some technology-agnostic predicates.
2. The mongo store interprets the predicates to build a mongo query. It does this by adding a `to_mongo_query()` method to each type of filter. You could imagine that if we added a SQL store, it could add its own `to_sql_query()` methods allowing it to build a `WHERE` clause.
3. Keywords used to construct the filter, i.e. `dateconfirmedbefore`/`dateconfirmedafter` are the same as the existing data service.
4. On a large-scale data service you would want an index on `confirmation_date` for these searches to be efficient. I'm not …
> 2714 filter by confirmation date

- data-serving/reusable-data-service/reusable_data_service/controller/case_controller.py
- data-serving/reusable-data-service/reusable_data_service/main.py
- data-serving/reusable-data-service/reusable_data_service/model/case.py
- data-serving/reusable-data-service/reusable_data_service/stores/mongo_store.py
- data-serving/reusable-data-service/tests/test_case_controller.py
- data-serving/reusable-data-service/tests/test_case_end_to_end.py
Creating cases. Open questions:
1. do we want case creation metadata on cases?
2. do we want case revision metadata on cases?
> 2714 post new case

- data-serving/reusable-data-service/reusable_data_service/controller/case_controller.py
- data-serving/reusable-data-service/reusable_data_service/main.py
- data-serving/reusable-data-service/reusable_data_service/model/case.py
- data-serving/reusable-data-service/tests/data/case.minimal.json
- data-serving/reusable-data-service/tests/test_case_controller.py
- data-serving/reusable-data-service/tests/test_case_end_to_end.py
#2714. This is because the data in the COVID-19 platform is camelCase and I don't want to arbitrarily change things I don't need to change.
> Rename confirmation_date to camelCase to match existing data structure

- data-serving/reusable-data-service/reusable_data_service/controller/case_controller.py
- data-serving/reusable-data-service/reusable_data_service/main.py
- data-serving/reusable-data-service/reusable_data_service/model/case.py
- data-serving/reusable-data-service/reusable_data_service/model/case_reference.py
- data-serving/reusable-data-service/reusable_data_service/stores/mongo_store.py
- data-serving/reusable-data-service/reusable_data_service/util/iso_json_encoder.py
- data-serving/reusable-data-service/tests/data/case.minimal.json
- data-serving/reusable-data-service/tests/test_case_controller.py
- data-serving/reusable-data-service/tests/test_case_end_to_end.py
- data-serving/reusable-data-service/tests/test_mongo_store.py
This adds the batchUpsert endpoint, which is how bulk uploads and automatic ingestion are supported. As previously discussed with @abhidg this doesn't include curator or revision metadata, because they're unused in the Covid-19 version.
> 2714 batch upsert

- data-serving/reusable-data-service/data_service/controller/case_controller.py
- data-serving/reusable-data-service/data_service/main.py
- data-serving/reusable-data-service/data_service/model/document.py
- data-serving/reusable-data-service/data_service/model/document_update.py
- data-serving/reusable-data-service/data_service/model/filter.py
- data-serving/reusable-data-service/data_service/stores/mongo_store.py
- data-serving/reusable-data-service/tests/test_case_controller.py
- data-serving/reusable-data-service/tests/test_case_end_to_end.py
- data-serving/reusable-data-service/tests/test_case_model.py
Sorry I screwed up the history here: I accidentally worked in main, then accidentally pushed, then realised I couldn't rollback because main is protected, so reverted then rebased my working branch so I now have all the changes in one commit :(
> #2714 update case

- data-serving/reusable-data-service/data_service/controller/case_controller.py
- data-serving/reusable-data-service/data_service/main.py
- data-serving/reusable-data-service/tests/test_case_controller.py
- data-serving/reusable-data-service/tests/test_case_end_to_end.py
Just like the existing data service, I do this the easy way by getting the list of cases matching the query and calling through to the other batch update behaviour. It would be possible to make this more efficient using a mongo update_many() command.
> 2714 batch update query

- data-serving/reusable-data-service/data_service/controller/case_controller.py
- data-serving/reusable-data-service/data_service/main.py
- data-serving/reusable-data-service/data_service/model/filter.py
- data-serving/reusable-data-service/data_service/stores/mongo_store.py
- data-serving/reusable-data-service/tests/test_case_controller.py
- data-serving/reusable-data-service/tests/test_case_end_to_end.py
Both individual case deletion and batch deletion.
> 2714 delete cases

- verification/curator-service/ui/src/components/AcknowledgmentsPage/helperFunctions.ts
Changes:
- Data acknowledgments are sorted case-insensitive
> #2623 Data acknowledgments are sorted case-insensitive

- ingestion/functions/parsing/new_zealand/new_zealand.py
> Fix age parsing for New Zealand

- data-serving/reusable-data-service/data_service/controller/case_controller.py
- data-serving/reusable-data-service/data_service/controller/geocode_controller.py
- data-serving/reusable-data-service/data_service/main.py
- data-serving/reusable-data-service/poetry.lock
- data-serving/reusable-data-service/pyproject.toml
- data-serving/reusable-data-service/tests/end_to_end_fixture.py
- data-serving/reusable-data-service/tests/test_case_controller_crud_actions.py
- data-serving/reusable-data-service/tests/test_case_geocode_integration.py
- data-serving/reusable-data-service/tests/test_geocode_controller.py
- geocoding/location-service/api/openapi.yaml
Call the geocoding service when given a case location that contains a query.
> #2714 geocode

- data-serving/reusable-data-service/data_service/day_zero_fields.json
- data-serving/reusable-data-service/data_service/model/case.py
- data-serving/reusable-data-service/data_service/model/case_reference.py
- data-serving/reusable-data-service/data_service/model/document.py
- data-serving/reusable-data-service/data_service/model/field.py
- data-serving/reusable-data-service/data_service/model/geojson.py
- data-serving/reusable-data-service/data_service/stores/mongo_store.py
- data-serving/reusable-data-service/tests/test_case_controller_crud_actions.py
In this branch:
- all document validation is made generic (i.e. no field names/types are assumed in the validation logic) and pushed up to the Document class.
- all fields are defined using the `Field` model, including those on the day zero schema.
- `DayZeroCase` class is removed as these fields can be added directly to the `Case` class.
- JSON file defining the day zero data dictionary.
With these changes in place, we can easily implement the day zero data dictionary by editing the JSON file.
> #2714 prepare to define full day zero schema

- data-serving/reusable-data-service/data_service/controller/case_controller.py
- data-serving/reusable-data-service/data_service/controller/schema_controller.py
- data-serving/reusable-data-service/data_service/day_zero_fields.json
- data-serving/reusable-data-service/data_service/main.py
- data-serving/reusable-data-service/data_service/model/case_reference.py
- data-serving/reusable-data-service/data_service/model/document.py
- data-serving/reusable-data-service/data_service/model/field.py
- data-serving/reusable-data-service/data_service/stores/memory_store.py
- data-serving/reusable-data-service/data_service/stores/mongo_store.py
- data-serving/reusable-data-service/tests/data/case.excluded.json
- data-serving/reusable-data-service/tests/data/case.minimal.json
- data-serving/reusable-data-service/tests/data/case.with_location.json
- data-serving/reusable-data-service/tests/test_case_controller_crud_actions.py
- data-serving/reusable-data-service/tests/test_case_end_to_end.py
- data-serving/reusable-data-service/tests/test_case_model.py
- data-serving/reusable-data-service/tests/test_case_reference.py
- data-serving/reusable-data-service/tests/test_case_schema_integration.py
- data-serving/reusable-data-service/tests/test_reusable_data_service.py
Added a couple of fields, and redesigned most tests so that they load sample cases from JSON as I wasn't enjoying updating dozens of tests every change. Some of the other fields like age range need new model data types so I wanted to get these ones in on a separate PR before tackling that.
> #2714 day zero fields

- data-serving/reusable-data-service/data_service/day_zero_fields.json
- data-serving/reusable-data-service/data_service/model/age_range.py
- data-serving/reusable-data-service/data_service/model/case.py
- data-serving/reusable-data-service/data_service/model/field.py
- data-serving/reusable-data-service/tests/data/case.excluded.json
- data-serving/reusable-data-service/tests/data/case.minimal.json
- data-serving/reusable-data-service/tests/data/case.with_location.json
- data-serving/reusable-data-service/tests/test_age_range.py
- data-serving/reusable-data-service/tests/test_case_end_to_end.py
- data-serving/reusable-data-service/tests/test_case_model.py
- data-serving/reusable-data-service/tests/test_case_schema_integration.py
- data-serving/reusable-data-service/tests/test_geojson_model.py
- data-serving/reusable-data-service/tests/util.py
If one of the enumerated values in a field is 'other', then you get (at no additional cost to the purchaser) a string field named fieldName_other where we can store the free text value.
> #2714 fields with associated free other value

- ingestion/functions/parsing/cuba/cuba.py
- ingestion/functions/parsing/new_zealand/new_zealand.py
The split of the data into covid19-cuba-{1,2,...}.json, as described in issue #2233 is not addressed by the changes here. Any of the  covid19-cuba-{1,2,...}.json files can be parsed by the changes, as well as covid19-cuba-old.json.
> Fix KeyError parsing for Cuba

- verification/curator-service/api/src/clients/email-client.ts
- verification/curator-service/api/src/util/instance-details.ts
The object had an email message with a lowercase key.
Changes:
- changed the key of an object with an email message to uppercase for correct reference
> #2814 sign in email send correctly to users who register without google account

- verification/curator-service/api/src/controllers/auth.ts
- verification/curator-service/api/src/util/single-window-rate-limiters.ts
- verification/curator-service/ui/cypress/integration/components/LandingPage.spec.ts
Changes:
- removed skipping successful counting attempts on sign-up and reset password email link for single window rate limiters
- added resetting counting attempts on successful requests for sign-in, reset password with a token, reset the password on the user's profile for single window rate limiters
-  increased number of failed attempts for single window rate limiters
> #2812 user cannot sign in too many failed attempts change

- data-serving/data-service/src/controllers/case.ts
- verification/curator-service/ui/src/components/LinelistTable/index.tsx
**Changes**
- Added missing collations to MongoDB queries (without correct collation no indexes were used which made the queries timeout)
- Added guards for undefined values coming from the DB
> #2856 - 500 error while filtering fix

- ingestion/functions/parsing/taiwan/geocodes.json
- ingestion/functions/parsing/taiwan/get_geocodes.py
- ingestion/functions/parsing/taiwan/taiwan.py
- parsing(taiwan): update geocodes
- parsing(taiwan): add unknown gender
> fix taiwan ingestion 2

- data-serving/scripts/export-data/test_convert_age.csv
- data-serving/scripts/export-data/test_transform.py
- data-serving/scripts/export-data/transform.py
Rarely ages are in float, this is more precision than necessary,
so they are converted to integers. This fixes a ValueError
encountered on float ages
> export: support float ages, convert to integers

- verification/curator-service/Dockerfile
RECAPTCHA_SITE_KEY can be made public, only the SECRET_KEY should
not be published.
> curator: add RECAPTCHA environment variable in build #2897

- verification/curator-service/ui/cypress/e2e/components/BulkCaseForm.spec.ts
- verification/curator-service/ui/src/components/App/index.tsx
- verification/curator-service/ui/src/components/LinelistTable/helperFunctions.ts
- verification/curator-service/ui/src/components/LinelistTable/index.tsx
- verification/curator-service/ui/src/components/ViewCase.test.tsx
- verification/curator-service/ui/src/components/ViewCase.tsx
- verification/curator-service/ui/src/components/util/helperFunctions.ts
**Changes**
- Modified age parsing function
- Fixed other found bug: when user had filters set and refreshed the page there was a race condition on two queries to the DB one with the filters and one without. Because of that sometimes the results were filtered and sometimes not. This is now also fixed
> #2840 - age display bug

- verification/curator-service/api/src/controllers/cases.ts
The user object passed from the request (req) does not have
the _id field, but has id as string; use that instead of _id
for logging and updating the user document.
> curator/api: use user.id in logging

- verification/curator-service/ui/src/components/DataGuideDialog.tsx
- verification/curator-service/ui/src/components/LinelistTable/Header.tsx
- verification/curator-service/ui/src/components/ViewCase.tsx
- verification/curator-service/ui/src/index.css
- verification/curator-service/ui/src/theme/theme.ts
We have been using a combination of Mabry Pro and Inter, with Roboto
in a few places, which is the default Material UI font. This changes
all interface fonts to Inter, and brings the line list portal in
sync with the maps, which use Inter.
> curator/ui: use Inter everywhere
